### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by VirtualMoon** [dmlc/dgl#1094]
## 🐛 Bug
When I run gat's code train_ppi. py, I report the following error:

Traceback (most recent call last):
  File "train_ppi.py", line 166, in <module>
    main(args)
  File "train_ppi.py", line 57, in main
    train_dataset = LegacyPPIDataset(mode='train')
  File "E:\Anaconda3\envs\my_Pytorch\lib\site-packages\dgl\data\ppi.py", line 35, in __init__
    self._load()
  File "E:\Anaconda3\envs\my_Pytorch\lib\site-packages\dgl\data\ppi.py", line 60, in _load
    '{}/{}'.format(dir, name))
  File "E:\Anaconda3\envs\my_Pytorch\lib\site-packages\dgl\data\utils.py", line 213, in extract_archive
    archive = zipfile.ZipFile(file, 'r')
  File "E:\Anaconda3\envs\my_Pytorch\lib\zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "E:\Anaconda3\envs\my_Pytorch\lib\zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by yzh119** [comment]
Hi,
I think the PPI dataset is not downloaded successfully (because of network issue or something else).
You can try emptying the directory `$HOME/.dgl/` (or just removing PPI dataset related files) and run gat code again.

**Comment by VirtualMoon** [comment]
Sure
I have solved it
Thank you
