### ISSUE TITLE
sample dataset 'karate club' cannot instantiate

### ISSUE THREAD

**Issue by meltzerpete** [dmlc/dgl#1208]
## 🐛 Bug

AttributeError on instantiation of KarateClub graph

## To Reproduce

```python
from dgl.data import karate

graph = karate.KarateClub()
```

gives error:

```txt
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/...", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/...", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/...", line 3, in <module>
    graph = karate.KarateClub()
  File "/home/.../dgl/data/karate.py", line 21, in __init__
    [kG.node[i]['club'] != 'Mr. Hi' for i in kG.nodes]).astype(np.int64)
  File "/home/.../dgl/data/karate.py", line 21, in <listcomp>
    [kG.node[i]['club'] != 'Mr. Hi' for i in kG.nodes]).astype(np.int64)
AttributeError: 'Graph' object has no attribute 'node'
```

## Expected behavior

KarateClub is sucessfully instantiated with no exceptions thrown.

## Environment

 - DGL Version (e.g., 1.0): 0.4.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 1.3.1
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7

**Comment by meltzerpete** [comment]
Ah I can see this has actually already been fixed - using the nightly build prerelease has fixed the issue. Thanks!
