### ISSUE TITLE
Bug in han-hetero 

### ISSUE THREAD

**Issue by bioannidis** [dmlc/dgl#1277]
This bug appears after following the instructions here
https://github.com/dmlc/dgl/tree/master/examples/pytorch/han

Reproduce in two steps

1. svn checkout https://github.com/dmlc/dgl/trunk/examples/pytorch/han/
2. python main.py --hetero

Thank you.
Vassilis Ioannidis.
Amazon applied scientist

Error
Created directory results/ACMRaw_2020-02-20_18-37-46
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    main(args)
  File "main.py", line 62, in main
    logits = model(g, features)
  File "/Users/ivasilei/opt/anaconda3/envs/my_dgl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/ivasilei/han/model_hetero.py", line 101, in forward
    h = gnn(g, h)
  File "/Users/ivasilei/opt/anaconda3/envs/my_dgl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/ivasilei/han/model_hetero.py", line 83, in forward
    semantic_embeddings.append(self.gat_layers[i](new_g, h).flatten(1))
  File "/Users/ivasilei/opt/anaconda3/envs/my_dgl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/ivasilei/opt/anaconda3/envs/my_dgl/lib/python3.7/site-packages/dgl/nn/pytorch/conv/gatconv.py", line 111, in forward
    graph.edata['a'] = self.attn_drop(edge_softmax(graph, e))
  File "/Users/ivasilei/opt/anaconda3/envs/my_dgl/lib/python3.7/site-packages/dgl/nn/pytorch/softmax.py", line 179, in edge_softmax
    return EdgeSoftmax.apply(graph, logits, eids)
  File "/Users/ivasilei/opt/anaconda3/envs/my_dgl/lib/python3.7/site-packages/dgl/nn/pytorch/softmax.py", line 52, in forward
    gidx = g._graph.get_immutable_gidx(utils.to_dgl_context(score.device))
  File "dgl/_ffi/_cython/./object.pxi", line 64, in dgl._ffi._cy3.core.ObjectBase.__getattr__
AttributeError: '<class 'dgl.heterograph_index.HeteroGraphIndex'>' object has no attribute 'get_immutable_gidx'

**Comment by BarclayII** [comment]
Hi, this is a duplicate of #1237 and it is fixed in #1239 .
The fix should be availalble in the nightly build.  However, it seems that you are using Mac which does not have nightly builds yet.  Could you try installing from source instead?

**Comment by bioannidis** [comment]
Thanks it works now
