### ISSUE TITLE
Cannot assign node features after removing edges

### ISSUE THREAD

**Issue by HaoZhongkai** [dmlc/dgl#1287]
## 🐛 Bug
Assigning node features using  "g.ndata['h']=xxx" will report bugs

## To Reproduce

```python
import dgl
import torch
g = dgl.DGLGraph()
g.add_nodes(5)
g.add_edges([0,2,3,1,1],[1,0,3,1,0],data={'h':torch.ones(5,3)})
g.remove_edges([0,1])
g.ndata['feats'] = torch.ones([5,6])
```

Report bugs:
```
Traceback (most recent call last):
  File "/home/zkgntmp01/DyGNN/DGNN/test/node_feats_dgl.py", line 19, in <module>
    g.ndata['feats'] = torch.ones([5,6])
  File "/home/zkgntmp01/anaconda3/lib/python3.7/site-packages/dgl/view.py", line 65, in __setitem__
    self._graph.set_n_repr({key : val}, self._nodes)
  File "/home/zkgntmp01/anaconda3/lib/python3.7/site-packages/dgl/graph.py", line 1794, in set_n_repr
    self._node_frame[key] = val
  File "/home/zkgntmp01/anaconda3/lib/python3.7/site-packages/dgl/frame.py", line 671, in __setitem__
    self.update_data(key, val, inplace=False)
  File "/home/zkgntmp01/anaconda3/lib/python3.7/site-packages/dgl/frame.py", line 698, in update_data
    self.update_column(key, val, inplace=inplace)
  File "/home/zkgntmp01/anaconda3/lib/python3.7/site-packages/dgl/frame.py", line 729, in update_column
    self._frame[name] = data
  File "/home/zkgntmp01/anaconda3/lib/python3.7/site-packages/dgl/frame.py", line 328, in __setitem__
    self.update_column(name, data)
  File "/home/zkgntmp01/anaconda3/lib/python3.7/site-packages/dgl/frame.py", line 415, in update_column
    (self.num_rows, len(col)))
dgl._ffi.base.DGLError: Expected data to have 0 rows, got 5.
```

## Expected behavior
output a Tensor with size [5.6]

## Environment

 - DGL Version (0.5a):
 - Backend Library & Version (Pytorch 1.3.0):
 - OS (Linux):
 - How you installed DGL (`pip`):
 - Python version: 3.7.0
 - CUDA/cuDNN version 10.1

**Comment by BarclayII** [comment]
Just a note.  Calling `g.ndata['feats'] = torch.ones([5,6])` the second time works.  Should fix this.

**Comment by yzh119** [comment]
Thanks for reporting this bug, will fix it soon.

**Comment by yzh119** [comment]
Bug fixed, please try the master branch or dgl nightly build version and see if the problem persists.
