### ISSUE TITLE
KG 

### ISSUE THREAD

**Issue by maelstrom9** [dmlc/dgl#1370]
Ran into an issue while using KG embeddings train.py

# To Reproduce

1. Install dgl 0.4.2
2. clone dgl
3. run the fb15k training by the given command in the documentation:

python3 train.py --model DistMult --dataset FB15k --batch_size 1024 \
    --neg_sample_size 256 --hidden_dim 2000 --gamma 500.0 --lr 0.1 --max_step 100000 \
    --batch_size_eval 16 --gpu 0 --valid --test -adv

**Issue:** 

Traceback (most recent call last):
  File "/Users/sai/Downloads/dgl2/apps/kg/train.py", line 401, in <module>
    run(args, logger)
  File "/Users/sai/Downloads/dgl2/apps/kg/train.py", line 336, in run
    train(args, model, train_sampler, valid_samplers, rel_parts=rel_parts)
  File "/Users/sai/Downloads/dgl2/apps/kg/train_pytorch.py", line 136, in train
    pos_g, neg_g = next(train_sampler)
  File "/Users/sai/Downloads/dgl2/apps/kg/dataloader/sampler.py", line 702, in __next__
    pos_g, neg_g = next(self.iterator_tail)
  File "/Users/sai/Downloads/dgl2/apps/kg/dataloader/sampler.py", line 711, in one_shot_iterator
    is_chunked, neg_head, num_nodes)
  File "/Users/sai/Downloads/dgl2/apps/kg/dataloader/sampler.py", line 475, in create_neg_subgraph
    neg_sample_size, neg_head)
  File "/Users/sai/Downloads/dgl2/apps/kg/dataloader/sampler.py", line 404, in __init__
    parent=subg.parent)
AttributeError: 'EdgeSubgraph' object has no attribute 'parent'

**Comment by zheng-da** [comment]
For now, you'll have to install DGL nightly build to run DGL-KE. We are going to release DGL 0.4.3 to support DGL-KE. Please try `pip3 install --pre dgl` instead.

**Comment by maelstrom9** [comment]
Thanks!!
