### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by ZSCDumin** [dmlc/dgl#1423]
Warning: No forward pass information available. Enable detect anomaly during forward pass for more information. (print_stack at ..\torch\csrc\autograd\python_anomaly_mode.cpp:40)
Traceback (most recent call last):
  File "E:/GithubProjects/AMNCF-最新版/IPM/code/AMNCF_GPU/main.py", line 107, in <module>
    training(amncf, dataset.get_user_dataloader(config.batch_size), epoch, config, 'user')
  File "E:/GithubProjects/AMNCF-最新版/IPM/code/AMNCF_GPU/main.py", line 36, in training
    loss.backward()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\autograd\__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [10, 32]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

Process finished with exit code 1

**Comment by VoVAllen** [comment]
Hi,

Did you do something like `a[...]=...` as a is a tensor? Could you post more codes for us to debug?

**Comment by VoVAllen** [comment]
You can add `torch.autograd.set_detect_anomaly(True)` at the beginning of your code to get more detailed error message

**Comment by ZSCDumin** [comment]
&nbsp;Thank you very much! I just want to use the tensor generated from the HeteroRGCN to make a&nbsp; predict work.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jinjing Zhou"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 下午2:49
收件人: "dmlc/dgl"<dgl@noreply.github.com&gt;; 
抄送: "放飞的心（杜敏）"<2712220318@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dmlc/dgl] code error (#1423)





 
You can add torch.autograd.set_detect_anomaly(True) at the beginning of your code to get more detailed error message
 
&mdash;

**Comment by tigerkkzz** [comment]
> You can add `torch.autograd.set_detect_anomaly(True)` at the beginning of your code to get more detailed error message



> Hi,
> 
> Did you do something like `a[...]=...` as a is a tensor? Could you post more codes for us to debug?
Hello, I have met the problem you mentioned. Is there any solution？thanks
