### ISSUE TITLE
Save DGLHeteroGraph

### ISSUE THREAD

**Issue by weihua916** [dmlc/dgl#1524]
How can we save heterogeneous graph?

```
import dgl
from dgl.data.utils import load_graphs, save_graphs
import torch

ratings = dgl.heterograph(
    {('user', '+1', 'movie') : [(0, 0), (0, 1), (1, 0)],
     ('user', '-1', 'movie') : [(2, 1)]})
ratings.nodes['user'].data['h'] = torch.zeros(3,4)
ratings.edges[('user', '+1', 'movie')].data['h'] = torch.zeros(3,4)

save_graphs('test', ratings, {'label': torch.tensor([[1,2,3]])})
graph, label_dict = load_graphs('test')

print(graph)
```

This code prints empty list `[]` for ver0.4.2, and the following error for ver0.4.3.post2.

```
Traceback (most recent call last):
  File "save_hetero.py", line 12, in <module>
    save_graphs('test', ratings, {'label': torch.tensor([[1,2,3]])})
  File "/anaconda3/lib/python3.7/site-packages/dgl/data/graph_serialize.py", line 107, in save_graphs
    gdata_list = [GraphData.create(g) for g in g_list]
  File "/anaconda3/lib/python3.7/site-packages/dgl/data/graph_serialize.py", line 107, in <listcomp>
    gdata_list = [GraphData.create(g) for g in g_list]
  File "/anaconda3/lib/python3.7/site-packages/dgl/heterograph.py", line 901, in __getitem__
    raise DGLError('Invalid key "{}". Must be one of the edge types.'.format(orig_key))
dgl._ffi.base.DGLError: Invalid key "0". Must be one of the edge types.
```

**Comment by VoVAllen** [comment]
HeteroGraph saving is not supported yet. Expected to add this feature before next weekend.

**Comment by VoVAllen** [comment]
You can use pickle for now

**Comment by weihua916** [comment]
Ok, sounds good. Looking forward to it. Thanks!

**Comment by weihua916** [comment]
Could you give me example implementation of graph saving using `pickle`?
I tried the following code and got the error below.

```python
import dgl
from dgl.data.utils import load_graphs, save_graphs
import torch

ratings = dgl.heterograph(
    {('user', '+1', 'movie') : [(0, 0), (0, 1), (1, 0)],
     ('user', '-1', 'movie') : [(2, 1)]})
ratings.nodes['user'].data['h'] = torch.zeros(3,4)
ratings.edges[('user', '+1', 'movie')].data['h'] = torch.zeros(3,4)

torch.save(ratings, 'test')
print(torch.load('test'))
```

```bash
Traceback (most recent call last):
  File "save_hetero.py", line 15, in <module>
    print(torch.load('test'))
  File "/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/anaconda3/lib/python3.7/site-packages/dgl/heterograph_index.py", line 42, in __setstate__
    num_src = number_of_nodes[src_ntype]
IndexError: list index out of range
```

**Comment by BarclayII** [comment]
Currently we are not officially supporting saving/loading with `torch.save/load`.  Could you try `pickle.dump/load` instead?

And I observed that graphs saved and loaded with `torch.save/load` would have its memory corrupted.

**Comment by weihua916** [comment]
Thank you so much! Yeah, `pickle` does works.

**Comment by ivanjacobsec** [comment]
For the copy pasters:
def save_graph(G,path='test'):
  
    with open(path, 'wb') as file:
        pickle.dump(G, file)

def open_graph(path='test'):
    with open(path, 'rb') as file:
        N = pickle.load(file)
    return N

G=create_graph()
save_graph(G)
N=open_graph()

**Comment by DanielBigGodness** [comment]
u guys r great!
