### ISSUE TITLE
JTNN generate vocab file

### ISSUE THREAD

**Issue by ad05bzag** [dmlc/dgl#1553]
## How to generate vocabulary for JTNN 

I have been trying to use JTNN from life_sci/examples/generative_models.  `test_data` is my file with one SMILES per line, for total of 10000 molecules.
When running `python train.py -t test_data`, i get the following error:
```
Using backend: pytorch
Loading data...
Loading finished.
	Num samples: 10000
	Vocab file: /root/.dgl/jtnn/vocab.txt
Model #Params: 1221K
Traceback (most recent call last):
  File "train.py", line 129, in <module>
    train()
  File "train.py", line 92, in train
    for it, batch in enumerate(dataloader):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/tf/notebooks/try_DGL_RDKit2018/jtnn/datautils.py", line 62, in __getitem__
    wid = _set_node_id(mol_tree, self.vocab)
  File "/tf/notebooks/try_DGL_RDKit2018/jtnn/datautils.py", line 29, in _set_node_id
    wid.append(vocab.get_index(mol_tree.nodes_dict[node]['smiles']))
  File "/tf/notebooks/try_DGL_RDKit2018/jtnn/mol_tree.py", line 21, in get_index
    return self.vmap[smiles]
KeyError: 'C1=CC2=CC=C(C=C2)CCC2=CC=CC(=C2)OC2=CC=C(C=C2)CC1'
```

I think it is because I am using a downloaded version of the vocab file with my own dataset that contains a number of compounds not in ZINC. So, how do i generate my own vocabulary file?

## Environment

 - DGL Version: 0.5a200523
 - Backend Library & Version: Pytorch 1.5.0
 - OS (e.g., Linux): 18.04
 - How you installed DGL (`conda`, `pip`, source):  `!{sys.executable} -m pip install --pre dgl-cu102`
 - Build command you used (if compiling from source): na
 - Python version: 3.7.6
 - CUDA/cuDNN version (if applicable): 10.2.89
 - GPU models and configuration (e.g. V100): Tesla P100-PCIE-16GB
 - Any other relevant information: Rdkit version 2018.09.3

**Comment by mufeili** [comment]
Sorry for the late reply, this should be fixed with #1577 .
