### ISSUE TITLE
[Bug] Failed to pass HeteroGraph between process

### ISSUE THREAD

**Issue by VoVAllen** [dmlc/dgl#1639]
## 🐛 Bug

Cannot pass graphs between processes

```python
from dgl.distributed import partition_graph
from dgl.data import CitationGraphDataset
import dgl
import torch as th


def test(gg):
    return gg

def main():
    g = CitationGraphDataset("cora")[0]
    g.readonly()
    import multiprocessing as mp
    gg = dgl.as_heterograph(g)
    gg = gg.to(th.device("cpu"))
    ctx = mp.get_context("spawn")

    # gg.__getstate__()

    p = ctx.Process(target=test, args=(gg, ))

    p.start()
    p.join()


if __name__ == "__main__":
    main()
```

Error message:
```python
Traceback (most recent call last):
  File "t.py", line 27, in <module>
    main()
  File "t.py", line 22, in main
    p.start()
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 59, in _launch
    cmd, self._fds)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/multiprocessing/util.py", line 417, in spawnv_passfds
    False, False, None)
ValueError: bad value(s) in fds_to_keep
```

**Comment by RadoxWoolf** [comment]
Hi @VoVAllen this is ribhu from the DGL forum. I had started [this](https://discuss.dgl.ai/t/training-dgl-heterogeneous-graphs-on-gpus-with-multiprocessing/1036?u=ribhu) discussion based on which you had opened this issue. I'm curious if there been any updates on this? I want to use heterographs with the functionality to pass them between processes on cuda as soon as possible. Thanks!

**Comment by VoVAllen** [comment]
Hi,

Unfortunately I haven't found the solution yet (already investigates this for several days). One workaround is that if this part is not really speed sensitive, we can make this work by turning off pytorch's optimization on inter process communication.

The way to do that is adding the function below and call it after import torch
```python
def deregister_torch_ipc():
    from multiprocessing.reduction import ForkingPickler
    import torch
    ForkingPickler._extra_reducers.pop(torch.cuda.Event)
    for t in torch._storage_classes:
        ForkingPickler._extra_reducers.pop(t)
    for t in torch._tensor_classes:
        ForkingPickler._extra_reducers.pop(t)
    ForkingPickler._extra_reducers.pop(torch.Tensor)
    ForkingPickler._extra_reducers.pop(torch.nn.parameter.Parameter)

import torch
deregister_torch_ipc()
```

And sorry for the inconvenience, and I'll keep investigating to find a better solution

**Comment by yaox12** [comment]
Should have been fixed now.
