### ISSUE TITLE
Number of nodes wrong when batching blocks

### ISSUE THREAD

**Issue by BarclayII** [dmlc/dgl#1837]
## 🐛 Bug

See the following reproduction code

## To Reproduce

```python
plays_spmat = ssp.coo_matrix(([1, 1, 1, 1], ([0, 1, 2, 1], [0, 0, 1, 1])))
wishes_nx = nx.DiGraph()
wishes_nx.add_nodes_from(['u0', 'u1', 'u2'], bipartite=0)
wishes_nx.add_nodes_from(['g0', 'g1'], bipartite=1)
wishes_nx.add_edge('u0', 'g1', id=0)
wishes_nx.add_edge('u2', 'g0', id=1)

follows_g = dgl.graph([(0, 1), (1, 2)], 'user', 'follows')
plays_g = dgl.bipartite(plays_spmat, 'user', 'plays', 'game')
wishes_g = dgl.bipartite(wishes_nx, 'user', 'wishes', 'game')
develops_g = dgl.bipartite([(0, 0), (1, 1)], 'developer', 'develops', 'game')
g = dgl.hetero_from_relations([follows_g, plays_g, wishes_g, develops_g])
g2 = dgl.hetero_from_relations([follows_g, plays_g, wishes_g, develops_g])

block1 = dgl.to_block(g, {'user': [1, 2], 'game': [0, 1], 'developer': []})
block2 = dgl.to_block(g2, {'user': [1, 2], 'game': [0, 1], 'developer': []})
batched_block = dgl.batch_hetero([block1, block2])
assert block1.number_of_src_nodes('developer') == 2             # passes
assert block2.number_of_src_nodes('developer') == 2             # passes
assert batched_block.number_of_src_nodes('developer') == 4      # fails, = 0
```

## Expected behavior

The last test should return pass.

## Environment

 - DGL Version (e.g., 1.0): master
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by classicsong** [comment]
It seems batching of block is not well tested

**Comment by githubgregersen** [comment]
I also came across a batching problem, directly with heterographs:
```
g0 = dgl.heterograph({
     ('user', 'plays', 'game'): [(0, 0), (1, 0), (1, 1), (2, 1)],
     }, num_nodes_dict={"foo":1, "user":3, "game":2})
g1 = dgl.heterograph({
     ('user', 'plays', 'game'): [(0, 0), (1, 0), (1, 1), (2, 1)],
     }, num_nodes_dict={"foo": 2, "user":3, "game":2})
gall = dgl.batch_hetero([g0, g1])
print(g0)
print(g1)
print(gall)
```
prints:
```
Graph(num_nodes={'foo': 1, 'game': 2, 'user': 3},
      num_edges={('user', 'plays', 'game'): 4},
      metagraph=[('user', 'game')])
Graph(num_nodes={'foo': 2, 'game': 2, 'user': 3},
      num_edges={('user', 'plays', 'game'): 4},
      metagraph=[('user', 'game')])
Graph(num_nodes={'foo': 0, 'game': 4, 'user': 6},
      num_edges={('user', 'plays', 'game'): 8},
      metagraph=[('user', 'game')])
```
So it seems that nodes without edges get dropped when batching heterographs

**Comment by theisjendal** [comment]
Hi,

I think this is an issue again (using dgl 0.9.1) if creating a block/msg without including dst nodes in src.
```
>>> graph_data = {
   ('drug', 'interacts', 'drug'): (th.tensor([0, 1]), th.tensor([1, 2])),
   ('drug', 'interacts', 'gene'): (th.tensor([0, 1]), th.tensor([2, 3])),
   ('drug', 'treats', 'disease'): (th.tensor([1]), th.tensor([2]))
}
>>> g = dgl.to_block(dgl.heterograph(graph_data), include_dst_in_src=False)
>>> g
Block(num_src_nodes={'disease': 0, 'drug': 2, 'gene': 0},
      num_dst_nodes={'disease': 1, 'drug': 2, 'gene': 2},
      num_edges={('drug', 'interacts', 'drug'): 2, ('drug', 'interacts', 'gene'): 2, ('drug', 'treats', 'disease'): 1},
      metagraph=[('drug', 'drug', 'interacts'), ('drug', 'gene', 'interacts'), ('drug', 'disease', 'treats')])
```
Clearly there are two nodes of type two, yet if I get the number of nodes using:
```
>>> g.num_nodes('gene')
0
```

This means I get the following error message when trying to assign features to the dst nodes:
```
>>> g.dstdata.update({'h': {'gene': th.tensor([0, 1])}})
Traceback (most recent call last):
  File path/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/usr/lib/python3.8/_collections_abc.py", line 832, in update
    self[key] = other[key]
  File "path2/.venv/lib/python3.8/site-packages/dgl/view.py", line 85, in __setitem__
    self._graph._set_n_repr(ntid, self._nodes, {key: data})
  File "path2/.venv/lib/python3.8/site-packages/dgl/heterograph.py", line 4119, in _set_n_repr
    raise DGLError('Expect number of features to match number of nodes (len(u)).'
dgl._ffi.base.DGLError: Expect number of features to match number of nodes (len(u)). Got 2 and 0 instead.
```
As you can see, it uses the `self._graph.number_of_nodes(ntid)` in the on line 4112 in heterograph.py, which returns `0` as shown above. 

I don't know if this is on purpose or not. If it is on purpose, how should I assign the features instead?

Of course, if I set `include_dst_in_src` to `true` then it would work, but seems like it should work when set to `false`.

Thanks!
