### ISSUE TITLE
AttributeError: 'Index' object has no attribute 'contiguous'

### ISSUE THREAD

**Issue by xiaofangdyd** [dmlc/dgl#1931]
## 🐛 Bug & my solutions

Hello, I test the **rgcn/link_predict.py** and found some bugs.
I replaced some python files(the file list are as follows) from github to my `dgl0.4.2post3` package in order to solve the `No module named xxx` problems

**file list**
- dgl/data/dgl_dataset.py & knowledge_graph.py & tensor_serialize.py
 - dgl/utils/*

but I also got another Error like this:
```shell
Traceback (most recent call last):
  File "link_predict.py", line 259, in <module>
    main(args)
  File "link_predict.py", line 89, in main
    data = load_data(args.dataset)
  File "D:\Anaconda3\envs\gnn\lib\site-packages\dgl\data\knowledge_graph.py", line 721, in load_data
    return FB15k237Dataset()
  File "D:\Anaconda3\envs\gnn\lib\site-packages\dgl\data\knowledge_graph.py", line 428, in __init__
    super(FB15k237Dataset, self).__init__(name, reverse, raw_dir, force_reload, verbose)
  File "D:\Anaconda3\envs\gnn\lib\site-packages\dgl\data\knowledge_graph.py", line 48, in __init__
    verbose=verbose)
  File "D:\Anaconda3\envs\gnn\lib\site-packages\dgl\data\dgl_dataset.py", line 263, in __init__
    verbose=verbose)
  File "D:\Anaconda3\envs\gnn\lib\site-packages\dgl\data\dgl_dataset.py", line 71, in __init__
    self._load()
  File "D:\Anaconda3\envs\gnn\lib\site-packages\dgl\data\dgl_dataset.py", line 155, in _load
    self.process()
  File "D:\Anaconda3\envs\gnn\lib\site-packages\dgl\data\knowledge_graph.py", line 90, in process
    g, data = build_knowledge_graph(num_nodes, num_rels, train, valid, test, reverse=self.reverse)
  File "D:\Anaconda3\envs\gnn\lib\site-packages\dgl\data\knowledge_graph.py", line 321, in build_knowledge_graph
    g = dgl_graph((s, d), num_nodes=num_nodes)
  File "D:\Anaconda3\envs\gnn\lib\site-packages\dgl\convert.py", line 137, in graph
    restrict_format=restrict_format)
  File "D:\Anaconda3\envs\gnn\lib\site-packages\dgl\convert.py", line 811, in create_from_edges
    num_ntypes, urange, vrange, u, v, restrict_format)
  File "D:\Anaconda3\envs\gnn\lib\site-packages\dgl\heterograph_index.py", line 982, in create_unitgraph_from_coo
    F.to_dgl_nd(row), F.to_dgl_nd(col),
  File "D:\Anaconda3\envs\gnn\lib\site-packages\dgl\backend\__init__.py", line 94, in to_dgl_nd
    return zerocopy_to_dgl_ndarray(data)
  File "D:\Anaconda3\envs\gnn\lib\site-packages\dgl\backend\pytorch\tensor.py", line 283, in zerocopy_to_dgl_ndarray
    return nd.from_dlpack(dlpack.to_dlpack(input.contiguous()))
AttributeError: 'Index' object has no attribute 'contiguous'
```
So I add some code as follows in `dgl/utils/internal.py`
```python
import torch
def contiguous(self):
    if self._pydata is None:
        self._pydata = self.tonumpy()
    return torch.from_numpy(self._pydata)
```
It may be a outdated API, but you can easily solve this problem.

Also I found another way to avoid this problem.
Firstly change the `dgl/data/knowledge_graph.py  -> build_knowledge_graph()   -> line 323  -> g = dgl_graph((s, d), num_nodes=num_nodes)`  to:
```python
g = dgl.DGLGraph()
g.add_nodes(num_nodes)
g.add_edges(s, d)
```
Secondly change the `examples/pytorch/rgcn/utils.py  ->  build_graph_from_triplets()  -> line 138  -> g = dgl.graph([])` to `g = dgl.DGLGraph()`

the first way can **only** fix the AttributeError: 'Index' object has no attribute 'contiguous'
the second way can avoid this Error and run the R-GCN's `link_predict` code well.

Finally, Thanks for your work and the DGL Package！

**Comment by yzh119** [comment]
Hi @xiaofangdyd , recently dgl repo is under extensive refactoring, and we have changed many APIs, so `dgl0.4.2post3` is no longer compatible with our example on the master branch.
You can either use our nightly build version by `pip install --pre dgl-cu**`, or wait for the dgl v0.5 release (coming soon).
The link prediction examples works well with dgl nightly build version on my machine.

**Comment by xiaofangdyd** [comment]
@yzh119 thanks for your help, I’m looking forward to the DGL v0.5 version. Good job!
