### ISSUE TITLE
Error [graphsage distributed, RANK not SET]

### ISSUE THREAD

**Issue by snash4** [dmlc/dgl#2013]
## ❓ Questions and Help

Tested on updated DGL code. 
dgl version is : '0.5a200812'

The standalone example works fine. But when I am trying to run the graphsage distributed example on two machines, I get this following error for each of the process:

```
Traceback (most recent call last):
  File "train_dist.py", line 330, in <module>
    main(args)
  File "train_dist.py", line 273, in main
    th.distributed.init_process_group(backend='gloo')
  File "/home/us4j4248/work/tools/anaconda3/envs/dglnew/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 393, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/us4j4248/work/tools/anaconda3/envs/dglnew/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 148, in _env_rendezvous_handler
    raise _env_error("RANK")
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set
```
Please help.
Thanks.

**Comment by aksnzhy** [comment]
Can you try the latest code on master branch? Please let me know if you still see this error.

**Comment by snash4** [comment]
pulled the latest code, and now it doesn't give me error. 
However, I ran into another problem, though probably not an issue of DGL.
I ran into the following issue
```
Warning!
Interface: virbr0-nic
IP address not available for interface.
```
After this warning, the process goes into the waiting.
Any suggestions on this.

**Comment by aksnzhy** [comment]
It seems that your networking hardware has not been assigned to the right IP address. Can you check you hardware?

**Comment by snash4** [comment]
I have run example codes (non-dgl) and launched them using torch.distributed script, they work fine. 

how can i get more information on this error? 

thanks

**Comment by VoVAllen** [comment]
Could you check whether the ip address in ip_config.txt is properly configured? Perhaps it should be the private IP address

**Comment by BarclayII** [comment]
Also, what was your distributed environment?  Like, were you using several AWS EC2 instances, or using slurm, or some other platforms?

**Comment by aksnzhy** [comment]
@snash4 Can you change the `--num_worker` parameter to the same value of `--num_sampler? `

**Comment by snash4** [comment]
@aksnzhy thanks it worked but now it gets stuck at some other place. I did some debugging. Here is the detail that I found:
 I have two machines, M0 is the master_server and M1 is another machine. 
M0 proceeds and enters in Epoch loop and gets stuck here:
`for step, blocks in enumerate(dataloader):`
M1 gets blocked in this call:
`th.distributed.init_process_group(backend='gloo')`

For M0, I understand it is waiting for the other worker to start.
Why M1 gets blocked? Any pointers on that. 
Thanks.

**Comment by aksnzhy** [comment]
`th.distributed.init_process_group(backend='gloo')` 

This line of code is the pyrorch distributed initialization, actually is not part of DGL distributed. Can you make sure that all the port is available?

**Comment by snash4** [comment]
updated the versions in all machines and it worked.
thanks.

**Comment by maqy1995** [comment]
> updated the versions in all machines and it worked.
> thanks.
Hi, I met the same problem, and my environment is similar to you.
Will these warnings cause the program to fail or blocking?
>Warning!
>Interface: virbr0-nic
>IP address not available for interface.

Can you tell me which version you used to fix this problem?

**Comment by snash4** [comment]
Hi, 
pull the nightly build of DGL, and as mentioned in one of the comments, set change the --num_workers parameter to the same value of --num_samplers.

Do you have multiple ip addresses associated with a machine?

**Comment by maqy1995** [comment]
My environment is 3 machines running CentOS7, each machine has 4 NICs but I only configured IP in one NIC. 
Each machine also has a management IP. I have docker services running on the machines too, and I run other distributed examples of PyTorch is ok.
the command I used is:
```
python3 ./launch.py --workspace /home/maqy/sage-dist-run/ --num_trainers 1 --num_samplers 3 --num_servers 1 --part_config reddit/reddit.json --ip_config ip_config.txt "python3 dgl_code/train_dist.py --graph_name reddit --ip_config ip_config.txt --num_servers 1 --num_epochs 1 --batch_size 1000 --num_workers 3"
```
but it will be blocked like that:
```
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Namespace(batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='reddit', id=None, ip_config='ip_config.txt', local_rank=0, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=1, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=3, part_config=None, standalone=False)
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Namespace(batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='reddit', id=None, ip_config='ip_config.txt', local_rank=0, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=1, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=3, part_config=None, standalone=False)
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Warning!
Interface: veth3c0b61d
IP address not available for interface.
Warning!
Interface: veth6e68154
IP address not available for interface.
Namespace(batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='reddit', id=None, ip_config='ip_config.txt', local_rank=0, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=1, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=3, part_config=None, standalone=False)
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Warning!
Interface: vethaafffaa
IP address not available for interface.
Warning!
Interface: veth90e9890
IP address not available for interface.
Machine (1) client (0) connect to server successfuly!
Machine (0) client (7) connect to server successfuly!
Machine (2) client (9) connect to server successfuly!
rank: 0
rank: 2
rank: 1
part 2, train: 51143 (local: 49140), val: 7943 (local: 7943), test: 18567 (local: 18567)
part 0, train: 51144 (local: 50502), val: 7944 (local: 7865), test: 18568 (local: 18167)
part 1, train: 51144 (local: 51144), val: 7944 (local: 7685), test: 18568 (local: 17829)
#labels: 41
#labels: 41
#labels: 41
```
Any ideas to fix it?

**Comment by snash4** [comment]
I don't' think it is the problem of NICs. These are warnings.
the servers are getting connected properly as you see that these results are coming from three servers
_part 2, train: 51143 (local: 49140), val: 7943 (local: 7943), test: 18567 (local: 18567)
part 0, train: 51144 (local: 50502), val: 7944 (local: 7865), test: 18568 (local: 18167)
part 1, train: 51144 (local: 51144), val: 7944 (local: 7685), test: 18568 (local: 17829)_

Are you running it on CPUs or GPUs? 
If GPUs, how many GPUs are there on each machine?

**Comment by maqy1995** [comment]
Thank you for your reply.
I tried both GPUs and CPUs, the result is same.
after the process is blocked for a while, some errors are printed, total info is below:
```
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
Namespace(batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='reddit', id=None, ip_config='ip_config.txt', local_rank=0, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=1, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=3, part_config=None, standalone=False)
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Namespace(batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='reddit', id=None, ip_config='ip_config.txt', local_rank=0, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=1, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=3, part_config=None, standalone=False)
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Warning!
Interface: veth3c0b61d
IP address not available for interface.
Warning!
Interface: veth6e68154
IP address not available for interface.
Namespace(batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='reddit', id=None, ip_config='ip_config.txt', local_rank=0, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=1, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=3, part_config=None, standalone=False)
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Warning!
Interface: vethaafffaa
IP address not available for interface.
Warning!
Interface: veth90e9890
IP address not available for interface.
Machine (1) client (0) connect to server successfuly!
Machine (0) client (7) connect to server successfuly!
Machine (2) client (9) connect to server successfuly!
rank: 0
rank: 2
rank: 1
part 2, train: 51143 (local: 49140), val: 7943 (local: 7943), test: 18567 (local: 18567)
part 0, train: 51144 (local: 50502), val: 7944 (local: 7865), test: 18568 (local: 18167)
part 1, train: 51144 (local: 51144), val: 7944 (local: 7685), test: 18568 (local: 17829)
#labels: 41
#labels: 41
#labels: 41
Traceback (most recent call last):
  File "dgl_code/train_dist.py", line 329, in <module>
    main(args)
  File "dgl_code/train_dist.py", line 295, in main
    run(args, device, data)
  File "dgl_code/train_dist.py", line 177, in run
    model = th.nn.parallel.DistributedDataParallel(model)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 335, in __init__
    self._ddp_init_helper()
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 446, in _ddp_init_helper
    self.bucket_bytes_cap)
* RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:84] Timed out waiting 1800000ms for recv operation to complete * 
Traceback (most recent call last):
  File "dgl_code/train_dist.py", line 329, in <module>
    main(args)
  File "dgl_code/train_dist.py", line 295, in main
    run(args, device, data)
  File "dgl_code/train_dist.py", line 226, in run
    loss.backward()
  File "/root/miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:84] Timed out waiting 1800000ms for recv operation to complete
Traceback (most recent call last):
  File "dgl_code/train_dist.py", line 329, in <module>
    main(args)
  File "dgl_code/train_dist.py", line 295, in main
    run(args, device, data)
  File "dgl_code/train_dist.py", line 226, in run
    loss.backward()
  File "/root/miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:136] Timed out waiting 1800000ms for send operation to complete
Using backend: pytorch
/root/miniconda3/lib/python3.7/site-packages/dgl/backend/pytorch/tensor.py:253: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mask = th.tensor(mask, dtype=th.bool)
Namespace(batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='reddit', id=None, ip_config='ip_config.txt', local_rank=None, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=1, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=3, part_config=None, standalone=False)
load reddit
start graph service on server 0 for part 0
Wait connections ...
12 clients connected!
Server (0) shutdown.
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:feat-kvdata- for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:val_mask-kvdata- for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:features-kvdata- for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:labels-kvdata- for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:test_mask-kvdata- for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:train_mask-kvdata- for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:label-kvdata- for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove reddit for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_data for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_indices for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_indptr for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_inner_node for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node__ID for shared memory
Using backend: pytorch
/root/miniconda3/lib/python3.7/site-packages/dgl/backend/pytorch/tensor.py:253: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mask = th.tensor(mask, dtype=th.bool)
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge_inner_edge for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge__ID for shared memory
Namespace(batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='reddit', id=None, ip_config='ip_config.txt', local_rank=None, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=1, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=3, part_config=None, standalone=False)
load reddit
start graph service on server 1 for part 1
Wait connections ...
12 clients connected!
Server (1) shutdown.
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge_edge_map for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_node_map for shared memory
[11:47:05] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_meta for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:feat-kvdata- for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:val_mask-kvdata- for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:features-kvdata- for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:labels-kvdata- for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:test_mask-kvdata- for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:train_mask-kvdata- for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:label-kvdata- for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove reddit for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_data for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_indices for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_indptr for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_inner_node for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node__ID for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge_inner_edge for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge__ID for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge_edge_map for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_node_map for shared memory
[11:45:34] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_meta for shared memory
Using backend: pytorch
/root/miniconda3/lib/python3.7/site-packages/dgl/backend/pytorch/tensor.py:253: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mask = th.tensor(mask, dtype=th.bool)
Namespace(batch_size=1000, batch_size_eval=100000, dataset=None, dropout=0.5, eval_every=5, fan_out='10,25', graph_name='reddit', id=None, ip_config='ip_config.txt', local_rank=None, log_every=20, lr=0.003, n_classes=None, num_clients=None, num_epochs=1, num_gpus=-1, num_hidden=16, num_layers=2, num_servers=1, num_workers=3, part_config=None, standalone=False)
load reddit
start graph service on server 2 for part 2
Wait connections ...
12 clients connected!
Server (2) shutdown.
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:feat-kvdata- for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:val_mask-kvdata- for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:features-kvdata- for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:labels-kvdata- for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:test_mask-kvdata- for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:train_mask-kvdata- for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove node:label-kvdata- for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove reddit for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_data for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_indices for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove redditreddit_0_csc_indptr for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_inner_node for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node__ID for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge_inner_edge for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge__ID for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_edge_edge_map for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_node_map for shared memory
[11:50:19] /opt/dgl/src/runtime/shared_mem.cc:36: remove /reddit_node_meta for shared memory
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Warning!
Interface: vethaafffaa
IP address not available for interface.
Warning!
Interface: veth90e9890
IP address not available for interface.
Machine (0) client (5) connect to server successfuly!
Using backend: pytorch
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Warning!
Interface: vethaafffaa
IP address not available for interface.
Warning!
Interface: veth90e9890
IP address not available for interface.
Machine (0) client (4) connect to server successfuly!
Using backend: pytorch
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Warning!
Interface: vethaafffaa
IP address not available for interface.
Warning!
Interface: veth90e9890
IP address not available for interface.
Machine (0) client (6) connect to server successfuly!
Using backend: pytorch
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Machine (2) client (11) connect to server successfuly!
Using backend: pytorch
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Machine (2) client (8) connect to server successfuly!
Using backend: pytorch
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Machine (2) client (10) connect to server successfuly!
Using backend: pytorch
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Warning!
Interface: veth3c0b61d
IP address not available for interface.
Warning!
Interface: veth6e68154
IP address not available for interface.
Machine (1) client (2) connect to server successfuly!
Using backend: pytorch
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Warning!
Interface: veth3c0b61d
IP address not available for interface.
Warning!
Interface: veth6e68154
IP address not available for interface.
Machine (1) client (3) connect to server successfuly!
Using backend: pytorch
Warning!
Interface: eno1
IP address not available for interface.
Warning!
Interface: eno2
IP address not available for interface.
Warning!
Interface: eno3
IP address not available for interface.
Warning!
Interface: veth3c0b61d
IP address not available for interface.
Warning!
Interface: veth6e68154
IP address not available for interface.
Machine (1) client (1) connect to server successfuly!
Using backend: pytorch
Exception ignored in: <function DistDataLoader.__del__ at 0x7f2d06b1d320>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/dgl/distributed/dist_dataloader.py", line 154, in __del__
    results.append(self.pool.apply_async(cleanup_fn, args=(self.barrier, self.name,)))
  File "/root/miniconda3/lib/python3.7/multiprocessing/pool.py", line 362, in apply_async
    raise ValueError("Pool not running")
ValueError: Pool not running
Exception ignored in: <function DistDataLoader.__del__ at 0x7f4788db2dd0>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/dgl/distributed/dist_dataloader.py", line 154, in __del__
    results.append(self.pool.apply_async(cleanup_fn, args=(self.barrier, self.name,)))
  File "/root/miniconda3/lib/python3.7/multiprocessing/pool.py", line 362, in apply_async
    raise ValueError("Pool not running")
ValueError: Pool not running
Exception ignored in: <function DistDataLoader.__del__ at 0x7fb2ed058d40>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/dgl/distributed/dist_dataloader.py", line 154, in __del__
    results.append(self.pool.apply_async(cleanup_fn, args=(self.barrier, self.name,)))
  File "/root/miniconda3/lib/python3.7/multiprocessing/pool.py", line 362, in apply_async
    raise ValueError("Pool not running")
ValueError: Pool not running
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python3', '-u', 'dgl_code/train_dist.py', '--local_rank=0', '--graph_name', 'reddit', '--ip_config', 'ip_config.txt', '--num_servers', '1', '--num_epochs', '1', '--batch_size', '1000', '--num_workers', '3']' returned non-zero exit status 1.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./launch.py", line 20, in run
    subprocess.check_call(cmd, shell = True)
  File "/root/miniconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no -p 2343 host1 'cd /home/maqy/sage-dist-run/; DGL_DIST_MODE="distributed" DGL_ROLE=client DGL_NUM_SAMPLER=3 DGL_NUM_CLIENT=12 DGL_CONF_PATH=reddit/reddit.json DGL_IP_CONFIG=ip_config.txt DGL_NUM_SERVER=1 python3 -m torch.distributed.launch --nproc_per_node=1 --nnodes=3 --node_rank=1 --master_addr=host0 --master_port=1234 dgl_code/train_dist.py --graph_name reddit --ip_config ip_config.txt --num_servers 1 --num_epochs 1 --batch_size 1000 --num_workers 3'' returned non-zero exit status 1.

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python3', '-u', 'dgl_code/train_dist.py', '--local_rank=0', '--graph_name', 'reddit', '--ip_config', 'ip_config.txt', '--num_servers', '1', '--num_epochs', '1', '--batch_size', '1000', '--num_workers', '3']' returned non-zero exit status 1.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./launch.py", line 20, in run
    subprocess.check_call(cmd, shell = True)
  File "/root/miniconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no -p 2343 host0 'cd /home/maqy/sage-dist-run/; DGL_DIST_MODE="distributed" DGL_ROLE=client DGL_NUM_SAMPLER=3 DGL_NUM_CLIENT=12 DGL_CONF_PATH=reddit/reddit.json DGL_IP_CONFIG=ip_config.txt DGL_NUM_SERVER=1 python3 -m torch.distributed.launch --nproc_per_node=1 --nnodes=3 --node_rank=0 --master_addr=host0 --master_port=1234 dgl_code/train_dist.py --graph_name reddit --ip_config ip_config.txt --num_servers 1 --num_epochs 1 --batch_size 1000 --num_workers 3'' returned non-zero exit status 1.

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python3', '-u', 'dgl_code/train_dist.py', '--local_rank=0', '--graph_name', 'reddit', '--ip_config', 'ip_config.txt', '--num_servers', '1', '--num_epochs', '1', '--batch_size', '1000', '--num_workers', '3']' returned non-zero exit status 1.
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./launch.py", line 20, in run
    subprocess.check_call(cmd, shell = True)
  File "/root/miniconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no -p 2343 host2 'cd /home/maqy/sage-dist-run/; DGL_DIST_MODE="distributed" DGL_ROLE=client DGL_NUM_SAMPLER=3 DGL_NUM_CLIENT=12 DGL_CONF_PATH=reddit/reddit.json DGL_IP_CONFIG=ip_config.txt DGL_NUM_SERVER=1 python3 -m torch.distributed.launch --nproc_per_node=1 --nnodes=3 --node_rank=2 --master_addr=host0 --master_port=1234 dgl_code/train_dist.py --graph_name reddit --ip_config ip_config.txt --num_servers 1 --num_epochs 1 --batch_size 1000 --num_workers 3'' returned non-zero exit status 1.

```

**Comment by maqy1995** [comment]
I found the cause of this problem, the reason is that the PyTorch version of one of the machines is different from the other machines. :pensive:

**Comment by ChandlerBang** [comment]
> Can you try the latest code on master branch? Please let me know if you still see this error.

Hi aksnzhy, I am using the latest code on master branch but I still got the `RANK not set` issue. Do you have any idea on how to solve it?
