### ISSUE TITLE
python3 link_predict.py -d wn18 --gpu 0 yields "ValueError: Feature size must be a multiplier of num_bases (36)"

### ISSUE THREAD

**Issue by hadfield** [dmlc/dgl#2110]
## 🐛 Bug

running link_predict example as:

python3 link_predict.py -d wn18 --gpu 0 

produces an error:

ValueError: Feature size must be a multiplier of num_bases (36)

with full stack trace:

```
python3 link_predict.py -d wn18 --gpu 0 
Using backend: pytorch
Namespace(dataset='wn18', dropout=0.2, edge_sampler='uniform', eval_batch_size=500, eval_protocol='filtered', evaluate_every=500, gpu=0, grad_norm=1.0, graph_batch_size=30000, graph_split_size=0.5, lr=0.01, n_bases=100, n_epochs=6000, n_hidden=500, n_layers=2, negative_sample=10, regularization=0.01)
# entities: 40943
# relations: 18
# training edges: 141442
# validation edges: 5000
# testing edges: 5000
Done loading data from cached files.
/home/marc/anaconda3/envs/pytorch/lib/python3.8/site-packages/dgl-0.6-py3.8-linux-x86_64.egg/dgl/data/utils.py:285: UserWarning: Property dataset.train will be deprecated, please use g.edata['train_mask'] instead.
/home/marc/anaconda3/envs/pytorch/lib/python3.8/site-packages/dgl-0.6-py3.8-linux-x86_64.egg/dgl/data/utils.py:285: UserWarning: Property dataset.test will be deprecated, please use g.edata['test_mask'] instead.
  warnings.warn('Property {} will be deprecated, please use {} instead.'.format(old, new))
Traceback (most recent call last):
  File "link_predict.py", line 259, in <module>
    main(args)
  File "link_predict.py", line 102, in main
    model = LinkPredict(num_nodes,
  File "link_predict.py", line 51, in __init__
    self.rgcn = RGCN(in_dim, h_dim, h_dim, num_rels * 2, num_bases,
  File "/home/marc/dgl/dgl/examples/pytorch/rgcn/model.py", line 20, in __init__
    self.build_model()
  File "/home/marc/dgl/dgl/examples/pytorch/rgcn/model.py", line 30, in build_model
    h2h = self.build_hidden_layer(idx)
  File "link_predict.py", line 43, in build_hidden_layer
    return RelGraphConv(self.h_dim, self.h_dim, self.num_rels, "bdd",
  File "/home/marc/anaconda3/envs/pytorch/lib/python3.8/site-packages/dgl-0.6-py3.8-linux-x86_64.egg/dgl/nn/pytorch/conv/relgraphconv.py", line 154, in __init__
    raise ValueError(
ValueError: Feature size must be a multiplier of num_bases (36).
```

This is using the current (yesterday) master branch, compiled and installed locally against cuda10.2.

Other examples in the same directory work fine, such as:
python3 entity_classify.py -d aifb --testing --gpu 0

**Comment by classicsong** [comment]
The relation regularizer for link_predict.py is bdd. According to the paper, feature size must be a multiplier of number of bases (For wn18, it is same as number of relations 36)

**Comment by hadfield** [comment]
so how to run this case from the command line?

**Comment by classicsong** [comment]
Try --n-bases 18

**Comment by hadfield** [comment]
that yields error:
ValueError: Feature size must be a multiplier of num_bases (18).

**Comment by classicsong** [comment]
You can try
`
python3 link_predict.py -d wn18 --gpu 0 --n-bases 10 --n-hidden 100
`

**Comment by hadfield** [comment]
thanks!  that ran with results:

MRR (filtered): 0.611146
Hits (filtered) @ 1: 0.464800
Hits (filtered) @ 3: 0.715500
Hits (filtered) @ 10: 0.884400
