### ISSUE TITLE
backend error when import dgl in python scripts

### ISSUE THREAD

**Issue by unbreakablegao** [dmlc/dgl#2129]
Hi,

When I ran "import dgl" in a python script, I got the following error:

Backend choice (pytorch, mxnet or tensorflow): DGL does not detect a valid backend option. Which backend would you like to work with?
Traceback (most recent call last):
  File "02_05_XXXXX.py", line 13, in <module>
    import dgl
  File "/opt/conda/lib/python3.6/site-packages/dgl/__init__.py", line 8, in <module>
    from .backend import load_backend, backend_name
  File "/opt/conda/lib/python3.6/site-packages/dgl/backend/__init__.py", line 74, in <module>
    load_backend(get_preferred_backend())
  File "/opt/conda/lib/python3.6/site-packages/dgl/backend/__init__.py", line 69, in get_preferred_backend
    backend_name = input("Backend choice (pytorch, mxnet or tensorflow): ").lower()
EOFError: EOF when reading a line

I am wondering how I set the backend in advance. Could you please give an example?
Thank you very much for your help!

**Comment by unbreakablegao** [comment]
just solved this problem by setting the following

import os
os.environ['DGLBACKEND'] = "pytorch"
