### ISSUE TITLE
'AssertionError: Graph must be on CPU' when trying to sample/collate (TensorFlow backend)

### ISSUE THREAD

**Issue by cwfparsonson** [dmlc/dgl#2140]
## 🐛 Bug

Using the solution from issue #2130, I have been able to do minibatch training & neighbourhood sampling with TensorFlow backend. However, I am now trying to run my script on a server which has GPUs, and I get the following error:

```python
sampler = dgl.dataloading.MultiLayerNeighborSampler(fanouts=fanouts, replace=False)
collator = dgl.dataloading.NodeCollator(g, train_nids, sampler)
                        
# train with sampling and minibatching
for batch_nodes in train_mini_batches:
    with tf.GradientTape() as tape:
        input_nodes, output_nodes, blocks = collator.collate(batch_nodes)
```
Output:
```
Traceback (most recent call last):
  File "hparam_tuner.py", line 83, in <module>
    tboard.run(logs_dir + run_name, model, hparams, data_dict, num_repeats=num_repeats)
  File "/home/zciccwf/phd_project/projects/gnn/gnn/testing/tensorboard_writer.py", line 307, in run
    accuracy, uncertainty = self._train_test_model(run_dir, 
  File "/home/zciccwf/phd_project/projects/gnn/gnn/testing/tensorboard_writer.py", line 241, in _train_test_model
    input_nodes, output_nodes, blocks = collator.collate(batch_nodes)
  File "/home/zciccwf/.conda/envs/deep_scheduler/lib/python3.8/site-packages/dgl/dataloading/dataloader.py", line 355, in collate
    blocks = self.block_sampler.sample_blocks(self.g, items)
  File "/home/zciccwf/.conda/envs/deep_scheduler/lib/python3.8/site-packages/dgl/dataloading/dataloader.py", line 215, in sample_blocks
    frontier = self.sample_frontier(block_id, g, seed_nodes)
  File "/home/zciccwf/.conda/envs/deep_scheduler/lib/python3.8/site-packages/dgl/dataloading/neighbor.py", line 73, in sample_frontier
    frontier = sampling.sample_neighbors(g, seed_nodes, fanout, replace=self.replace)
  File "/home/zciccwf/.conda/envs/deep_scheduler/lib/python3.8/site-packages/dgl/sampling/neighbor.py", line 122, in sample_neighbors
    assert g.device == F.cpu(), "Graph must be on CPU."
AssertionError: Graph must be on CPU.
```

The only way I can fix this is if I run my entire script on a CPU
```python
with tf.device('/cpu:0'):
   run_script()
```

I've tried running specific parts of my code on a CPU to figure out which part requires to be ran on a CPU but I can't seem to find it. Does the sample/collate implementation above support being ran on a GPU?

**Comment by VoVAllen** [comment]
Would you mind share the script with us? Ideally if you want to do sampling, the original graph should be on cpu and the computation on the sampled graph should be on gpu. Therefore you could try adding `with tf.device("gpu:0")` around the real model part.

**Comment by cwfparsonson** [comment]
Hi,

Thanks for getting back to me.

Here is the underlying script:

```python
import tensorflow as tf
import dgl
import math
from gnn.models.graph_conv import evaluate
from tensorboard.plugins.hparams import api as hp
import numpy as np
import os
import shutil
import copy

class TensorboardWriter:
    def __init__(self, logs_dir, hparams, overwrite=False):
        self.logs_dir = logs_dir
        self.overwrite = overwrite
        self.hparams = hparams

        self.METRIC_TEST_ACCURACY = 'test_accuracy'
        self.METRIC_TEST_ACCURACY_UNCERTAINTY = 'test_accuracy_uncertainty'
        self.METRIC_TRAINING_LOSS = 'training_loss'
        self.METRIC_VALIDATION_ACCURACY = 'validation_accuracy'

        self._init_dir()

    def _init_dir(self):
        try:
            os.mkdir(self.logs_dir)
        except FileNotFoundError:
            print('Unable to create save_weight directory. Ensure that all but the last directory in the path already exist.')
            raise
        except FileExistsError:
            print('Directory already exists.')
            if self.overwrite:
                print('Overwriting directory.')
                shutil.rmtree(self.logs_dir[:-1])
                os.mkdir(self.logs_dir)
            else:
                print('Change to an empty dir or set overwrite == True.')
                raise

        with tf.summary.create_file_writer(self.logs_dir).as_default():
            hp.hparams_config(hparams=self.hparams,
                              metrics=[hp.Metric(self.METRIC_TEST_ACCURACY, display_name='Test Accuracy'),
                                       hp.Metric(self.METRIC_TEST_ACCURACY_UNCERTAINTY, display_name='Test Accuracy Uncertainty'),
                                       hp.Metric(self.METRIC_TRAINING_LOSS, display_name='Training Loss'),
                                       hp.Metric(self.METRIC_VALIDATION_ACCURACY, display_name='Validation Accuracy')])


    def _train_test_model(self,
                          run_dir,
                          Model,
                          udf_hparams,
                          g,
                          features,
                          labels,
                          train_mask,
                          val_mask,
                          test_mask,
                          num_repeats=0):
        '''Runs a training loop given user-defined hyperparameters & performs test.
        Possible user defined hparam keys:
            - HP_NUM_UNITS (name='num_units') N.B. last layer will always have num_units==num_classes
            - HP_NUM_LAYERS (name='num_layers') # also translates to number of hops to do away from node when sampling neighbours
            - HP_OPTIMIZER (name='optimizer')
            - HP_LEARNING_RATE (name='learning_rate')
            - HP_NUM_EPOCHS (name='num_epochs')
            - HP_SHUFFLE (name='shuffle') # bool (whether or not to shuffle data)
            - HP_BATCH_NORM (name='batch_norm') # bool (whether or not to use batch normalisation)
            - HP_DROPOUT_RATE (name='dropout_rate') # dropout rate to apply to each layer during training (wont apply to last layer) (set as 0 to avoid dropout)
            - HP_SAMPLE (name='sample') # bool (whether or not to sample)
            - HP_BATCH_SIZE (name='batch_size') # must have HP_SAMPLE==True to take effect
            - HP_NUM_NEIGHBOURS (name='num_neighbours') # no. neighbours to sample for each gnn layer https://docs.dgl.ai/en/0.5.x/api/python/dgl.dataloading.html#neighbor-sampler # must have HP_SAMPLE==True to take effect
        '''
        # define default hyperparameters
        HP_NUM_UNITS = hp.HParam('num_units', hp.Discrete([64])) # units per layer
        HP_NUM_LAYERS = hp.HParam('num_layers', hp.Discrete([1])) # num layers (+=1 since always have output layer)
        HP_OPTIMIZER = hp.HParam('optimizer', hp.Discrete(['adam']))
        HP_LEARNING_RATE = hp.HParam('learning_rate', hp.Discrete([0.0001]))
        HP_NUM_EPOCHS = hp.HParam('num_epochs', hp.Discrete([600]))
        HP_SHUFFLE = hp.HParam('shuffle', hp.Discrete([True]))
        HP_BATCH_NORM = hp.HParam('batch_norm', hp.Discrete([False])) 
        HP_DROPOUT_RATE = hp.HParam('dropout_rate', hp.Discrete([0])) # set to 0 to disable dropout
        HP_SAMPLE = hp.HParam('sample', hp.Discrete([True]))
        HP_BATCH_SIZE = hp.HParam('batch_size', hp.Discrete([35])) 
        HP_NUM_NEIGHBOURS = hp.HParam('num_neighbours', hp.Discrete([4])) # default to 0, which samples all neighbours for each hop/layer
        HP_NUM_HEADS = hp.HParam('num_heads', hp.Discrete([2]))
        default_hparams = {HP_NUM_UNITS: HP_NUM_UNITS.domain.values[0],
                           HP_NUM_LAYERS: HP_NUM_LAYERS.domain.values[0],        
                           HP_OPTIMIZER: HP_OPTIMIZER.domain.values[0],
                           HP_LEARNING_RATE: HP_LEARNING_RATE.domain.values[0],
                           HP_NUM_EPOCHS: HP_NUM_EPOCHS.domain.values[0],
                           HP_SHUFFLE: HP_SHUFFLE.domain.values[0],
                           HP_BATCH_NORM: HP_BATCH_NORM.domain.values[0], 
                           HP_DROPOUT_RATE: HP_DROPOUT_RATE.domain.values[0], 
                           HP_SAMPLE: HP_SAMPLE.domain.values[0],
                           HP_BATCH_SIZE: HP_BATCH_SIZE.domain.values[0],
                           HP_NUM_NEIGHBOURS: HP_NUM_NEIGHBOURS.domain.values[0],
                           HP_NUM_HEADS: HP_NUM_HEADS.domain.values[0],}

        # enter user defined hparams
        hparams = {}
        for key in default_hparams:
            if key.name not in [k.name for k in udf_hparams]:
                hparams[key] = default_hparams[key]
            else:
                udf_param = [udf_hparams[k] for k in udf_hparams if k.name == key.name]
                hparams[key] = udf_param[0]

        # check all user defined params were entered
        for key in udf_hparams:
            if key.name not in [k.name for k in hparams]:
                raise Exception('hparam key {} name is invalid. Accepted hparam key names:\n{}'.format(key, [k.name for k in default_hparams]))


        # reconfigure hyperparameters for this run
        for key in hparams:
            if key.name == 'num_units':
                HP_NUM_UNITS = key
            elif key.name == 'num_layers':
                HP_NUM_LAYERS = key
            elif key.name == 'optimizer':
                HP_OPTIMIZER = key
            elif key.name == 'learning_rate':
                HP_LEARNING_RATE = key
            elif key.name == 'num_epochs':
                HP_NUM_EPOCHS = key
            elif key.name == 'shuffle':
                HP_SHUFFLE = key
            elif key.name == 'batch_norm':
                HP_BATCH_NORM = key
            elif key.name == 'dropout_rate':
                HP_DROPOUT_RATE = key
            elif key.name == 'sample':
                HP_SAMPLE = key
            elif key.name == 'batch_size':
                HP_BATCH_SIZE = key
            elif key.name == 'num_neighbours':
                HP_NUM_NEIGHBOURS = key
            elif key.name == 'num_heads':
                HP_NUM_HEADS = key
            else:
                raise Exception('Unrecognised hyperparameter defined in hparams.')

        if hparams[HP_DROPOUT_RATE] == 0 or hparams[HP_DROPOUT_RATE] == 0.0:
            # relable for model compatability
            hparams[HP_DROPOUT_RATE] = None
        if hparams[HP_SAMPLE]:
            mode = 'sampling'
        else:
            mode = 'no_sampling'

        # one-hot encode labels
        unique_labels = np.unique(labels)
        num_classes = len(unique_labels)
        onehot_labels = tf.one_hot(indices=labels, depth=num_classes)
        unique_onehot_labels = np.unique(onehot_labels, axis=0)
        label_to_onehot = {label: onehot for label, onehot in zip(unique_labels, unique_onehot_labels)}
        labels = tf.cast([label_to_onehot[l] for l in labels.numpy()], dtype=tf.int64) # convert to onehot

        # define gnn layers (automatically add defaults to final output layers)
        # layers_config = {'out_feats': [hparams[HP_NUM_UNITS] for _ in range(hparams[HP_NUM_LAYERS])] + [num_classes],
                         # 'activations': ['relu' for _ in range(hparams[HP_NUM_LAYERS])] + [None],
                         # 'batch_norms': [hparams[HP_BATCH_NORM] for _ in range(hparams[HP_NUM_LAYERS]+1)],
                         # 'dropout_rates': [hparams[HP_DROPOUT_RATE] for _ in range(hparams[HP_NUM_LAYERS])] + [None]}
        layers_config = {'out_feats': [hparams[HP_NUM_UNITS] for _ in range(hparams[HP_NUM_LAYERS])] + [num_classes],
                         'num_heads': [hparams[HP_NUM_HEADS] for _ in range(hparams[HP_NUM_LAYERS])] + [1]}

        # add edges between each node and itself to preserve old node representations
        g.add_edges(g.nodes(), g.nodes())

        # define optimiser
        if hparams[HP_OPTIMIZER] == 'adam':
            opt = tf.keras.optimizers.Adam(learning_rate=hparams[HP_LEARNING_RATE])
        else:
            opt = tf.keras.optimizers.SGD(learning_rate=hparams[HP_LEARNING_RATE])


        # init run trackers
        all_test_accuracy = []
        all_training_loss = {epoch: [] for epoch in range(hparams[HP_NUM_EPOCHS])}
        all_validation_accuracy = {epoch: [] for epoch in range(hparams[HP_NUM_EPOCHS])}

        # get node ids
        node_ids = g.nodes()
        index = 0
        train_nids, val_nids = [], []
        for tm, vm in zip(train_mask, val_mask):
            if tm and vm:
                raise Exception('Sample registered as both train and validation sample, should only be one.')
            elif tm:
                train_nids.append(node_ids[index])
            elif vm:
                val_nids.append(node_ids[index])
            else:
                # is test mask
                pass
            index += 1

        if hparams[HP_SHUFFLE]:
            orig_train_nids = copy.deepcopy(train_mask)

        # repeat training loops to get uncertainty
        with tf.device('/gpu:0'):
            for _ in range(num_repeats+1):
                # init model
                model = Model(layers_config=layers_config)

                # begin training loop
                for epoch in range(hparams[HP_NUM_EPOCHS]):
                    epoch_loss = []

                    # shuffle
                    if hparams[HP_SHUFFLE]:
                        train_nids = tf.random.shuffle(train_nids)
                    else:
                        pass

                    # train for this epoch
                    if mode == 'sampling':
                        # sample minibatches
                        if hparams[HP_NUM_NEIGHBOURS] != 0:
                            fanouts = [hparams[HP_NUM_NEIGHBOURS] for _ in range(model.num_layers)] # sampling fixed num neighbour nodes each layer
                        else:
                            fanouts = [None for _ in range(model.num_layers)] # sample all neighbours
                        num_batches = math.ceil(int(len(train_nids)/hparams[HP_BATCH_SIZE]))
                        train_mini_batches = []
                        prev_index = 0
                        index = copy.deepcopy(hparams[HP_BATCH_SIZE])
                        for batch_num in range(num_batches):
                            train_mini_batches.append(train_nids[prev_index:index])
                            prev_index = copy.deepcopy(index)
                            index += hparams[HP_BATCH_SIZE]

                        sampler = dgl.dataloading.MultiLayerNeighborSampler(fanouts=fanouts, replace=False)
                        collator = dgl.dataloading.NodeCollator(g, train_nids, sampler)
                        
                        # train with sampling and minibatching
                        for batch_nodes in train_mini_batches:
                            with tf.GradientTape() as tape:
                                input_nodes, output_nodes, blocks = collator.collate(batch_nodes)
                                input_features = blocks[0].srcdata['feat']
                                output_labels = blocks[-1].dstdata['label']
                                onehot_output_labels = tf.cast([label_to_onehot[l] for l in output_labels.numpy()],dtype=tf.int64)
                                logits = model(blocks, input_features, training=True, mode=mode)
                                loss = tf.nn.softmax_cross_entropy_with_logits(labels=onehot_output_labels, logits=logits)
                                epoch_loss.append(tf.math.reduce_mean(loss))
                                grads = tape.gradient(loss, model.trainable_variables)
                                opt.apply_gradients(zip(grads, model.trainable_variables))
                    else:
                        # train without sampling or minibatching
                        with tf.GradientTape() as tape:
                            logits = model(g, features, training=True, mode=mode)
                            output_logits = tf.gather(logits, train_nids)
                            output_labels = tf.gather(labels, train_nids)
                            loss = tf.nn.softmax_cross_entropy_with_logits(labels=output_labels,logits=output_logits)
                            epoch_loss.append(tf.math.reduce_mean(loss))
                            grads = tape.gradient(loss, model.trainable_variables)
                            opt.apply_gradients(zip(grads, model.trainable_variables))

                    # validation testing
                    epoch_acc = evaluate(model, g, features, labels, val_nids)

                    # summarise epoch
                    epoch_loss = np.mean(np.array(epoch_loss))
                    all_training_loss[epoch].append(epoch_loss)
                    all_validation_accuracy[epoch].append(tf.math.reduce_mean(epoch_acc))

                # test fully trained model
                acc = evaluate(model, g, features, labels, test_mask)
                all_test_accuracy.append(acc)

            # summarise run
            # training loss and validation
            for epoch in range(hparams[HP_NUM_EPOCHS]):
                loss = np.mean(np.array(all_training_loss[epoch]))
                acc = np.mean(np.array(all_validation_accuracy[epoch]))
                with tf.summary.create_file_writer(run_dir).as_default():
                    tf.summary.scalar(self.METRIC_TRAINING_LOSS, data=loss, step=epoch)
                    tf.summary.scalar(self.METRIC_VALIDATION_ACCURACY, data=acc, step=epoch)
            # test
            mean_accuracy = np.mean(np.array(all_test_accuracy))
            if num_repeats > 1:
                uncertainty = (np.max(np.array(all_test_accuracy)) - np.min(np.array(all_test_accuracy))) / 2
            else:
                uncertainty = 0

            return mean_accuracy, uncertainty 


    def run(self, run_dir, Model, hparams, data_dict, num_repeats=1):
        '''Trains and tests model with given hparams and tracks with tensorboard.
        Args:
            run_dir (str): Directory to where to save logs + name of this run.
            Model (obj): GNN model to train and test.
            hparams (dict): User-defined hyperparameters to use.
            data_dict (dict): Data for training, validation, and testing.
            num_repeats (int): Number of times to repeat training and testing
                (will return the average accuracy and the uncertainty in the
                accuracy value).
        '''
        with tf.device('/cpu:0'):
            data_dict = copy.deepcopy(data_dict) # ensure no overwriting of original data
        with tf.summary.create_file_writer(run_dir).as_default():
            hp.hparams(hparams) # record hparams used in this run
            accuracy, uncertainty = self._train_test_model(run_dir, 
                                                           Model,
                                                           hparams, 
                                                           g=data_dict['graph'],
                                                           features=data_dict['features'],
                                                           labels=data_dict['labels'],
                                                           train_mask=data_dict['train_mask'],
                                                           val_mask=data_dict['val_mask'],
                                                           test_mask=data_dict['test_mask'],
                                                           num_repeats=num_repeats)

        with tf.summary.create_file_writer(run_dir).as_default():
            tf.summary.scalar(self.METRIC_TEST_ACCURACY, data=accuracy, step=1)
            tf.summary.scalar(self.METRIC_TEST_ACCURACY_UNCERTAINTY, data=uncertainty, step=1)
```

And here is how it is called:
```python
if __name__ == '__main__':
    import tensorflow as tf
    from tensorboard.plugins.hparams import api as hp
    from gnn.models.tools import load_data
    from gnn.models.models import GCN, GAT
    from gnn.testing.tensorboard_writer import TensorboardWriter
    import time

    # config
    dataset = 'cora'
    logs_dir = '../../data/logs/hparam_tuning/'
    # model = GCN
    model = GAT
    num_repeats = 3 # num times to repeat each trial to get uncertainty value

    # load dataset
    with tf.device('/cpu:0'):
        g, features, labels, train_mask, val_mask, test_mask = load_data(dataset)
        data_dict = {'graph': g,
                     'features': features,
                     'labels': labels,
                     'train_mask': train_mask,
                     'val_mask': val_mask,
                     'test_mask': test_mask}

    # set hyperparams to trial
    HP_NUM_UNITS = hp.HParam('num_units', hp.Discrete([64, 128])) # 64
    HP_OPTIMIZER = hp.HParam('optimizer', hp.Discrete(['adam'])) # adam
    HP_LEARNING_RATE = hp.HParam('learning_rate', hp.Discrete([0.0001])) # 0.0001
    HP_NUM_EPOCHS = hp.HParam('num_epochs', hp.Discrete([300, 400])) # 200
    HP_SHUFFLE = hp.HParam('shuffle', hp.Discrete([True])) 
    HP_BATCH_NORM = hp.HParam('batch_norm', hp.Discrete([False]))
    HP_DROPOUT_RATE = hp.HParam('dropout_rate', hp.Discrete([0])) 
    HP_SAMPLE = hp.HParam('sample', hp.Discrete([True])) # True
    HP_BATCH_SIZE = hp.HParam('batch_size', hp.Discrete([35])) 
    HP_NUM_NEIGHBOURS = hp.HParam('num_neighbours', hp.Discrete([4])) 
    HP_NUM_HEADS = hp.HParam('num_heads', hp.Discrete([3, 4, 5, 8]))
    hparams = [HP_NUM_UNITS, 
               HP_OPTIMIZER, 
               HP_LEARNING_RATE, 
               HP_NUM_EPOCHS, 
               HP_SHUFFLE,
               HP_BATCH_NORM,
               HP_DROPOUT_RATE,
               HP_SAMPLE,
               HP_BATCH_SIZE,
               HP_NUM_NEIGHBOURS,
               HP_NUM_HEADS]
    num_runs = 1
    for param in hparams:
        num_runs *= len(param.domain.values)

    # init tensorboard
    tboard = TensorboardWriter(logs_dir, hparams, overwrite=True)

    # trial each combination of hyperparams
    session_num = 1
    started = time.time()
    for num_units in HP_NUM_UNITS.domain.values:
        for optimizer in HP_OPTIMIZER.domain.values:
            for learning_rate in HP_LEARNING_RATE.domain.values:
                for num_epochs in HP_NUM_EPOCHS.domain.values:
                    for shuffle in HP_SHUFFLE.domain.values:
                        for batch_norm in HP_BATCH_NORM.domain.values:
                            for dropout_rate in HP_DROPOUT_RATE.domain.values:
                                for sample in HP_SAMPLE.domain.values:
                                    for batch_size in HP_BATCH_SIZE.domain.values:
                                        for num_neighbours in HP_NUM_NEIGHBOURS.domain.values:
                                            for num_heads in HP_NUM_HEADS.domain.values:
                                                hparams = {HP_NUM_UNITS: num_units,
                                                           HP_OPTIMIZER: optimizer,
                                                           HP_LEARNING_RATE: learning_rate,
                                                           HP_NUM_EPOCHS: num_epochs,
                                                           HP_SHUFFLE: shuffle,
                                                           HP_BATCH_NORM: batch_norm,
                                                           HP_DROPOUT_RATE: dropout_rate,
                                                           HP_SAMPLE: sample,
                                                           HP_BATCH_SIZE: batch_size,
                                                           HP_NUM_NEIGHBOURS: num_neighbours,
                                                           HP_NUM_HEADS: num_heads,}
                                                run_name = 'run_'+str(session_num)
                                                print('Starting trial {} of {} ({} repeats)'.format(run_name, num_runs, num_repeats))
                                                start = time.time()
                                                print({h.name: hparams[h] for h in hparams})
                                                tboard.run(logs_dir + run_name, model, hparams, data_dict, num_repeats=num_repeats)
                                                end = time.time()
                                                print('Finished trial in {} s'.format(end-start))
                                                session_num += 1
    ended = time.time()
    print('Finished hparam trials in {} s'.format(ended-started))
```

As above, I have tried adding a with tf.device('/cpu:0') where the original graph is defined and then, just before the training loop, a with tf.device('/gpu:0'), however this results in the same AssertionError as before.

**Comment by cwfparsonson** [comment]
Just to add, I tried putting everything on the CPU (graphs etc) using with tf.device('/cpu:0') and then only running the actual training loop on the GPU:

```python
# train with sampling and minibatching
for batch_nodes in train_mini_batches:
    with tf.GradientTape() as tape:
        input_nodes, output_nodes, blocks = collator.collate(batch_nodes)
            with tf.device('/gpu:0'):
                input_features = blocks[0].srcdata['feat']
                output_labels = blocks[-1].dstdata['label']
                onehot_output_labels = tf.cast([label_to_onehot[l] for l in output_labels.numpy()],dtype=tf.int64)
                logits = model(blocks, input_features, training=True, mode=mode)
                loss = tf.nn.softmax_cross_entropy_with_logits(labels=onehot_output_labels, logits=logits)
                epoch_loss.append(tf.math.reduce_mean(loss))
                grads = tape.gradient(loss, model.trainable_variables)
                opt.apply_gradients(zip(grads, model.trainable_variables))
```
Output:
```
Traceback (most recent call last):
  File "hparam_tuner.py", line 84, in <module>
    tboard.run(logs_dir + run_name, model, hparams, data_dict, num_repeats=num_repeats)
  File "/home/zciccwf/phd_project/projects/gnn/gnn/testing/tensorboard_writer.py", line 309, in run
    accuracy, uncertainty = self._train_test_model(run_dir, 
  File "/home/zciccwf/phd_project/projects/gnn/gnn/testing/tensorboard_writer.py", line 247, in _train_test_model
    logits = model(blocks, input_features, training=True, mode=mode)
  File "/home/zciccwf/.conda/envs/deep_scheduler/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/zciccwf/phd_project/projects/gnn/gnn/models/gat_conv.py", line 121, in call
    h = layer(next(blocks), h, training=training, mode=mode)
  File "/home/zciccwf/.conda/envs/deep_scheduler/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/zciccwf/phd_project/projects/gnn/gnn/models/gat_conv.py", line 79, in call
    head_outs = [attention_head(g, features, training=training, mode=mode) for attention_head in self.heads]
  File "/home/zciccwf/phd_project/projects/gnn/gnn/models/gat_conv.py", line 79, in <listcomp>
    head_outs = [attention_head(g, features, training=training, mode=mode) for attention_head in self.heads]
  File "/home/zciccwf/.conda/envs/deep_scheduler/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/home/zciccwf/phd_project/projects/gnn/gnn/models/gat_conv.py", line 58, in call
    block.srcdata['z'] = z_src
  File "/home/zciccwf/.conda/envs/deep_scheduler/lib/python3.8/site-packages/dgl/view.py", line 81, in __setitem__
    self._graph._set_n_repr(self._ntid, self._nodes, {key : val})
  File "/home/zciccwf/.conda/envs/deep_scheduler/lib/python3.8/site-packages/dgl/heterograph.py", line 3754, in _set_n_repr
    raise DGLError('Cannot assign node feature "{}" on device {} to a graph on'
dgl._ffi.base.DGLError: Cannot assign node feature "z" on device /gpu:0 to a graph on device /cpu:0. Call DGLGraph.to() to copy the graph to the same device.
```

The problem seems to be coming from the sampler which I cannot define on the GPU, which causes an error when trying to train the model on a GPU

**Comment by VoVAllen** [comment]
Hi,

Seems you are very close the make it runnable. Could you try add `blocks = [block.to("gpu:0") for block in blocks]` before `logits = model(blocks, input_features, training=True, mode=mode)`?

**Comment by cwfparsonson** [comment]
Hi,

Thanks, that seems to work!

This is probably not for you guys to know/answer, but using a GPU as described above (putting the parts after `with tf.GradientTape() as tape` inside a `with tf.device('/gpu:0')`, as above) actually results in a slower overall training time (183 seconds as opposed to 139 seconds when everything is done on a CPU). Do you know why this might be? Is it possible I need to put other parts of my script (other than just what's inside `with tf.GradientTape() as tape`) on a GPU? Currently everything else is on a CPU..
