### ISSUE TITLE
Error when convert g.edge_subgraph() in networkx to DGLGraph

### ISSUE THREAD

**Issue by hningbo** [dmlc/dgl#2164]
## To Reproduce

1. create a graph in networkx

```
    g = nx.Graph()
    g.add_edge(1,2)
    g.add_edge(0,2)
```

2. get a subgraph from edge 

```
    sg = g.edge_subgraph([(1,2)])
```

3. convert subgraph to DGLGraph instance

```
    g = DGLGraph(sg)
```

where the error traceback is 

```
Traceback (most recent call last):
  File "D:\miniconda3\lib\site-packages\dgl\graph_index.py", line 1277, in create_graph_index
    gidx = from_networkx(graph_data, readonly)
  File "D:\miniconda3\lib\site-packages\dgl\graph_index.py", line 1116, in from_networkx
    return from_coo(num_nodes, src, dst, readonly)
  File "D:\miniconda3\lib\site-packages\dgl\graph_index.py", line 1017, in from_coo
    gidx.add_edges(src, dst)
  File "D:\miniconda3\lib\site-packages\dgl\graph_index.py", line 100, in add_edges
    _CAPI_DGLGraphAddEdges(self, u_array, v_array)
  File "D:\miniconda3\lib\site-packages\dgl\_ffi\_ctypes\function.py", line 188, in __call__
    check_call(_LIB.DGLFuncCall(
  File "D:\miniconda3\lib\site-packages\dgl\_ffi\base.py", line 62, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: [14:48:54] C:\Users\Administrator\dgl\src\graph\graph.cc:79: Check failed: HasVertex(src) && HasVertex(dst): Invalid vertices: src=1 dst=2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\path\to\workspace\my_code.py", line 105, in <module>
    g = DGLGraph(sg)
  File "D:\miniconda3\lib\site-packages\dgl\graph.py", line 996, in __init__
    gidx = graph_index.create_graph_index(graph_data, readonly)
  File "D:\miniconda3\lib\site-packages\dgl\graph_index.py", line 1279, in create_graph_index
    raise DGLError('Error while creating graph from input of type "%s".'
dgl._ffi.base.DGLError: Error while creating graph from input of type "<class 'networkx.classes.graph.Graph'>".

Process finished with exit code 1

```

## Expected behavior

Convert the g.edge_subgraph() in networkx to DGLGraph()

## Environment

 - DGL Version : 0.4.3
 - Backend Library & Version : Pytorch 1.6.0
 - OS (e.g., Linux): Windows
 - How you installed DGL : pip
 - Python version: 3.8.1
 - CUDA/cuDNN version : 10.2
 - GPU models and configuration : GTX 1060Ti
 - Any other relevant information: networkx version 2.5

**Comment by mufeili** [comment]
Can you try updating to DGL 0.5 and use `g = dgl.from_networkx(sg)` to load a NetworkX graph?

**Comment by jermainewang** [comment]
Closed due to lack of activity.
