### ISSUE TITLE
An error occurred while importing dgl

### ISSUE THREAD

**Issue by lt610** [dmlc/dgl#2221]
## To Reproduce

1.import dgl

>>> import dgl
Using backend: pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liutang/miniconda3/envs/3.6.7/lib/python3.6/site-packages/dgl/__in                                                                                                      it__.py", line 14, in <module>
    from .backend import load_backend, backend_name
  File "/home/liutang/miniconda3/envs/3.6.7/lib/python3.6/site-packages/dgl/back                                                                                                      end/__init__.py", line 73, in <module>
    load_backend(get_preferred_backend())
  File "/home/liutang/miniconda3/envs/3.6.7/lib/python3.6/site-packages/dgl/back                                                                                                      end/__init__.py", line 23, in load_backend
    mod = importlib.import_module('.%s' % mod_name, __name__)
  File "/home/liutang/miniconda3/envs/3.6.7/lib/python3.6/importlib/__init__.py"                                                                                                      , line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/liutang/miniconda3/envs/3.6.7/lib/python3.6/site-packages/dgl/back                                                                                                      end/pytorch/__init__.py", line 1, in <module>
    from .tensor import *
  File "/home/liutang/miniconda3/envs/3.6.7/lib/python3.6/site-packages/dgl/back                                                                                                      end/pytorch/tensor.py", line 11, in <module>
    from ... import ndarray as nd
  File "/home/liutang/miniconda3/envs/3.6.7/lib/python3.6/site-packages/dgl/ndar                                                                                                      ray.py", line 14, in <module>
    from ._ffi.object import register_object, ObjectBase
  File "/home/liutang/miniconda3/envs/3.6.7/lib/python3.6/site-packages/dgl/_ffi                                                                                                      /object.py", line 8, in <module>
    from .object_generic import ObjectGeneric, convert_to_object
  File "/home/liutang/miniconda3/envs/3.6.7/lib/python3.6/site-packages/dgl/_ffi                                                                                                      /object_generic.py", line 7, in <module>
    from .base import string_types
  File "/home/liutang/miniconda3/envs/3.6.7/lib/python3.6/site-packages/dgl/_ffi                                                                                                      /base.py", line 42, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "/home/liutang/miniconda3/envs/3.6.7/lib/python3.6/site-packages/dgl/_ffi                                                                                                      /base.py", line 34, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/home/liutang/miniconda3/envs/3.6.7/lib/python3.6/ctypes/__init__.py", l                                                                                                      ine 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcublas.so.10: cannot open shared object file: No such file or direct                                                                                                      ory
## Environment

 - DGL Version (e.g., dgl-cu102):
 - Backend Library & Version (e.g., PyTorch 1.6.0):
 - OS (e.g., CentOS):
 - How you installed DGL ( `pip`):
 - Build command you used (if compiling from source):
 - Python version:3.6.7
 - CUDA/cuDNN version (10.2):
 - GPU models and configuration (GeForce RTX 2080 Ti):
 - Any other relevant information:

**Comment by mufeili** [comment]
This seems to be a common issue for cuda and you can find many discussions on the internet, e.g. https://forums.developer.nvidia.com/t/importerror-libcublas-so-10-0-cannot-open-shared-object-file-no-such-file-or-directory/71627/4. You can try some solutions suggested in these discussions.

**Comment by jermainewang** [comment]
Doesn't seem to be DGL-related issue. Close for now.
