### ISSUE TITLE
dgl.distributed.initialize failed when the graph has no node features and edge features

### ISSUE THREAD

**Issue by sentosajie** [dmlc/dgl#2366]
## 🐛 Bug

If the graph has no node features and edge features, **dgl.distributed.initialize** will failed with the RuntimeError: There is no data on kvserver 

## To Reproduce

1. Generate a graph randomly:
```
u0 = np.random.randint(0, 10000, 15000)
v0 = np.random.randint(0, 10000, 15000)
u = np.concatenate([u0, v0])
v = np.concatenate([v0, u0])
pairs = list(zip(u, v))
g = dgl.graph(pairs)
```
2. Partition it as usual
3. In the training script, the initialization will failed:
```
dgl.distributed.initialize(args.ip_config, args.num_servers, args.num_workers)
#output
Traceback (most recent call last):
  File "scripts/train.py", line 225, in <module>
    main(args)
  File "scripts/train.py", line 112, in main
    dgl.distributed.initialize(args.ip_config, args.num_servers, args.num_workers)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/dgl/distributed/dist_context.py", line 101, in initialize
    serv.start()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/dgl/distributed/dist_graph.py", line 297, in start
    num_clients=self.num_clients, server_state=server_state)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/dgl/distributed/rpc_server.py", line 92, in start_server
    res = req.process_request(server_state)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/dgl/distributed/kvstore.py", line 369, in process_request
    raise RuntimeError('There is no data on kvserver.')
RuntimeError: There is no data on kvserver.
```
4. If you add some features to the graph, everything works well
```
g = dgl.graph(pairs)
g.edata['w'] = torch.tensor(np.random.randn(g.num_edges()))
```

## Environment

 - DGL Version 0.5.2
 - CUDA/cuDNN version (if applicable): 10.1

**Comment by aksnzhy** [comment]
thanks for reporting this bug！

**Comment by zheng-da** [comment]
The bug should have been fixed by https://github.com/dmlc/dgl/pull/2838
