### ISSUE TITLE
RuntimeError: number of categories cannot exceed 2^24 - GraphSage Unsupervised

### ISSUE THREAD

**Issue by etorf** [dmlc/dgl#2420]
I am trying to run GraphSage unsupervised implementation from train_sampling_unsupervised.py on my Graph -
80M Nodes with 2B Edges (Big...).
I am getting this error:
`Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train_model.py", line 44, in decorated_function
    raise exception.__class__(trace)
RuntimeError: Traceback (most recent call last):
  File "train_model.py", line 32, in _queue_result
    res = func(*args, **kwargs)
  File "train_model.py", line 206, in run
    for step, (input_nodes, pos_graph, neg_graph, blocks) in enumerate(dataloader):
  File "/opt/conda/lib/python3.6/site-packages/dgl/dataloading/pytorch/__init__.py", line 161, in __next__
    input_nodes, pair_graph, neg_pair_graph, blocks = next(self.iter_)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/opt/conda/lib/python3.6/site-packages/dgl/dataloading/pytorch/__init__.py", line 133, in collate
    input_nodes, pair_graph, neg_pair_graph, blocks = super().collate(items)
  File "/opt/conda/lib/python3.6/site-packages/dgl/dataloading/dataloader.py", line 678, in collate
    return self._collate_with_negative_sampling(items)
  File "/opt/conda/lib/python3.6/site-packages/dgl/dataloading/dataloader.py", line 607, in _collate_with_negative_sampling
    neg_srcdst = self.negative_sampler(self.g, items)
  File "train_model.py", line 60, in __call__
    dst = self.weights.multinomial(n*self.k, replacement=True)
RuntimeError: number of categories cannot exceed 2^24
`

**Comment by classicsong** [comment]
You need to remove .int() in https://github.com/dmlc/dgl/blob/0ceb6751a0c408018459966c8c83ccfc8980e397/examples/pytorch/graphsage/train_sampling_unsupervised.py#L257

**Comment by etorf** [comment]
I don't think it's that. It's coming from the negative sampler which is being called before, and specifically the multinomial selection which apparently is limited...

**Comment by VoVAllen** [comment]
Seems from https://github.com/pytorch/pytorch/issues/2576
Do you have such big weights in your model?

**Comment by BarclayII** [comment]
`torch.multinomial` doesn't support arrays larger than `2^24` (i.e. <17M) elements, either CPU or GPU.

You will either need to use `np.random.choice` if you still want the non-uniform sampling as in the example, or you can simply use uniform sampling (`dgl.dataloading.negative_sampler.Uniform`).
