### ISSUE TITLE
Sparseadam optimizer in Metapath2vec model got an empty parameter list

### ISSUE THREAD

**Issue by zezhishao** [dmlc/dgl#2571]
## 🐛 Bug

https://github.com/dmlc/dgl/blob/a613ad880690a8b155537117ea038a9de14111ed/examples/pytorch/metapath2vec/metapath2vec.py#L39

I'm using `pytorch=1.7.1` and it occurs:
```shell
Traceback (most recent call last):
  File "metapath2vec.py", line 81, in <module>
    m2v.train()
  File "metapath2vec.py", line 39, in train
    optimizer = optim.SparseAdam(self.skip_gram_model.parameters(), lr=self.initial_lr)
  File "/home/S22/anaconda3/envs/stapy/lib/python3.8/site-packages/torch/optim/sparse_adam.py", line 49, in __init__
    super(SparseAdam, self).__init__(params, defaults)
  File "/home/S22/anaconda3/envs/stapy/lib/python3.8/site-packages/torch/optim/optimizer.py", line 47, in __init__
    raise ValueError("optimizer got an empty parameter list")
ValueError: optimizer got an empty parameter list
```

It seems that there is a bug in `Sparseadam` in PyTorch, and it can be temporarily fixed by:
```python
optimizer = optim.SparseAdam(list(self.skip_gram_model.parameters()), lr=self.initial_lr)
```

**Comment by VoVAllen** [comment]
Thanks! Could you make a pull request on this change?
