### ISSUE TITLE
jtnn example vocab error

### ISSUE THREAD

**Issue by nickyoungforu** [dmlc/dgl#2590]
NOCUDA=1 python3 vaetrain_dgl.py
it shows :
Original Traceback (most recent call last):
  File "/Users/cc/opt/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/Users/cc/opt/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/cc/opt/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/cc/Workspace/repos/dgl/examples/pytorch/jtnn/jtnn/datautils.py", line 52, in __getitem__
    wid = _set_node_id(mol_tree, self.vocab)
  File "/Users/cc/Workspace/repos/dgl/examples/pytorch/jtnn/jtnn/datautils.py", line 21, in _set_node_id
    wid.append(vocab.get_index(mol_tree.nodes_dict[node]['smiles']))
  File "/Users/cc/Workspace/repos/dgl/examples/pytorch/jtnn/jtnn/mol_tree.py", line 16, in get_index
    return self.vmap[smiles]
KeyError: 'C1=CN=NC=C1'

env:
dgl 0.5.3
torch 1.7.1
mac os

**Comment by VoVAllen** [comment]
What's your rdkit version?

**Comment by nickyoungforu** [comment]
> What's your rdkit version?

2019.09.3

**Comment by BarclayII** [comment]
> > What's your rdkit version?
> 
> 2019.09.3

Could you try 2018.09.3?  Other versions may have different vocabularies so the code may not work.
