### ISSUE TITLE
[Windows] module libdgl.dll or dependencies not found

### ISSUE THREAD

**Issue by nomisto** [dmlc/dgl#2622]
## 🐛 Bug

FileNotFound error when importing dgl module.

## To Reproduce

1. import dgl
1.
1.

``` bash
`>>> import dgl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ottsi\AppData\Local\Programs\Python\Python39\lib\site-packages\dgl\__init__.py", line 4, in <module>
    from . import nn
  File "C:\Users\ottsi\AppData\Local\Programs\Python\Python39\lib\site-packages\dgl\nn\__init__.py", line 11, in <module>
    from .pytorch import *
  File "C:\Users\ottsi\AppData\Local\Programs\Python\Python39\lib\site-packages\dgl\nn\pytorch\__init__.py", line 1, in <module>
    from .gcn import GraphConvolutionLayer
  File "C:\Users\ottsi\AppData\Local\Programs\Python\Python39\lib\site-packages\dgl\nn\pytorch\gcn.py", line 11, in <module>
    from ...base import ALL, is_all
  File "C:\Users\ottsi\AppData\Local\Programs\Python\Python39\lib\site-packages\dgl\base.py", line 6, in <module>
    from ._ffi.base import DGLError
  File "C:\Users\ottsi\AppData\Local\Programs\Python\Python39\lib\site-packages\dgl\_ffi\base.py", line 43, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "C:\Users\ottsi\AppData\Local\Programs\Python\Python39\lib\site-packages\dgl\_ffi\base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "C:\Users\ottsi\AppData\Local\Programs\Python\Python39\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\ottsi\AppData\Local\Programs\Python\Python39\lib\site-packages\dgl\libdgl.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

## Environment

 - DGL Version (e.g., 1.0): 0.1.3
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): torch 1.7.1+cpu
 - OS (e.g., Linux): Windows 10
 - How you installed DGL (`conda`, `pip`, source): pip install dgl
 - Build command you used (if compiling from source):
 - Python version: 3.9.1
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

## Additional context

libdgl.dll is present at specified location.

**Comment by yzh119** [comment]
The `DGL 0.1.3` is too early, would you mind upgrading to a later version?

**Comment by nomisto** [comment]
Unfortunately for python 3.9 this is the latest version, but downgrading the python version did the trick, thanks.
