### ISSUE TITLE
No module and no attribute error when run COLLAB in GXN model

### ISSUE THREAD

**Issue by sneakerkg** [dmlc/dgl#2624]
## 🐛 Bug

In V0.6 bug bash, we noticed two issues when running COLLAB in GXN model.
1.AttributeError: 'numpy.ndarray' object has no attribute 'device' in dataset = LegacyTuDataset(args.dataset, raw_dir=args.dataset_path);
2.(with early stopping) Run COLLAB successfully. from dataloader import GraphDataLoaderModuleNotFoundError: No module named 'dataloader'

**Comment by sneakerkg** [comment]
Also @lygztq

**Comment by lygztq** [comment]
For 1: Could you list the detailed error message (the trackback and the command) here? @hengruizhang98
For 2: Fix bug in #2629

**Comment by hengruizhang98** [comment]
@lygztq  I didn't face the first bug. Haocheng Xu reported it.

**Comment by mufeili** [comment]
I probably have already fixed the first issue in PR #2592 . Can you ask Haocheng to confirm it?

**Comment by lygztq** [comment]
> I probably have already fixed the first issue in PR #2592 . Can you ask Haocheng to confirm it?

I don't have his github id. But I have sent an email to him.

**Comment by mufeili** [comment]
> > I probably have already fixed the first issue in PR #2592 . Can you ask Haocheng to confirm it?
> 
> I don't have his github id. But I have sent an email to him.

Cool, thx!

**Comment by Smilexuhc** [comment]
Sorry for late reply.
Traceback (most recent call last):
  File "main.py", line 153, in <module>
    acc, train_time = main(args)
  File "main.py", line 90, in main
    dataset = LegacyTUDataset(args.dataset, raw_dir=args.dataset_path)
  File "/home/.pyenv/versions/3.6.6/lib/python3.6/site-packages/dgl/data/tu.py", line 84, in __init__
    force_reload=force_reload, verbose=verbose)
  File "/home/.pyenv/versions/3.6.6/lib/python3.6/site-packages/dgl/data/dgl_dataset.py", line 288, in __init__
    verbose=verbose)
  File "/home/.pyenv/versions/3.6.6/lib/python3.6/site-packages/dgl/data/dgl_dataset.py", line 93, in __init__
    self._load()
  File "/home/.pyenv/versions/3.6.6/lib/python3.6/site-packages/dgl/data/dgl_dataset.py", line 178, in _load
    self.process()
  File "/home/.pyenv/versions/3.6.6/lib/python3.6/site-packages/dgl/data/tu.py", line 142, in process
    g.ndata['feat'] = np.ones((g.number_of_nodes(), self.hidden_size))
  File "/home/.pyenv/versions/3.6.6/lib/python3.6/site-packages/dgl/view.py", line 81, in __setitem__
    self._graph._set_n_repr(self._ntid, self._nodes, {key : val})
  File "/home/.pyenv/versions/3.6.6/lib/python3.6/site-packages/dgl/heterograph.py", line 3970, in _set_n_repr
    if F.context(val) != self.device:
  File "/home/.pyenv/versions/3.6.6/lib/python3.6/site-packages/dgl/backend/pytorch/tensor.py", line 76, in context
    return input.device
AttributeError: 'numpy.ndarray' object has no attribute 'device'

**Comment by lygztq** [comment]
@mufeili I'm not sure it is the same problem as #2592. It looks like a problem in the TUDataset.

**Comment by mufeili** [comment]
> #2592

This is the same issue [here](https://github.com/dmlc/dgl/pull/2592/files#diff-65fb1bb5dc56539c5e370effd2de3754b566a428f5bfddc0659a387aa13759d5R139).

**Comment by lygztq** [comment]
> > #2592
> 
> This is the same issue [here](https://github.com/dmlc/dgl/pull/2592/files#diff-65fb1bb5dc56539c5e370effd2de3754b566a428f5bfddc0659a387aa13759d5R139).

Thx
