### ISSUE TITLE
[Bug] PinSage example crashes on CUDA 11.0 while succeeds on CUDA 10.1

### ISSUE THREAD

**Issue by BarclayII** [dmlc/dgl#2687]
## 🐛 Bug

Following the instructions in PinSage's README.txt fails with the following error with master build on CUDA 11.0.

```
(base) ubuntu@ip-172-31-47-0:/mnt/b/gq/dgl/examples/pytorch/pinsage$ CUDA_LAUNCH_BLOCKING=1 python model.py data.pkl --num-epochs 300 --num-workers 2 --device cuda:0 --hidden-dims 64
Using backend: pytorch
  0%|                                                                                                       | 0/20000 [00:00<?, ?it/s]model.py:101: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
[W python_anomaly_mode.cpp:104] Warning: Error detected in EmbeddingBackward. Traceback of forward call that caused the error:          File "model.py", line 143, in <module>
    train(dataset, args)
  File "model.py", line 102, in train
    loss = model(pos_graph, neg_graph, blocks).mean()
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "model.py", line 24, in forward
    h_item = self.get_repr(blocks)
  File "model.py", line 31, in get_repr
    h_item_dst = self.proj(blocks[-1].dstdata)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/b/gq/dgl/examples/pytorch/pinsage/layers.py", line 106, in forward
    result = module(data, length)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/b/gq/dgl/examples/pytorch/pinsage/layers.py", line 82, in forward
    return self.emb(x).sum(1) / length.unsqueeze(1).float()
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1852, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
 (function _print_stack)
  0%|                                                                                                       | 0/20000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "model.py", line 143, in <module>
    train(dataset, args)
  File "model.py", line 104, in train
    loss.backward()
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: unique_by_key: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```

The code successfully runs with CUDA 10.1.  I also checked the inputs of the embedding layers and they looked correct.

Perhaps some other CUDA calls in DGL failed and later PyTorch CUDA calls inherited the error code?  Could it still be the case if I turned on `CUDA_LAUNCH_BLOCKING`?

**Comment by yzh119** [comment]
Which version of dgl you were using? 0.5.3 or 0.6 .

**Comment by yzh119** [comment]
We switched to ALG2 in spmmcsr call in #2550 , and it might be the reason.
