### ISSUE TITLE
Index out of bound will make Dataloader crash

### ISSUE THREAD

**Issue by Michael1015198808** [dmlc/dgl#2854]
## 🐛 Bug

If the argument `n_id` passed to `dgl.dataloading.pytorch.NodeDataLoader` contains indexes out of bound, the program will crash in C/C++ backend.

## To Reproduce

1. Just run the code below.

### Code

```python3
import dgl
import torch

p = [1, 2, 3, 4, 5, 6, 7]
q = [0, 1, 2, 3, 4, 4, 3]

g = dgl.graph((q, p))

g.ndata['x'] = torch.ones(8, 1)

sampler = dgl.dataloading.neighbor.MultiLayerNeighborSampler([None] * 2)
dataloader = dgl.dataloading.pytorch.NodeDataLoader(g, [0, 5, 9], sampler)

for input_nodes, output_nodes, blocks in dataloader:
    print(input_nodes)
    print(output_nodes)
    print(blocks)
```

### Error messages

```
terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at CPUAllocator.cpp:65] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 753070376028920 bytes. Error code 12 (Cannot allocate memory)
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x47 (0x7f9f2cda26a7 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::alloc_cpu(unsigned long) + 0x1f1 (0x7f9f2cd73901 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x247b6 (0x7f9f2cd757b6 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: at::native::empty_cpu(c10::ArrayRef<long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) + 0x172 (0x7f9fb82e3ed2 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x123fb03 (0x7f9fb85ceb03 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x1217137 (0x7f9fb85a6137 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x123220c (0x7f9fb85c120c in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x120e6ba (0x7f9fb859d6ba in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x1217137 (0x7f9fb85a6137 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x123220c (0x7f9fb85c120c in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #10: at::empty(c10::ArrayRef<long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) + 0xbd (0x7f9fb868d00d in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #11: torch::empty(c10::ArrayRef<long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>)::{lambda()#1}::operator()() const + 0xa8 (0x7f9eef144cf0 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.7.1.so)
frame #12: torch::empty(c10::ArrayRef<long>, c10::TensorOptions const&, c10::optional<c10::MemoryFormat>) + 0x51 (0x7f9eef144d74 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.7.1.so)
frame #13: TAempty + 0x129 (0x7f9eef141316 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.7.1.so)
frame #14: dgl::runtime::NDArray::Empty(std::vector<long, std::allocator<long> >, DLDataType, DLContext) + 0xb6 (0x7f9f0a426936 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/dgl/libdgl.so)
frame #15: dgl::aten::CSRMatrix dgl::aten::impl::CSRSliceRows<(DLDeviceType)1, long>(dgl::aten::CSRMatrix, dgl::runtime::NDArray) + 0x3c5 (0x7f9f09e0e045 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/dgl/libdgl.so)
frame #16: dgl::aten::CSRSliceRows(dgl::aten::CSRMatrix, dgl::runtime::NDArray) + 0x4fe (0x7f9f09d0fa3e in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/dgl/libdgl.so)
frame #17: dgl::UnitGraph::CSR::OutEdges(unsigned long, dgl::runtime::NDArray) const + 0xc8 (0x7f9f0a5493c8 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/dgl/libdgl.so)
frame #18: dgl::UnitGraph::InEdges(unsigned long, dgl::runtime::NDArray) const + 0xc9 (0x7f9f0a542549 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/dgl/libdgl.so)
frame #19: dgl::HeteroGraph::InEdges(unsigned long, dgl::runtime::NDArray) const + 0x46 (0x7f9f0a472ec6 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/dgl/libdgl.so)
frame #20: dgl::InEdgeGraph(std::shared_ptr<dgl::BaseHeteroGraph>, std::vector<dgl::runtime::NDArray, std::allocator<dgl::runtime::NDArray> > const&) + 0x325 (0x7f9f0a503085 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/dgl/libdgl.so)
frame #21: <unknown function> + 0xcab6f7 (0x7f9f0a47e6f7 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/dgl/libdgl.so)
frame #22: DGLFuncCall + 0x48 (0x7f9f0a40aa98 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/dgl/libdgl.so)
frame #23: <unknown function> + 0x16623 (0x7f9eec10f623 in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/dgl/_ffi/_cy3/core.cpython-37m-x86_64-linux-gnu.so)
frame #24: <unknown function> + 0x1694b (0x7f9eec10f94b in /home/zyyan/anaconda3/envs/rlcard/lib/python3.7/site-packages/dgl/_ffi/_cy3/core.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>
```

## Expected behavior

The program shouldn't crash at C/C++ backend, it should raise a Python exception when creating the dataloader or iterating over the dataloader.

## Environment

 - DGL Version (e.g., 1.0): `0.6.0post1`
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): `PyTorch 1.7.1+cu110`
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed DGL (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7.10
 - CUDA/cuDNN version (if applicable): 11.0 (But CUDA isn't running because of broken driver)
 - GPU models and configuration (e.g. V100): 
 - Any other relevant information:

**Comment by manangoel99** [comment]
Hello!
Can I take up this issue?

**Comment by TristonC** [comment]
In DGL 0.9.0 it gives out of bound error message.  Close this issue for being fixed. 
```Traceback (most recent call last):
  File "repro.py", line 15, in <module>
    for input_nodes, output_nodes, blocks in dataloader:
  File "/opt/conda/lib/python3.8/site-packages/dgl/dataloading/dataloader.py", line 513, in __next__
    self._next_non_threaded() if not self.use_thread else self._next_threaded()
  File "/opt/conda/lib/python3.8/site-packages/dgl/dataloading/dataloader.py", line 493, in _next_non_threaded
    batch = next(self.dataloader_it)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 692, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 40, in fetch
    return self.collate_fn(data)
  File "/opt/conda/lib/python3.8/site-packages/dgl/dataloading/dataloader.py", line 537, in __call__
    batch = self.sample_func(self.g, items)
  File "/opt/conda/lib/python3.8/site-packages/dgl/dataloading/base.py", line 243, in sample
    result = self.sample_blocks(g, seed_nodes, exclude_eids=exclude_eids)
  File "/opt/conda/lib/python3.8/site-packages/dgl/dataloading/neighbor_sampler.py", line 110, in sample_blocks
    frontier = g.sample_neighbors(
  File "/opt/conda/lib/python3.8/site-packages/dgl/utils/internal.py", line 921, in _fn
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dgl/sampling/neighbor.py", line 293, in sample_neighbors
    frontier = _sample_neighbors(
  File "/opt/conda/lib/python3.8/site-packages/dgl/sampling/neighbor.py", line 367, in _sample_neighbors
    subgidx = _CAPI_DGLSampleNeighbors(g._graph, nodes_all_types, fanout_array,
  File "dgl/_ffi/_cython/./function.pxi", line 293, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 239, in dgl._ffi._cy3.core.FuncCall
dgl._ffi.base.DGLError: [17:39:40] /opt/dgl/dgl-source/src/array/cpu/spmat_op_impl_csr.cc:438: expect row ID 9 to be less than number of rows 8
