### ISSUE TITLE
EOFError when I try to keep num_workers > 0 in the dataloader

### ISSUE THREAD

**Issue by Pran97** [dmlc/dgl#2890]
The entire error traceback is as follows-
Using backend: pytorch
Loading graph
Loading features
Loading masks and labels
Initializing dataloader...
Initializing model...
  0%|                                                                                                                                                                                              | 0/2173 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 231, in <module>
    train(args, dataset, g, feats, paper_offset)
  File "train.py", line 120, in train
    for i, (input_nodes, output_nodes, mfgs) in enumerate(tq):
  File "C:\Users\e*****\Anaconda3\lib\site-packages\tqdm\std.py", line 1165, in __iter__
    for obj in iterable:
  File "C:\Users\e*****\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "C:\Users\e*****\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\e****\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 914, in __init__
    w.start()
  File "C:\Users\e*****\Anaconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\e******\Anaconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\e*****\Anaconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\e******\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\e******\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\e******\Anaconda3\lib\site-packages\dgl\_ffi\object.py", line 59, in __reduce__
    return (_new_object, (cls, ), self.__getstate__())
  File "C:\Users\e******\Anaconda3\lib\site-packages\dgl\heterograph_index.py", line 32, in __getstate__
    self._pk_state = _CAPI_DGLHeteroPickle(self)
  File "C:\Users\e******\Anaconda3\lib\site-packages\dgl\_ffi\_ctypes\function.py", line 188, in __call__
    check_call(_LIB.DGLFuncCall(
  File "C:\Users\e******\Anaconda3\lib\site-packages\dgl\_ffi\base.py", line 64, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: [19:11:13] C:\Users\Administrator\dgl-0.5\src\graph\unit_graph.cc:1341: The graph have restricted sparse format csc , cannot create CSR matrix.
Using backend: pytorch
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\e*****\Anaconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\e*****\Anaconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

The error vanishes when I keep the  num_workers=0 in the train_dataloader, but as expected it massively slows down the code. Any work around for this error, besides num_workers=0?

**Comment by VoVAllen** [comment]
> dgl._ffi.base.DGLError: [19:11:13] C:\Users\Administrator\dgl-0.5\src\graph\unit_graph.cc:1341: The graph have restricted sparse format csc , cannot create CSR matrix.

It seems you've restricted the format in the subprocess. Could you try remove the restriction?

**Comment by jermainewang** [comment]
Close due to lack of activity.
