### ISSUE TITLE
DGL import error with PyTorch

### ISSUE THREAD

**Issue by lokesharma-dev** [dmlc/dgl#2980]
Hi, 

I have an error while importing DGL library. Shows a '.dll' file missing, however it is available when I look in the mentioned path. Any suggestions?

System Settings
Cuda: Not available
Installation: pip install dgl
torch  version: 1.8.1
numpy | scipy: 1.20.3 | 1.6.3
Python: 3.8.8

Traceback
 ```
   import dgl
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2021.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\n832\PycharmProjects\Sandbox\venv\lib\site-packages\dgl\__init__.py", line 13, in <module>
    from .backend import load_backend, backend_name
  File "C:\Program Files\JetBrains\PyCharm 2021.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\n832\PycharmProjects\Sandbox\venv\lib\site-packages\dgl\backend\__init__.py", line 95, in <module>
    load_backend(get_preferred_backend())
  File "C:\Users\n832\PycharmProjects\Sandbox\venv\lib\site-packages\dgl\backend\__init__.py", line 41, in load_backend
    from .._ffi.base import load_tensor_adapter # imports DGL C library
  File "C:\Program Files\JetBrains\PyCharm 2021.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\n832\PycharmProjects\Sandbox\venv\lib\site-packages\dgl\_ffi\base.py", line 44, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
  File "C:\Users\n832\PycharmProjects\Sandbox\venv\lib\site-packages\dgl\_ffi\base.py", line 34, in _load_lib
    lib = ctypes.CDLL(lib_path[0])
  File "C:\Users\n832\AppData\Local\Programs\Python\Python38\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\n832\PycharmProjects\Sandbox\venv\lib\site-packages\dgl\dgl.dll' (or one of its dependencies). Try using the full path with constructor syntax.



```

**Comment by jermainewang** [comment]
https://discuss.dgl.ai/t/import-error-dgl-with-pytorch/2037/2 Duplicate question here.
