### ISSUE TITLE
RuntimeError: Expected object of scalar type Double but got scalar type Float

### ISSUE THREAD

**Issue by saharshleo** [dmlc/dgl#3052]
```py
print(g)
```

```
Graph(num_nodes=100, num_edges=17144,
      ndata_schemes={'feat': Scheme(shape=(2,), dtype=torch.float64), 'label': Scheme(shape=(), dtype=torch.int64), 'train_mask': Scheme(shape=(), dtype=torch.bool), 'val_mask': Scheme(shape=(), dtype=torch.bool), 'test_mask': Scheme(shape=(), dtype=torch.bool)}
      edata_schemes={'weight': Scheme(shape=(18,), dtype=torch.float64)})
```

```py
# Definition of GCN and train as per node classification tutorial - https://docs.dgl.ai/tutorials/blitz/1_introduction.html
model = GCN(g.ndata['feat'].shape[1], 16, num_classes=2)
train(g, model)
```

```
Traceback (most recent call last):
  File "test_gcn.py", line 163, in <module>
    train(g, model)
  File "test_gcn.py", line 52, in train
    logits = model(g, features)
  File "python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "test_gcn.py", line 34, in forward
    h = self.conv1(g, in_feat)
  File "python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "python3.6/site-packages/dgl/nn/pytorch/conv/graphconv.py", line 426, in forward
    rst = th.matmul(rst, weight)
RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #3 'mat2' in call to _th_addmm_out
```

PS - I tried writing on dgl forum, but i think your mailing system is not working

**Comment by VoVAllen** [comment]
DGL only supports float32. You need to manually convert your tensor to float32 by `tensor = tensor.float()`
