### ISSUE TITLE
Questions about example in dgl seal model on ogbl-collab

### ISSUE THREAD

**Issue by jalencato** [dmlc/dgl#3162]
## 🐛 Bug

when running the example code in seal, it sends error like:

## error message
Traceback (most recent call last):
  File "main.py", line 175, in <module>
    main(args, logger.info)
  File "main.py", line 91, in main
    train_data = seal_data('train')
 File "/home/ubuntu/tmp/Experiment/link/dgl/previous/sampler.py", line 253, in __call__
    graph_list, labels = self.sampler(edges, labels)
  File "/home/ubuntu/tmp/Experiment/link/dgl/previous/sampler.py", line 175, in __call__
    for subgraph, label in tqdm(sampler, ncols=100):
  File "/home/ubuntu/anaconda3/envs/sealdgl/lib/python3.7/site-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/home/ubuntu/anaconda3/envs/sealdgl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/ubuntu/anaconda3/envs/sealdgl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/home/ubuntu/anaconda3/envs/sealdgl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/home/ubuntu/anaconda3/envs/sealdgl/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/ubuntu/anaconda3/envs/sealdgl/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/ubuntu/anaconda3/envs/sealdgl/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
    fd = df.detach()
  File "/home/ubuntu/anaconda3/envs/sealdgl/lib/python3.7/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/ubuntu/anaconda3/envs/sealdgl/lib/python3.7/multiprocessing/reduction.py", line 185, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/ubuntu/anaconda3/envs/sealdgl/lib/python3.7/multiprocessing/reduction.py", line 161, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata

## Expected behavior
I wonder if there is any problem in the sampler, but how to fix it? 

Meanwhile, the code in main, line 88: "edge_weight = seal_data.edata['edge_weight'].float()" should be altered with "edge_weight = seal_data.edata['weight'].float()"

## Environment

 - DGL Version 0.6:
 - Backend Library & Version PyTorch 1.5/1.8:
 - Linux:
 - How you installed DGL: conda:
 - Python version: 3.7
 - CUDA/cuDNN version (if applicable):10.2

**Comment by VoVAllen** [comment]
Hi,

Thanks for reporting the typo.

However, I can run it on my machine. Could you try a smaller `num_workers` on your machine such as 4 or 0? I guess the subprocess might experience OOM and killed by the system
