### ISSUE TITLE
when i test DGLGraph API REFERENCE has typeError

### ISSUE THREAD

**Issue by DancyHuang** [dmlc/dgl#321]
i am new to DGL and be interested in it，after install dgl on python 3, then test API references;  shell below:
-------------------------------------------------------------------------------------------------
>>> import dgl
>>> import torch as th
>>> 
>>> G = dgl.DGLGraph()
>>> G.add_nodes(3) 
>>> G.ndata['x'] = th.zeros((3, 5))
>>> G.ndata
{'x': tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]])}
>>> G.nodes[[0, 2]].data['x'] = th.ones((2, 5))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lib/ceph/osd/ceph-0/tf/dgl/dgl-master/python/dgl/view.py", line 54, in __setitem__
    self._graph.set_n_repr({key : val}, self._nodes)
  File "/var/lib/ceph/osd/ceph-0/tf/dgl/dgl-master/python/dgl/graph.py", line 1526, in set_n_repr
    u = utils.toindex(u)
  File "/var/lib/ceph/osd/ceph-0/tf/dgl/dgl-master/python/dgl/utils.py", line 130, in toindex
    return x if isinstance(x, Index) else Index(x)
  File "/var/lib/ceph/osd/ceph-0/tf/dgl/dgl-master/python/dgl/utils.py", line 15, in __init__
    self._initialize_data(data)
  File "/var/lib/ceph/osd/ceph-0/tf/dgl/dgl-master/python/dgl/utils.py", line 21, in _initialize_data
    self._dispatch(data)
  File "/var/lib/ceph/osd/ceph-0/tf/dgl/dgl-master/python/dgl/utils.py", line 76, in _dispatch
    self._user_tensor_data[F.cpu()] = F.zerocopy_from_numpy(self._pydata)
TypeError: unhashable type: 'torch.Device'
>>> 
-------------------------------------------------------------------------------------------------
       BTW, Is there a good way to solve this problems？ 
       Thanks!

**Comment by DancyHuang** [comment]
it  works ok in pytorch 0.4.1+
