### ISSUE TITLE
Encounter indexerror when running distributed training for Grapgsage with 4 layer

### ISSUE THREAD

**Issue by zfthys** [dmlc/dgl#3263]
## 🐛 Bug

I ran train_dist.py( dgl/examples/pytorch/graphsage/experimental/train_dist.py) and set num_layers to 4，the model Encountered Indexerror when initializing loss function.
The code ran on 2 CPU.

## To Reproduce

1.run the script provided by dgl：
python3 $HOME/dgl/dgl_hys/tools/launch.py \
  --workspace $HOME/dgl/dgl_hys/examples/pytorch/graphsage/experimental/ \
  --ssh_port 22200 \
  --num_trainers 1 \
  --num_samplers 0 \
  --num_servers 1 \
  --part_config data/ogb-product.json \
  --ip_config ip_config.txt \
  "python3 train_dist.py --num_layers 4 --graph_name ogb-product --ip_config ip_config.txt --num_epochs 30 --batch_size 1000"

The error message that I am getting is,
[1,0]<stderr>:INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
[1,0]<stderr>:INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_gsd7ljcg/none_tkl_0jg6/attempt_0/0/error.json
[1,0]<stderr>:Using backend: pytorch
[1,0]<stderr>:Using backend: pytorch
[1,0]<stderr>:Warning! Interface: em2 
[1,0]<stderr>:IP address not available for interface.
[1,0]<stderr>:Warning! Interface: em2 
[1,0]<stderr>:IP address not available for interface.
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "train_dist.py", line 319, in <module>
[1,0]<stderr>:    main(args)
[1,0]<stderr>:  File "train_dist.py", line 290, in main
[1,0]<stderr>:    run(args, device, data)
[1,0]<stderr>:  File "train_dist.py", line 221, in run
[1,0]<stderr>:    loss = loss_fcn(batch_pred, batch_labels)
[1,0]<stderr>:  File "/home/hongy0c/dgl/dgl-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
[1,0]<stderr>:    return forward_call(*input, **kwargs)
[1,0]<stderr>:  File "/home/hongy0c/dgl/dgl-env/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1120, in forward
[1,0]<stderr>:    return F.cross_entropy(input, target, weight=self.weight,
[1,0]<stderr>:  File "/home/hongy0c/dgl/dgl-env/lib/python3.8/site-packages/torch/nn/functional.py", line 2824, in cross_entropy
[1,0]<stderr>:    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
[1,0]<stderr>:IndexError[1,0]<stderr>:: [1,0]<stderr>:Target 17 is out of bounds.
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "train_dist.py", line 319, in <module>
[1,0]<stderr>:    main(args)
[1,0]<stderr>:  File "train_dist.py", line 290, in main
[1,0]<stderr>:    run(args, device, data)[1,0]<stderr>:
[1,0]<stderr>:  File "train_dist.py", line 221, in run
[1,0]<stderr>:    loss = loss_fcn(batch_pred, batch_labels)
[1,0]<stderr>:  File "/home/hongy0c/dgl/dgl-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
[1,0]<stderr>:    [1,0]<stderr>:return forward_call(*input, **kwargs)
[1,0]<stderr>:  File "/home/hongy0c/dgl/dgl-env/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1120, in forward
[1,0]<stderr>:    [1,0]<stderr>:return F.cross_entropy(input, target, weight=self.weight,
[1,0]<stderr>:  File "/home/hongy0c/dgl/dgl-env/lib/python3.8/site-packages/torch/nn/functional.py", line 2824, in cross_entropy
[1,0]<stderr>:    [1,0]<stderr>:return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
[1,0]<stderr>:IndexError: Target 20 is out of bounds.
[1,0]<stderr>:Using backend: pytorch
[1,0]<stderr>:Using backend: pytorch
[1,1]<stderr>:[232634] Aug 18 06:27:31 Exit (hongy0c) from <10.109.75.62:42050>: Disconnect received
[1,0]<stderr>:[232737] Aug 18 06:27:31 Exit (hongy0c) from <10.109.75.62:39258>: Disconnect received
[1,0]<stderr>:ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 232874) of binary: /home/hongy0c/dgl/dgl-env/bin/python3
[1,0]<stderr>:ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
[1,0]<stderr>:INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
[1,0]<stderr>:INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group

## Environment

 - DGL Version (e.g., 1.0): 0.7a210714
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.9.0
 - OS (e.g., Linux): CentOS 7.9
 - How you installed DGL (`conda`, `pip`, source): 
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - Any other relevant information:

**Comment by classicsong** [comment]
Did you set the fan_out?

**Comment by zfthys** [comment]
> Did you set the fan_out?

I used the default fan_out, which is '10,25'

**Comment by ranzhejiang** [comment]
when your num_layers are 4, your fan_out must be four too, such as '10,10,10,10'

**Comment by zfthys** [comment]
> when your num_layers are 4, your fan_out must be four too, such as '10,10,10,10'

It work! Thank you!
