### ISSUE TITLE
AttributeError: 'DGLHeteroGraph' object has no attribute 'number_of_etypes'

### ISSUE THREAD

**Issue by Flawless1202** [dmlc/dgl#3266]
## 🐛 Bug

An error occurred when use the function `edge_softmax`

## To Reproduce

The behavior can be reproduced by the following code:

```
import math

import torch
import dgl.function as fn
import dgl
from dgl.backend.pytorch import edge_softmax

g = dgl.graph(
    (
        [0, 0, 0, 0, 0, 0],
        [0, 1, 2, 3, 4, 5],
    ),
    num_nodes=6,
)
g = dgl.remove_self_loop(g)
g = dgl.add_self_loop(g)

q = torch.rand((6, 32))
k = torch.rand((6, 32))
v = torch.rand((6, 32))

g.srcdata.update({"q": q})
g.dstdata.update({"k": k})

g.apply_edges(fn.u_dot_v("q", "k", "score"))
g.edata["attn"] = edge_softmax(g, g.edata["score"] / math.sqrt(32))
```

And the std outputs are as follow:

```
Traceback (most recent call last):
  File "bug_report.py", line 26, in <module>
    g.edata["attn"] = edge_softmax(g, g.edata["score"] / math.sqrt(32))
  File "/home/chenkai/.virtualenvs/dgl/lib/python3.8/site-packages/dgl/backend/pytorch/sparse.py", line 437, in edge_softmax
    return EdgeSoftmax.apply(gidx, logits, eids, norm_by)
  File "/home/chenkai/.virtualenvs/dgl/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 219, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/chenkai/.virtualenvs/dgl/lib/python3.8/site-packages/dgl/backend/pytorch/sparse.py", line 291, in forward
    score_max = _gspmm(gidx, 'copy_rhs', 'max', None, score)[0]
  File "/home/chenkai/.virtualenvs/dgl/lib/python3.8/site-packages/dgl/sparse.py", line 118, in _gspmm
    if gidx.number_of_etypes() != 1:
AttributeError: 'DGLHeteroGraph' object has no attribute 'number_of_etypes'
``` 

## Expected behavior

Change the judgment `if gidx.number_of_etypes() != 1` in line 118 of file 'dgl/sparse.py'

## Environment

 - DGL Version: DGL  0.7.0 + cu111
 - Backend Library & Version: PyTorch 1.9.0 + cu111
 - OS: Ubuntu 20.04
 - How you installed DGL: pip
 - Build command you used (if compiling from source): No
 - Python version: 3.8.10
 - CUDA/cuDNN version (if applicable): CUDA 11.1 and cuDNN 8.2.1
 - GPU models and configuration: Nvidia RTX 3090
 - Any other relevant information:

## Additional context

No

**Comment by Flawless1202** [comment]
Change the import code
```
from dgl.backend.pytorch import edge_softmax
```
to follow one 
```
from dgl.ops import edge_softmax
```
can solve the problem.

**Comment by Flawless1202** [comment]
Change the import code
```
from dgl.backend.pytorch import edge_softmax
```
to follow one 
```
from dgl.ops import edge_softmax
```
can solve the problem.
