### ISSUE TITLE
Unit test was successful locally but timeout on Jenkins

### ISSUE THREAD

**Issue by jwyyy** [dmlc/dgl#3282]
## 🐛 Bug

I submitted a PR which rans successfully on my Ubuntu desktop. But when doing checks online, the unit test ran [test_mp_dataloader.py](https://github.com/dmlc/dgl/blob/master/tests/distributed/test_mp_dataloader.py) for more than 10 minutes and triggered timeout.

## To Reproduce

1. PR https://github.com/dmlc/dgl/pull/3279
2. Success message on local Ubuntu:
```
[21:00:46] /home/usrname/github/dgl/src/graph/transform/metis_partition_hetero.cc:78: Partition a graph with 2708 nodes and 10556 edges into 3 parts and get 413 edge cuts
Metis partitioning: 0.002 seconds
Split the graph: 0.001 seconds
Construct subgraphs: 0.002 seconds
/home/usrname/github/dgl/python/dgl/backend/pytorch/tensor.py:273: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mask = th.tensor(mask, dtype=th.bool)
Calculate edge assignment: 0.001 seconds
part 0 has 1071 nodes and 903 are inside the partition
part 0 has 3530 edges and 3267 are inside the partition
part 1 has 1137 nodes and 903 are inside the partition
part 1 has 3792 edges and 3502 are inside the partition
part 2 has 1088 nodes and 902 are inside the partition
part 2 has 4060 edges and 3787 are inside the partition
Save partitions: 0.022 seconds
There are 10556 edges in the graph and 0 edge cuts for 3 partitions.

```
3. Checks failed at the graph that was successfully tested on local Ubuntu. Before this partition test, everything was smooth.
```
tests/distributed/test_mp_dataloader.py::test_neg_dataloader[0-3] [03:47:02] /home/jenkins/agent/workspace/dgl_PR-3279/src/graph/transform/metis_partition_hetero.cc:78: Partition a graph with 2708 nodes and 10556 edges into 3 parts and get 413 edge cuts

Sending interrupt signal to process

Killing processes

kill finished with exit code 0

[[[04:01:4404:01:44] /home/jenkins/agent/workspace/dgl_PR-3279/src/rpc/rpc.cc:] 329/home/jenkins/agent/workspace/dgl_PR-3279/src/rpc/rpc.cc: :04:01:44

User pressed Ctrl+C, Exiting] 

/home/jenkins/agent/workspace/dgl_PR-3279/src/rpc/rpc.cc329:: 

User pressed Ctrl+C, Exiting

329: 

User pressed Ctrl+C, Exiting

[04:01:44] /home/jenkins/agent/workspace/dgl_PR-3279/src/rpc/rpc.cc:329: 

User pressed Ctrl+C, Exiting

Terminated

terminate called without an active exception

terminate called without an active exception

terminate called without an active exception

script returned exit code 143
```

## Environment

 - DGL Version (e.g., 1.0): **0.8**
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): **PyTorch 1.9.0**
 - OS (e.g., Linux): **Ubuntu**
 - How you installed DGL (`conda`, `pip`, source): **source**
 - Build command you used (if compiling from source): **successful**
 - Python version: **3.8.11**
 - CUDA/cuDNN version (if applicable): **NA**

## Additional context

I thought the problem was due to a performance issue in the first PR that slowed down the test. However, once the issue was fixed and the test ran without any problem locally, the same issue still happened in Jenkins checking.

**Comment by VoVAllen** [comment]
Thanks for reporting. Will take a look tommorow

**Comment by jwyyy** [comment]
Hi @VoVAllen , do you have any update on this issue? Had a new one today when updating the same draft PR. The problem was with [test_dist_graph_store.py](https://github.com/dmlc/dgl/blob/master/tests/distributed/test_dist_graph_store.py). Local test was successful. The PR only modifies dataloader.py. The same error occurred even after master branch was merged.

The error is below:
```
tests/distributed/test_dist_graph_store.py::test_server_client [20:07:01] /home/jenkins/agent/workspace/dgl_PR-3279/src/graph/transform/metis_partition_hetero.cc:78: Partition a graph with 10000 nodes and 199872 edges into 4 parts and get 56503 edge cuts

Machine (0) client (3) connect to server successfuly!

Using backend: pytorch

Machine (0) client (0) connect to server successfuly!

Using backend: pytorch

Machine (0) client (1) connect to server successfuly!

Using backend: pytorch

Machine (0) client (2) connect to server successfuly!

Using backend: pytorch

load dist_graph_test_2

start server 0

start graph service on server 0 for part 0

Wait connections ...

4 clients connected!

Server (0) shutdown.

Using backend: pytorch

Convert a graph into a bidirected graph: 0.005 seconds

Metis partitioning: 0.056 seconds

Save partitions: 0.011 seconds

There are 100000 edges in the graph and 0 edge cuts for 1 partitions.

Using backend: pytorch

run graph store with port 5883

Machine (0) client (0) connect to server successfuly!

end

Using backend: pytorch

Error in atexit._run_exitfuncs:

Traceback (most recent call last):

  File "/home/jenkins/agent/workspace/dgl_PR-3279/python/dgl/distributed/dist_context.py", line 316, in exit_client

    rpc.client_barrier()

  File "/home/jenkins/agent/workspace/dgl_PR-3279/python/dgl/distributed/rpc.py", line 931, in client_barrier

    assert res.msg == 'barrier'

AssertionError

terminate called without an active exception
```

**Comment by jermainewang** [comment]
Since PR #3279 is deprecated in favor of a new one, close this issue.
