### ISSUE TITLE
NameError: name 'torch' is not defined in train_cv_multi_gpu.py test for multigpu training

### ISSUE THREAD

**Issue by TristonC** [dmlc/dgl#3369]
## 🐛 Bug

Error shows torch is not defined in the multi-gpu test for train_cv_multi-gpu.py. 

It seems that the https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/train_cv_multi_gpu.py#L16 is missing an import.  Append , distributedto that line should fix the problem.

## To Reproduce

1. python3 train_cv_multi_gpu.py --num-epochs 30 --gpu 0,1

Using backend: pytorch
Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dgl-0.7.1-py3.8-linux-x86_64.egg/dgl/multiprocessing/pytorch.py", line 29, in decorated_function
    raise exception.__class__(trace)
NameError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/dgl-0.7.1-py3.8-linux-x86_64.egg/dgl/multiprocessing/pytorch.py", line 17, in _queue_result
    res = func(*args, **kwargs)
  File "train_cv_multi_gpu.py", line 242, in run
    dist_sampler = torch.utils.data.distributed.DistributedSampler(train_nid.numpy(), shuffle=True, drop_last=False)
NameError: name 'torch' is not defined

Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/dgl-0.7.1-py3.8-linux-x86_64.egg/dgl/multiprocessing/pytorch.py", line 29, in decorated_function
    raise exception.__class__(trace)
NameError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/dgl-0.7.1-py3.8-linux-x86_64.egg/dgl/multiprocessing/pytorch.py", line 17, in _queue_result
    res = func(*args, **kwargs)
  File "train_cv_multi_gpu.py", line 242, in run
    dist_sampler = torch.utils.data.distributed.DistributedSampler(train_nid.numpy(), shuffle=True, drop_last=False)
NameError: name 'torch' is not defined

## Environment

 - DGL Version: master
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by TristonC** [comment]
@BarclayII Could you help on this issue?

**Comment by jwyyy** [comment]
Hi @TristonC , `torch` is imported as `th` in [line 3](https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/train_cv_multi_gpu.py#L3). An easy fix is to use `th.utils.data.distributed.DistributedSampler`.
