### ISSUE TITLE
Distributed graph partition doesn't work on OGBN-mag

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#3420]
## 🐛 Bug

After partitioning the graph with ParMETIS, distributed training fails with the following error. This problem happens in the master branch.

```
Traceback (most recent call last):
  File "entity_classify_dist.py", line 643, in <module>
    main(args)
  File "entity_classify_dist.py", line 583, in main
    run(args, device, (g, n_classes, train_nid, val_nid, test_nid, labels, all_val_nid, all_test_nid))
  File "entity_classify_dist.py", line 481, in run
    for step, sample_data in enumerate(dataloader):
  File "/home/ubuntu/workspace/dgl/python/dgl/distributed/dist_dataloader.py", line 108, in __next__
    self._request_next_batch()
  File "/home/ubuntu/workspace/dgl/python/dgl/distributed/dist_dataloader.py", line 140, in _request_next_batch
    result = self.collate_fn(next_data)
  File "/home/ubuntu/workspace/dgl/python/dgl/dataloading/dataloader.py", line 560, in collate
    blocks = self.block_sampler.sample_blocks(self.g, items)
  File "/home/ubuntu/workspace/dgl/python/dgl/dataloading/dataloader.py", line 393, in sample_blocks
    block = transform.to_block(frontier, seed_nodes_out)
  File "/home/ubuntu/workspace/dgl/python/dgl/transform.py", line 2260, in to_block
    new_graph_index, src_nodes_ids_nd, induced_edges_nd = _CAPI_DGLToBlock(
  File "/home/ubuntu/workspace/dgl/python/dgl/_ffi/_ctypes/function.py", line 188, in __call__
    check_call(_LIB.DGLFuncCall(
  File "/home/ubuntu/workspace/dgl/python/dgl/_ffi/base.py", line 64, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: [05:04:15] /home/ubuntu/workspace/dgl/src/graph/transform/to_bipartite.cc:119: Check failed: new_dst.Ptr<IdType>()[i] != -1 (-1 vs. -1) : Node 675208 does not exist in `rhs_nodes`. Argument `rhs_nodes` must contain all the edge destination nodes.
Stack trace:
  [bt] (0) /home/ubuntu/workspace/dgl/build/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x80) [0x7f75aa0c8d70]
  [bt] (1) /home/ubuntu/workspace/dgl/build/libdgl.so(+0x537204) [0x7f75aa4aa204]
  [bt] (2) /home/ubuntu/workspace/dgl/build/libdgl.so(std::tuple<std::shared_ptr<dgl::BaseHeteroGraph>, std::vector<dgl::runtime::NDArray, std::allocator<dgl::runtime::NDArray> > > dgl::transform::ToBlock<(DLDeviceType)1, long>(std::shared_ptr<dgl::BaseHeteroGraph>, std::vector<dgl::runtime::NDArray, std::allocator<dgl::runtime::NDArray> > const&, bool, std::vector<dgl::runtime::NDArray, std::allocator<dgl::runtime::NDArray> >*)+0x4f) [0x7f75aa4aaf5f]
  [bt] (3) /home/ubuntu/workspace/dgl/build/libdgl.so(+0x539181) [0x7f75aa4ac181]
  [bt] (4) /home/ubuntu/workspace/dgl/build/libdgl.so(+0x5394a8) [0x7f75aa4ac4a8]
  [bt] (5) /home/ubuntu/workspace/dgl/build/libdgl.so(DGLFuncCall+0x60) [0x7f75aa357aa0]
  [bt] (6) /lib/x86_64-linux-gnu/libffi.so.7(+0x6ff5) [0x7f75e2a6eff5]
  [bt] (7) /lib/x86_64-linux-gnu/libffi.so.7(+0x640a) [0x7f75e2a6e40a]
  [bt] (8) /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(_ctypes_callproc+0x5b6) [0x7f75e590a306]
```

## To Reproduce

In `examples/pytorch/rgcn/experimental`, partition the graph as follows:

```
python3 write_mag.py
pm_dglpart mag 2
python3 ~/workspace/dgl/tools/convert_partition.py --input-dir . --graph-name mag --num-parts 2 --workspace /tmp/ --output outputs --schema mag.json --num-node-weights 4
python3 get_mag_data.py
```

Run distributed training on two machines:

```
python3 ~/workspace/dgl/tools/launch.py --workspace ~/workspace/dgl/examples/pytorch/rgcn/experimental/ --num_trainers 1 --num_servers 1 --num_samplers 0 --part_config outputs/mag.json --ip_config ip_config2.txt "python3 entity_classify_dist.py --graph-name mag --dataset mag --fanout='25,25' --batch-size 1024  --n-hidden 64 --lr 0.01 --eval-batch-size 1024  --low-mem --dropout 0.5 --use-self-loop --n-bases 2 --n-epochs 3 --layer-norm --ip-config ip_config2.txt  --sparse-embedding --sparse-lr 0.06"
```

I did some investigation. It seems the canonical etypes calculated from the edges in DistGraph (https://github.com/dmlc/dgl/blob/master/python/dgl/distributed/dist_graph.py#L502) are incorrect.

Basically, the constructed partitions fail in the following test. The test code can be found here: https://github.com/dmlc/dgl/pull/3366/files

```
eid = []
gpb = dgl.distributed.graph_partition_book.RangePartitionBook(0, 2, node_map, edge_map,
        {ntype:i for i, ntype in enumerate(hg.ntypes)},
        {etype:i for i, etype in enumerate(hg.etypes)})
subg0 = dgl.load_graphs('{}/part0/graph.dgl'.format(partitions_folder))[0][0]
for etype in hg.etypes:
    type_eid = th.zeros((1,), dtype=th.int64)
    eid.append(gpb.map_to_homo_eid(type_eid, etype))
eid = th.cat(eid)
part_id = gpb.eid2partid(eid)
assert np.all(part_id.numpy() == 0)
local_eid = gpb.eid2localeid(eid, 0)
assert np.all(local_eid.numpy() == eid.numpy())
assert np.all((subg0.edata[dgl.EID][local_eid] == eid).numpy())
lsrc, ldst = subg0.find_edges(local_eid)
gsrc, gdst = subg0.ndata[dgl.NID][lsrc], subg0.ndata[dgl.NID][ldst]
assert np.all(gsrc.numpy() == lsrc.numpy())
assert np.all(gdst.numpy() == ldst.numpy())
etids, _ = gpb.map_to_per_etype(eid)
src_tids, _ = gpb.map_to_per_ntype(gsrc)
dst_tids, _ = gpb.map_to_per_ntype(gdst)
canonical_etypes = []
etype_ids = th.arange(0, len(etypes))
for src_tid, etype_id, dst_tid in zip(src_tids, etype_ids, dst_tids):
    canonical_etypes.append((ntypes[src_tid], etypes[etype_id], ntypes[dst_tid]))
for etype in canonical_etypes:
    assert etype in hg.canonical_etypes
```

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
fixed in https://github.com/dmlc/dgl/pull/3472.
