### ISSUE TITLE
use GPU to train GraphSAGE: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.

### ISSUE THREAD

**Issue by raninbowlalala** [dmlc/dgl#3422]
## To Reproduce

1.dgl_cu101_0.6.1
1.python3.6
1.torch1.7

 python3 train_sampling.py --gpu 0
## Expected behavior
train successfully

## Environment

 - DGL Version (e.g., 1.0):cu10.1_0.6.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):pytoch1.7.0
 - OS (e.g., Linux):linux
 - How you installed DGL (`conda`, `pip`, source):pip 
 - Build command you used (if compiling from source):
 - Python version:3.6.9
 - CUDA/cuDNN version (if applicable):10.1
 - GPU models and configuration (e.g. V100):V100
 - Any other relevant information:

## Additional context

Traceback (most recent call last):
  File "train_sampling.py", line 229, in <module>
    run(args, device, data)
  File "train_sampling.py", line 129, in run
    batch_pred = model(blocks, batch_inputs, device)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sage_lim/model.py", line 44, in forward
    h = layer(block, x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dgl/nn/pytorch/conv/sageconv.py", line 230, in forward
    graph.srcdata['h'] = self.fc_neigh(feat_src) if lin_before_mp else feat_src
  File "/usr/local/lib/python3.6/dist-packages/dgl/view.py", line 81, in __setitem__
    self._graph._set_n_repr(self._ntid, self._nodes, {key : val})
  File "/usr/local/lib/python3.6/dist-packages/dgl/heterograph.py", line 3997, in _set_n_repr
    ' same device.'.format(key, F.context(val), self.device))
dgl._ffi.base.DGLError: Cannot assign node feature "h" on device cuda:0 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.

**Comment by VoVAllen** [comment]
Hi, I cannot reproduce the error on my machine. Did you make any modification to your code?
