### ISSUE TITLE
Bug in dgl.data.utils.generate_mask_tensor

### ISSUE THREAD

**Issue by zhaorui-tan** [dmlc/dgl#3453]
## 🐛 Bug

 I am trying to generate a mask tensor for nodes and it shows the error as below. It seems bool type masks cannot be saved because the dlpack does not support bool type. I tried to change the source code to generate a float type tensor as a mask and it worked.  

## Environment

 - DGL Version 0.6.1:
 - PyTorch 1.10.0
 - OS windos:
 - How you installed DGL (`pip`):
 - Build command you used (if compiling from source):
 - Python version 3.7:

## Error
`Using backend: pytorch
Successfully added node data
Traceback (most recent call last):
  File "C:/Users/Ray Tan/Documents/hetero_t2i/codes/magnn/hetro_graph_data_loader.py", line 124, in <module>
    a = SGLoader()
  File "C:/Users/Ray Tan/Documents/hetero_t2i/codes/magnn/hetro_graph_data_loader.py", line 42, in __init__
    super().__init__('SG')
  File "C:\Users\Ray Tan\.conda\envs\torch_1_2\lib\site-packages\dgl\data\dgl_dataset.py", line 93, in __init__
    self._load()
  File "C:\Users\Ray Tan\.conda\envs\torch_1_2\lib\site-packages\dgl\data\dgl_dataset.py", line 179, in _load
    self.save()
  File "C:/Users/Ray Tan/Documents/hetero_t2i/codes/magnn/hetro_graph_data_loader.py", line 45, in save
    save_graphs(os.path.join(self.save_path, self.name + '_dgl_graph.bin'), [self.g])
  File "C:\Users\Ray Tan\.conda\envs\torch_1_2\lib\site-packages\dgl\data\graph_serialize.py", line 130, in save_graphs
    save_heterographs(filename, g_list, labels)
  File "C:\Users\Ray Tan\.conda\envs\torch_1_2\lib\site-packages\dgl\data\heterograph_serialize.py", line 28, in save_heterographs
    gdata_list = [HeteroGraphData.create(g) for g in g_list]
  File "C:\Users\Ray Tan\.conda\envs\torch_1_2\lib\site-packages\dgl\data\heterograph_serialize.py", line 28, in <listcomp>
    gdata_list = [HeteroGraphData.create(g) for g in g_list]
  File "C:\Users\Ray Tan\.conda\envs\torch_1_2\lib\site-packages\dgl\data\heterograph_serialize.py", line 42, in create
    ndata_list.append(tensor_dict_to_ndarray_dict(g.nodes[ntype].data))
  File "C:\Users\Ray Tan\.conda\envs\torch_1_2\lib\site-packages\dgl\data\heterograph_serialize.py", line 17, in tensor_dict_to_ndarray_dict
    ndarray_dict[key] = F.zerocopy_to_dgl_ndarray(value)
  File "C:\Users\Ray Tan\.conda\envs\torch_1_2\lib\site-packages\dgl\backend\pytorch\tensor.py", line 324, in zerocopy_to_dgl_ndarray
    return nd.from_dlpack(dlpack.to_dlpack(data.contiguous()))
RuntimeError: Bool type is not supported by dlpack

Process finished with exit code 1
`

**Comment by VoVAllen** [comment]
Could you try our nightly version? It should be fixed by now

**Comment by zhaorui-tan** [comment]
Yes, it seems working fine for me now. Cheers!

**Comment by PolarisRisingWar** [comment]
I've met a similar question, and by using test version I also tempororaly solved this problem. I wonder if I downloaded the nightly version, how should I upgrade the package in the future? For example, should I use command like `pip install --upgrade dgl-cu102` just as usual?

My specific error message:
code:
```python
import dgl
import torch
import torch.nn as nn
import torch.nn.functional as F

import dgl.data

dataset = dgl.data.CoraGraphDataset()
print('Number of categories:', dataset.num_classes)
```
Error message:
```
Traceback (most recent call last):
  File "/home/(myusername)/whj_code2/trydgl.py", line 8, in <module>
    dataset = dgl.data.CoraGraphDataset()
  File "/home/(myusername)/anaconda3/envs/cuda102/lib/python3.9/site-packages/dgl/data/citation_graph.py", line 406, in __init__
    super(CoraGraphDataset, self).__init__(name, raw_dir, force_reload, verbose, reverse_edge)
  File "/home/(myusername)/anaconda3/envs/cuda102/lib/python3.9/site-packages/dgl/data/citation_graph.py", line 67, in __init__
    super(CitationGraphDataset, self).__init__(name,
  File "/home/(myusername)/anaconda3/envs/cuda102/lib/python3.9/site-packages/dgl/data/dgl_dataset.py", line 282, in __init__
    super(DGLBuiltinDataset, self).__init__(name,
  File "/home/(myusername)/anaconda3/envs/cuda102/lib/python3.9/site-packages/dgl/data/dgl_dataset.py", line 93, in __init__
    self._load()
  File "/home/(myusername)/anaconda3/envs/cuda102/lib/python3.9/site-packages/dgl/data/dgl_dataset.py", line 179, in _load
    self.save()
  File "/home/(myusername)/anaconda3/envs/cuda102/lib/python3.9/site-packages/dgl/data/citation_graph.py", line 171, in save
    save_graphs(str(graph_path), self._g)
  File "/home/(myusername)/anaconda3/envs/cuda102/lib/python3.9/site-packages/dgl/data/graph_serialize.py", line 130, in save_graphs
    save_heterographs(filename, g_list, labels)
  File "/home/(myusername)/anaconda3/envs/cuda102/lib/python3.9/site-packages/dgl/data/heterograph_serialize.py", line 28, in save_heterographs
    gdata_list = [HeteroGraphData.create(g) for g in g_list]
  File "/home/(myusername)/anaconda3/envs/cuda102/lib/python3.9/site-packages/dgl/data/heterograph_serialize.py", line 28, in <listcomp>
    gdata_list = [HeteroGraphData.create(g) for g in g_list]
  File "/home/(myusername)/anaconda3/envs/cuda102/lib/python3.9/site-packages/dgl/data/heterograph_serialize.py", line 42, in create
    ndata_list.append(tensor_dict_to_ndarray_dict(g.nodes[ntype].data))
  File "/home/(myusername)/anaconda3/envs/cuda102/lib/python3.9/site-packages/dgl/data/heterograph_serialize.py", line 17, in tensor_dict_to_ndarray_dict
    ndarray_dict[key] = F.zerocopy_to_dgl_ndarray(value)
  File "/home/(myusername)/anaconda3/envs/cuda102/lib/python3.9/site-packages/dgl/backend/pytorch/tensor.py", line 324, in zerocopy_to_dgl_ndarray
    return nd.from_dlpack(dlpack.to_dlpack(data.contiguous()))
RuntimeError: Bool type is not supported by dlpack
```
Installed DGL by pip. (Command: pip install dgl-cu102 -f https://data.dgl.ai/wheels/repo.html)
other package version that maybe related to this problem:
python 3.9
torch 1.10.0 (with cuda10.2 cudatoolkit)

**Comment by VoVAllen** [comment]
@PolarisRisingWar We're going to release 0.7.2 to patch this problem and we're in the final pre-release stage. For now, you can use our nightly version by `pip install --pre dgl-cu102 -f https://data.dgl.ai/wheels-test/repo.html`

**Comment by VoVAllen** [comment]
We expect to release 0.7.2 early next week.
