### ISSUE TITLE
Is it possible to export stgcn_wave to a torchscript model?

### ISSUE THREAD

**Issue by HaoWei-TomTom** [dmlc/dgl#3493]
## To Reproduce

I want to export [stgcn_wave](https://github.com/dmlc/dgl/tree/master/examples/pytorch/stgcn_wave) model to a torchscript model.
What I did is:

1. add these two lines below [the line 11](https://github.com/dmlc/dgl/blob/master/examples/pytorch/stgcn_wave/utils.py#L11)
```
            traced_script_module = torch.jit.trace(model, x, check_trace=False)
            traced_script_module.save("stgcn_torchscript.pt")
```
2. then I got this error:
```
<virtual env path>/lib/python3.6/site-packages/dgl/nn/pytorch/conv/graphconv.py:388: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if (graph.in_degrees() == 0).any():
<virtual env path>/lib/python3.6/site-packages/dgl/heterograph.py:2730: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  if len(vid_tensor) > 0 and F.as_scalar(F.min(vid_tensor, 0)) < 0 < len(vid_tensor):
<virtual env path>/lib/python3.6/site-packages/dgl/backend/pytorch/tensor.py:49: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return data.item()
<virtual env path>/lib/python3.6/site-packages/dgl/heterograph.py:3580: TracerWarning: Using len to get tensor shape might cause the trace to be incorrect. Recommended usage would be tensor.shape[0]. Passing a tensor of different shape might lead to errors or silently give incorrect results.
  if F.as_scalar(F.sum(self.has_nodes(u_tensor, ntype=srctype), dim=0)) != len(u_tensor):
<virtual env path>/lib/python3.6/site-packages/dgl/heterograph.py:4109: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if nfeats != num_nodes:
Traceback (most recent call last):
  File "main.py", line 117, in <module>
    val_loss = evaluate_model(model, loss, val_iter)
  File "<my folder>/utils.py", line 14, in evaluate_model
    traced_script_module.save("stgcn_torchscript.pt")
  File "<virtual env path>/lib/python3.6/site-packages/torch/jit/_script.py", line 596, in save
    return self._c.save(str(f), **kwargs)
RuntimeError: 
Could not export Python function call 'GSpMM'. Remove calls to Python functions before export. Did you forget to add @script or @script_method annotation? If this is a nn.ModuleList, add it to __constants__:
<virtual env path>/lib/python3.6/site-packages/dgl/backend/pytorch/sparse.py(502): gspmm
<virtual env path>/lib/python3.6/site-packages/dgl/ops/spmm.py(77): gspmm
<virtual env path>/lib/python3.6/site-packages/dgl/ops/spmm.py(191): func
<virtual env path>/lib/python3.6/site-packages/dgl/core.py(297): invoke_gspmm
<virtual env path>/lib/python3.6/site-packages/dgl/core.py(322): message_passing
<virtual env path>/lib/python3.6/site-packages/dgl/heterograph.py(4849): update_all
<virtual env path>/lib/python3.6/site-packages/dgl/nn/pytorch/conv/graphconv.py(434): forward
<virtual env path>/lib/python3.6/site-packages/torch/nn/modules/module.py(1039): _slow_forward
<virtual env path>/lib/python3.6/site-packages/torch/nn/modules/module.py(1051): _call_impl
<my folder>/model.py(46): forward
<virtual env path>/lib/python3.6/site-packages/torch/nn/modules/module.py(1039): _slow_forward
<virtual env path>/lib/python3.6/site-packages/torch/nn/modules/module.py(1051): _call_impl
<my folder>/model.py(100): forward
<virtual env path>/lib/python3.6/site-packages/torch/nn/modules/module.py(1039): _slow_forward
<virtual env path>/lib/python3.6/site-packages/torch/nn/modules/module.py(1051): _call_impl
<virtual env path>/lib/python3.6/site-packages/torch/jit/_trace.py(959): trace_module
<virtual env path>/lib/python3.6/site-packages/torch/jit/_trace.py(744): trace
<my folder>/utils.py(13): evaluate_model
main.py(117): <module>

```

## Expected behavior

I want to get a torchscript model, then I will run this torchscript model in java. [See this tutorial.](https://docs.djl.ai/jupyter/load_pytorch_model.html#step-1-prepare-your-model)

## Environment

 - dgl-cu102: 0.7.2
 - torch: 1.9.0
 - OS: ubuntu 16.04
 - How you installed DGL (`conda`, `pip`, source): pip
 - Python version: 3.6
 - CUDA/cuDNN version (if applicable): 10.2
 - GPU models and configuration: GeForce GTX 1080

**Comment by BarclayII** [comment]
Currently TorchScript is not supported due to complications in how we handle graphs and features together.  Essentially it requires moving most of the DGLGraph logic into C++ so it will be a long effort.

**Comment by HaoWei-TomTom** [comment]
Thanks for clarification!

**Comment by WalcirC** [comment]
Any progress on Torchscript support? I would like to trace a model but I don't think it's possible yet. 
Thank you.

`
torch.jit.trace(model, (batched_graph, batched_graph.ndata['attr'].float()), 'DGLGraphConv-torchscript.pt')
`
Only tensors and (possibly nested) tuples of tensors, lists, or dictsare supported as inputs or outputs of traced functions, but instead got value of type DGLHeteroGraph.
