### ISSUE TITLE
This error occurs in scripts running multi-GPU node classification

### ISSUE THREAD

**Issue by zhengchu1994** [dmlc/dgl#3534]
I'm trying to run this script  `https://docs.dgl.ai/en/latest/tutorials/multi/2_node_classification.html`
The following error occurs at the end of the run line by line:
last lines:
```python
# Say you have four GPUs.
num_gpus = 2
import dgl.multiprocessing as mp
devices = list(range(num_gpus))
procs = []
for proc_id in range(num_gpus):
    p = mp.Process(target=run, args=(proc_id, devices))
    p.start()
    procs.append(p)
for p in procs:
    p.join()
```
error:

```python
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/dgl/multiprocessing/pytorch.py", line 29, in decorated_function
    raise exception.__class__(trace)
ValueError: Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/dgl/multiprocessing/pytorch.py", line 17, in _queue_result
    res = func(*args, **kwargs)
  File "<ipython-input-5-a5e5a57b015c>", line 31, in run
    num_workers=0       # Number of sampler processes
  File "/usr/local/anaconda3/lib/python3.6/site-packages/dgl/dataloading/pytorch/__init__.py", line 385, in __init__
    **dataloader_kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 231, in __init__
    "sampler option, but got sampler={}".format(sampler))
ValueError: DataLoader with IterableDataset: expected unspecified sampler option, but got sampler=<torch.utils.data.distributed.DistributedSampler object at 0x7f7ebd511860>

Process Process-2:
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/dgl/multiprocessing/pytorch.py", line 29, in decorated_function
    raise exception.__class__(trace)
ValueError: Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/dgl/multiprocessing/pytorch.py", line 17, in _queue_result
    res = func(*args, **kwargs)
  File "<ipython-input-5-a5e5a57b015c>", line 31, in run
    num_workers=0       # Number of sampler processes
  File "/usr/local/anaconda3/lib/python3.6/site-packages/dgl/dataloading/pytorch/__init__.py", line 385, in __init__
    **dataloader_kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 231, in __init__
    "sampler option, but got sampler={}".format(sampler))
ValueError: DataLoader with IterableDataset: expected unspecified sampler option, but got sampler=<torch.utils.data.distributed.DistributedSampler object at 0x7f7ebd511940>
```

my enviroments:
```sh
torch.__version__
'1.8.0'

dgl.__version__
'0.7a210520'

!python3 --version
Python 3.6.8

!nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```

Plus: I used this command to install dgl:
```sh
pip3 install --pre dgl-cu101
```

**Comment by VoVAllen** [comment]
Could you try `pip3 install --pre dgl-cu101 -f https://data.dgl.ai/wheels-test/repo.html`?

**Comment by zhengchu1994** [comment]
> Could you try `pip3 install --pre dgl-cu101 -f https://data.dgl.ai/wheels-test/repo.html`?

Yes, it works.
But it seems to have ended with just one epoch, here is the output:
```python
epoch: epoch:   00

100%|██████████| 45/45 [00:06<00:00,  6.64it/s, loss=2.158, acc=0.446]

proc_id:  0
100%|██████████| 30/30 [00:00<00:00, 32.07it/s]
Epoch 0 Validation Accuracy 0.4733044733044733
```

**Comment by BarclayII** [comment]
The tutorial indeed only runs for one epoch for the sake of tutorial testing.

**Comment by zhengchu1994** [comment]
> The tutorial indeed only runs for one epoch for the sake of tutorial testing.

```python

    # Copied from previous tutorial with changes highlighted.
    for epoch in range(10):
        train_dataloader.set_epoch(epoch)    # <--- necessary for dataloader with DDP.
        model.train()
```
Thank u for your help, but I still don't understand. If the epoch parameter is set to 10, why only run one epoch

**Comment by BarclayII** [comment]
> Thank u for your help, but I still don't understand. If the epoch parameter is set to 10, why only run one epoch

Did you remove the break statement?

**Comment by zhengchu1994** [comment]
> https://docs.dgl.ai/en/latest/tutorials/multi/2_node_classification.html

I see~hhh，thanks so much for helping me, 0_0~
