### ISSUE TITLE
'Tensor' object has no attribute 'local_scope'

### ISSUE THREAD

**Issue by pancccool** [dmlc/dgl#3555]
Traceback (most recent call last):
  File "D:/E/PycharmProjects/GCN/gatAndNewGnn/gat_for_graph_classi_torch_dgl.py", line 411, in <module>
    prediction = model(bg) # 得到模型预测值
  File "D:\E\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:/E/PycharmProjects/GCN/gatAndNewGnn/gat_for_graph_classi_torch_dgl.py", line 333, in forward
    h = gnn(h, bg)
  File "D:\E\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\E\Anaconda3\envs\pytorch\lib\site-packages\dgl\nn\pytorch\conv\gatconv.py", line 246, in forward
    with graph.local_scope():
AttributeError: 'Tensor' object has no attribute 'local_scope'

How to solve this problem?

**Comment by VoVAllen** [comment]
Seem should be `h = gnn(bg, h)` instead of `h = gnn(h, bg)
`

**Comment by pancccool** [comment]
> 似乎应该`h = gnn(bg, h)`代替`h = gnn(h, bg) `

thanks a lot!
When I replace h = gnn(bg, h) with h = gnn(h, bg),the following errors occurred:

Traceback (most recent call last):
  File "D:/E/PycharmProjects/GCN/gatAndNewGnn/gat_for_graph_classi_torch_dgl.py", line 412, in <module>
    prediction = model(bg) 
  File "D:\E\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:/E/PycharmProjects/GCN/gatAndNewGnn/gat_for_graph_classi_torch_dgl.py", line 334, in forward
    h = gnn(bg, h)
  File "D:\E\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\E\Anaconda3\envs\pytorch\lib\site-packages\dgl\nn\pytorch\conv\gatconv.py", line 270, in forward
    feat_src = feat_dst = self.fc(h_src).view(
  File "D:\E\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\E\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\E\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 dim 1 must match mat2 dim 0

I don't know how to check the model where did the dimensions go wrong. 
Each batch has 20 graphs, each graph has 120 nodes, and each node has 120 node features, so my in_dims is set to 120.

**Comment by pancccool** [comment]
> 
h: torch.Size([2400,120])

**Comment by pancccool** [comment]
I am using GNN for the first time and I am not familiar with it

**Comment by jermainewang** [comment]
Could you also give the code of how you initialize your GNN layer?

**Comment by pancccool** [comment]
> 你能否也给出你如何初始化你的 GNN 层的代码？

I checked in detail that the input shape changed in the GNN layer, and after passing through the first layer the shape was [2400,8,16].  
The input dimension of layer 2 GNN is set to [8*16].  
GNN did not help me complete the automatic concatenation. When I manually set the view(bg.num_nodes(), -1), the output of the first layer was changed to [2400,128]. There are no more dimensional errors at this time.
Is it right for me to do this?

**Comment by jermainewang** [comment]
Reshaping or concatenation of node features do not belong to the duty of a GNN layer, so what you've done is totally right.

**Comment by farazBhatti** [comment]
Still getting the same error.
`
<ipython-input-128-670846c0e3e3> in call(self, features)
     25             if i != 0:
     26                 h = self.dropout(h)
---> 27             h = layer(h,self.g)
     28         return tf.keras.activations.sigmoid(h)
     29 

c:\users\faraz\appdata\local\programs\python\python39\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
   1128         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130             return forward_call(*input, **kwargs)
   1131         # Do not call functions when jit is used
   1132         full_backward_hooks, non_full_backward_hooks = [], []

c:\users\faraz\appdata\local\programs\python\python39\lib\site-packages\dgl\nn\pytorch\conv\graphconv.py in forward(self, graph, feat, weight, edge_weight)
    376         * Weight shape: :math:`(\text{in_feats}, \text{out_feats})`.
    377         """
--> 378         with graph.local_scope():
    379             if not self._allow_zero_in_degree:
    380                 if (graph.in_degrees() == 0).any():

AttributeError: 'Graph' object has no attribute 'local_scope'
`

**Comment by Soontosh** [comment]
I've also just gotten this error: https://discuss.dgl.ai/t/attributeerror-tensor-object-has-no-attribute-local-scope/4494
