### ISSUE TITLE
dgl.knn_graph() error on tensorflow

### ISSUE THREAD

**Issue by pancccool** [dmlc/dgl#3623]
x = torch.tensor([[0.0, 0.0, 1.0],
                  [1.0, 0.5, 0.5],
                  [0.5, 0.2, 0.2],
                  [0.3, 0.2, 0.4]])
knn_g = dgl.knn_graph(x, 2)

There is no problem on PyTorch  

But on Tensorflow:
x = tf.constant([[0.0, 0.0, 1.0],
                  [1.0, 0.5, 0.5],
                  [0.5, 0.2, 0.2],
                  [0.3, 0.2, 0.4]])
knn_g = dgl.knn_graph(x, 2)

Traceback (most recent call last):
  File "<input>", line 5, in <module>
  File "D:\E\Anaconda3\envs\tfgpu\lib\site-packages\dgl\transform.py", line 187, in knn_graph
    return _knn_graph_blas(x, k, dist=dist)
  File "D:\E\Anaconda3\envs\tfgpu\lib\site-packages\dgl\transform.py", line 240, in _knn_graph_blas
    dist = pairwise_squared_distance(x)
  File "D:\E\Anaconda3\envs\tfgpu\lib\site-packages\dgl\transform.py", line 67, in pairwise_squared_distance
    return x2s + F.swapaxes(x2s, -1, -2) - 2 * x @ F.swapaxes(x, -1, -2)
  File "D:\E\Anaconda3\envs\tfgpu\lib\site-packages\dgl\backend\tensorflow\tensor.py", line 323, in swapaxes
    return tf.transpose(input, perm=[axis1, axis2])
  File "D:\E\Anaconda3\envs\tfgpu\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "D:\E\Anaconda3\envs\tfgpu\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2135, in transpose_v2
    return transpose(a=a, perm=perm, name=name, conjugate=conjugate)
  File "D:\E\Anaconda3\envs\tfgpu\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "D:\E\Anaconda3\envs\tfgpu\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2216, in transpose
    return transpose_fn(a, perm, name=name)
  File "D:\E\Anaconda3\envs\tfgpu\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 11589, in transpose
    x, perm, name=name, ctx=_ctx)
  File "D:\E\Anaconda3\envs\tfgpu\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 11614, in transpose_eager_fallback
    attrs=_attrs, ctx=ctx, name=name)
  File "D:\E\Anaconda3\envs\tfgpu\lib\site-packages\tensorflow\python\eager\execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError: transpose expects a vector of size 3. But input(1) is a vector of size 2 [Op:Transpose]

I do not understand why this problem occurs. I would appreciate receiving your reply

**Comment by pancccool** [comment]
I do not understand why this problem occurs. I would appreciate receiving your reply

**Comment by VoVAllen** [comment]
Sorry for the inconvenience. I made a fix at https://github.com/dmlc/dgl/pull/3628
