### ISSUE TITLE
New DataLoader is missing `set_epoch()` method

### ISSUE THREAD

**Issue by nv-dlasalle** [dmlc/dgl#3709]
## 🐛 Bug

During the refactoring of #3665, it looks like the Node- and EdgeDataLoader's lost the `set_epoch()` method.

## To Reproduce

1. Install nightly DGL build.
1. Run `/examples/pytorch/rgcn/entity_classify_mp.py` with multiple GPUs.
1. This results in:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/multiprocessing/pytorch.py", line 29, in decorated_function
    raise exception.__class__(trace)
AttributeError: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/dgl-0.8-py3.8-linux-x86_64.egg/dgl/multiprocessing/pytorch.py", line 17, in _queue_result
    res = func(*args, **kwargs)
  File "entity_classify_mp.py", line 299, in run
    loader.set_epoch(epoch)
AttributeError: 'NodeDataLoader' object has no attribute 'set_epoch'
```

## Expected behavior

`set_epoch()` should create permutation for the training ids.

## Environment

 - DGL Version (e.g., 1.0): 0.8.x
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.9.1
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `cmake -DCMAKE_BUILD_TYPE=Release -DUSE_CUDA=ON -DUSE_NCCL=ON -DBUILD_TORCH=ON .. && make -j`
 - Python version: 3.8
 - CUDA/cuDNN version (if applicable): 11.3
 - GPU models and configuration (e.g. V100): NVIDIA V100 SXM2 16GB
 - Any other relevant information:

**Comment by BarclayII** [comment]
`set_epoch` method is no longer needed for `NodeDataLoader` and `EdgeDataLoader`.  Its previous existence is to make it compatible with PyTorch's `DistributedSampler` which has a `set_epoch` method for cross-worker shuffling.  I removed it since the new DDP sampler has its own shuffling strategy (shuffle on only one worker with shared memory) so it's no longer necessary.

**Comment by nv-dlasalle** [comment]
Thanks, I missed that.
