### ISSUE TITLE
Working on hetero link prediction with your han example. error: AttributeError: 'list' object has no attribute 'adj'

### ISSUE THREAD

**Issue by Jeriousman** [dmlc/dgl#3739]
I have been modifying your han example (hetero node classification task) to hetero link prediction task. I have been doing okay I guess until I reached this problem. When I do the below, every thing works except for the last line ```  pos_score, neg_score = model(positive_graph, negative_graph, blocks, input_features) ```

```


    for input_nodes, positive_graph, negative_graph, blocks in train_dataloader:
        blocks = [b.to(torch.device('cuda')) for b in blocks]
        positive_graph = positive_graph.to(torch.device('cuda'))
        negative_graph = negative_graph.to(torch.device('cuda'))
        input_features = blocks[0].srcdata['h']
        pos_score, neg_score = model(positive_graph, negative_graph, blocks, input_features)
```

This gives me an error as below:
```
Traceback (most recent call last):

  File "<ipython-input-5-ce6e71fad59f>", line 8, in <module>
    pos_score, neg_score = model(positive_graph, negative_graph, blocks, input_features)

  File "/home/hojun/anaconda3/envs/dgl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "/home/hojun/Python/Models/Recommender_systems/GNN/dgl-master/examples/pytorch/!linkpred_or_hetero/han_linkpred_hojun/model_hetero.py", line 278, in forward
    h = gnn(blocks, h)

  File "/home/hojun/anaconda3/envs/dgl/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "/home/hojun/Python/Models/Recommender_systems/GNN/dgl-master/examples/pytorch/!linkpred_or_hetero/han_linkpred_hojun/model_hetero.py", line 139, in forward
    g, meta_path)

  File "/home/hojun/anaconda3/envs/dgl/lib/python3.6/site-packages/dgl/transform.py", line 1344, in metapath_reachable_graph
    adj = adj * g.adj(etype=etype, scipy_fmt='csr', transpose=False)

AttributeError: 'list' object has no attribute 'adj'
```

It seems that it has something to do with metapath_reachable_graph acting differently compared to 'normal' subgraph. meta_paths is set ```meta_paths=[['pa', 'ap'], ['pf', 'fp']]``` as the same as original han node classification problem.
If possible, can you please give me how to fix this?

**Comment by hojun0705** [comment]
Let me write information about input_features, positive_graph, negative_graph, blocks and model.

```
positive_graph
Out[10]: 
Graph(num_nodes={'author': 760, 'field': 60, 'paper': 888},
      num_edges={('author', 'ap', 'paper'): 191, ('field', 'fp', 'paper'): 54, ('paper', 'pa', 'author'): 205, ('paper', 'pf', 'field'): 62},
      metagraph=[('author', 'paper', 'ap'), ('paper', 'author', 'pa'), ('paper', 'field', 'pf'), ('field', 'paper', 'fp')])
```

```
negative_graph
Out[11]: 
Graph(num_nodes={'author': 760, 'field': 60, 'paper': 888},
      num_edges={('author', 'ap', 'paper'): 382, ('field', 'fp', 'paper'): 108, ('paper', 'pa', 'author'): 410, ('paper', 'pf', 'field'): 124},
      metagraph=[('author', 'paper', 'ap'), ('paper', 'author', 'pa'), ('paper', 'field', 'pf'), ('field', 'paper', 'fp')])
```

```
blocks
Out[12]: 
[Block(num_src_nodes={'author': 7328, 'field': 69, 'paper': 4022},
       num_dst_nodes={'author': 2798, 'field': 66, 'paper': 3971},
       num_edges={('author', 'ap', 'paper'): 13259, ('field', 'fp', 'paper'): 3971, ('paper', 'pa', 'author'): 7434, ('paper', 'pf', 'field'): 4015},
       metagraph=[('author', 'paper', 'ap'), ('paper', 'author', 'pa'), ('paper', 'field', 'pf'), ('field', 'paper', 'fp')]),
 Block(num_src_nodes={'author': 2798, 'field': 66, 'paper': 3971},
       num_dst_nodes={'author': 760, 'field': 60, 'paper': 888},
       num_edges={('author', 'ap', 'paper'): 3273, ('field', 'fp', 'paper'): 888, ('paper', 'pa', 'author'): 2097, ('paper', 'pf', 'field'): 3933},
       metagraph=[('author', 'paper', 'ap'), ('paper', 'author', 'pa'), ('paper', 'field', 'pf'), ('field', 'paper', 'fp')])]
```

```
input_features
Out[13]: 
{'paper': tensor([[0., 1., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.]], device='cuda:0')}
```

```
#model



class HAN(nn.Module):
    def __init__(self, meta_paths, in_size, hidden_size, num_heads, dropout):
        super(HAN, self).__init__()

        self.layers = nn.ModuleList()  
        self.layers.append(HANLayer(meta_paths, in_size, hidden_size, num_heads[0], dropout))
        for l in range(1, len(num_heads)):  
            self.layers.append(HANLayer(meta_paths, hidden_size * num_heads[l-1],
                                        hidden_size, num_heads[l], dropout))
        self.edgepredict = ScorePredictor()
        # self.predict = nn.Linear(hidden_size * num_heads[-1], out_size)

    def forward(self, pos_g, neg_g, blocks, h):
        for gnn in self.layers:
            h = gnn(blocks, h)

        
        pos_score = self.edgepredict(pos_g, h)
        neg_score = self.edgepredict(neg_g, h)

        return pos_score, neg_score
```

**Comment by VoVAllen** [comment]
Could you provide a reproducible code snippet for us to take a look?
