### ISSUE TITLE
Getting error message from dgl.dataloading.NodeDataLoader when use_uva=True

### ISSUE THREAD

**Issue by oyilmaz-nvidia** [dmlc/dgl#3961]
Hi,

I followed the code examples for UVA and I am getting the following error when I set the `use_uva=True`. When `use_uva=False`, I don't get any error.

I am using the RGCN model with these parameters;

model = RGCN(
        dim_hidden=40,
        dim_out=349,
        n_layers=1,
        num_bases=-1,
    )

Param names might not exactly match with the one in the upstream examples but it should be easy to understand. For the data loader, I use 1024 as batch size and the fanout sizes are 50 for both 2 layers.

```       torch.multiprocessing.spawn.ProcessRaisedException: 
    
       -- Process 0 terminated with the following error:
       Traceback (most recent call last):
        File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
           fn(i, *args)
         File "/workspace/gp/workflow/trainers/utils.py", line 10, in run
           trainer.fit_process(rank)
         File "/workspace/gp/workflow/trainers/trainer.py", line 108, in fit_process
          self.setup(rank)
         File "/workspace/gp/workflow/trainers/trainer.py", line 157, in setup
           self.data_object.build_train_dataloader_post_dist(device, use_ddp)
         File "/workspace/gp/data_loaders/node_data_object.py", line 157, in build_train_dataloader_post_dist
           self.train_dataloader = make_dgl_loader(
         File "/workspace/gp/data_loaders/node_data_object.py", line 72, in make_dgl_loader
          loader = dgl.dataloading.NodeDataLoader(
         File "/opt/conda/lib/python3.8/site-packages/dgl-0.8.0.post2-py3.8-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 809, in __init__
           self.dataset = create_tensorized_dataset(
         File "/opt/conda/lib/python3.8/site-packages/dgl-0.8.0.post2-py3.8-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 542, in create_tensorized_dataset
           return DDPTensorizedDataset(indices, batch_size, drop_last, ddp_seed)
         File "/opt/conda/lib/python3.8/site-packages/dgl-0.8.0.post2-py3.8-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 192, in __init__
           self._id_tensor = call_once_and_share(
         File "/opt/conda/lib/python3.8/site-packages/dgl-0.8.0.post2-py3.8-linux-x86_64.egg/dgl/multiprocessing/pytorch.py", line 77, in call_once_and_share
           result[:] = func()
         File "/opt/conda/lib/python3.8/site-packages/dgl-0.8.0.post2-py3.8-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 193, in <lambda>
           lambda: _get_id_tensor_from_mapping(indices, self._device, self._mapping_keys),
         File "/opt/conda/lib/python3.8/site-packages/dgl-0.8.0.post2-py3.8-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 89, in _get_id_tensor_from_mapping
          id_tensor = torch.empty(
      RuntimeError: CUDA error: resource already mapped

/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py:160: ProcessRaisedException```

Any suggestion?

**Comment by nv-dlasalle** [comment]
This looks to be the same/similar cause as  #3939.
