### ISSUE TITLE
Error on running examples/pytorch/graphsage/node_classification.py

### ISSUE THREAD

**Issue by TristonC** [dmlc/dgl#3999]
## 🐛 Bug
```bash
Traceback (most recent call last):
  File "node_classification.py", line 131, in <module>
    acc = MF.accuracy(pred, label)
  File "/opt/conda/lib/python3.8/site-packages/torchmetrics/functional/classification/accuracy.py", line 417, in accuracy
    tp, fp, tn, fn = _accuracy_update(
  File "/opt/conda/lib/python3.8/site-packages/torchmetrics/functional/classification/accuracy.py", line 107, in _accuracy_update
    tp, fp, tn, fn = _stat_scores_update(
  File "/opt/conda/lib/python3.8/site-packages/torchmetrics/functional/classification/stat_scores.py", line 184, in _stat_scores_update
    tp, fp, tn, fn = _stat_scores(preds, target, reduce=reduce)
  File "/opt/conda/lib/python3.8/site-packages/torchmetrics/functional/classification/stat_scores.py", line 98, in _stat_scores
    true_pred, false_pred = target == preds, target != preds
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
## To Reproduce
Run the node node_classification.py on a GPU enabled environment
python3  examples/pytorch/graphsage/node_classification.py

## Environment

 - DGL Version (e.g., 1.0): 0.9
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.12
 - OS (e.g., Linux): Ubuntu
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): 
 - Python version: 3.8.13
 - CUDA/cuDNN version (if applicable): 11.7
 - GPU models and configuration (e.g. V100): V100
 - Any other relevant information: torchmetrics version: 0.8.2

**Comment by TristonC** [comment]
PR 4016 fixes this issue. I will close this once it is merged.
