### ISSUE TITLE
DGL's distributed training cannot handle distributed bipartite graphs

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#4000]
## 🐛 Bug

When DGL runs on a distributed bipartite graph with one relation type, it reports the error below.

```
Traceback (most recent call last):
  File "m5gnn_lp_huggingface.py", line 27, in <module>
    main(args)
  File "m5gnn_lp_huggingface.py", line 17, in main
    trainer.fit()
  File "/m5-gnn/python/m5gnn/trainer/lp_trainer.py", line 142, in fit
    lp_model.fit(dataloader)
  File "/m5-gnn/python/m5gnn/model/rgcn_lp_base.py", line 164, in fit
    for i, (input_nodes, pos_graph, neg_graph, blocks) in enumerate(loader):
  File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/dist_dataloader.py", line 108, in __next__
    self._request_next_batch()
  File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/dist_dataloader.py", line 140, in _request_next_batch
    result = self.collate_fn(next_data)
  File "/usr/local/lib/python3.8/dist-packages/dgl/_dataloading/dataloader.py", line 897, in collate
    return self._collate_with_negative_sampling(items)
  File "/usr/local/lib/python3.8/dist-packages/dgl/_dataloading/dataloader.py", line 853, in _collate_with_negative_sampling
    input_nodes, _, blocks = self.graph_sampler.sample_blocks(
  File "/usr/local/lib/python3.8/dist-packages/dgl/dataloading/neighbor_sampler.py", line 110, in sample_blocks
    frontier = g.sample_neighbors(
  File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/dist_graph.py", line 1254, in sample_neighbors
    frontier = graph_services.sample_neighbors(
  File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/graph_services.py", line 574, in sample_neighbors
    assert len(nodes) == 1
```
The reason that this error happens is that the code checks the number of relation types to determine if a graph is a homogeneous graph. The code handles a bipartite graph with one relation type as a homogeneous graph, which results in this error.

**Comment by Rhett-Ying** [comment]
Is this your case? a nodes dict whose `len(nodes) > 1` is passed in?
```
g=dgl.rand_bipartite('user', 'buys', 'game', 500, 1000, 100)
partition_graph(g)
gpb = load_partition()
dist_graph=DistGraph("test", gpb)
_ = dgl.distributed.sample_neighbors(dist_graph, nodes={'game':[1,2,3], 'user':[1,2,3]})
```

**Comment by zheng-da** [comment]
yes, this is the case.

**Comment by Rhett-Ying** [comment]
fixed
