### ISSUE TITLE
raise DGLError(py_str(_LIB.DGLGetLastError())) cudaErrorInvalidDevice in DGLGraph.to() to copy the graph to gpu 1

### ISSUE THREAD

**Issue by LukeLIN-web** [dmlc/dgl#4006]
```
python 3.6.9
tensorflow:2.2.2
CUDA Version 10.1.243
```

my codes is
```
g = data[0]
    if args.gpu < 0:
        device = "/cpu:0"
    else:
        device = "/gpu:1"
        g = g.to(device)
```
The error is :

```
/gpu:1
Traceback (most recent call last):
  File "/root/share/orion-perf/examples/tensorflow/node_classification/v2.2/main_gat.py", line 4, in <module>
    run_gat.run()
  File "/root/share/orion-perf/examples/tensorflow/node_classification/common/run_gat.py", line 127, in run
    g = g.to(device)
  File "/usr/local/lib/python3.6/dist-packages/dgl/heterograph.py", line 5192, in to
    ret._graph = self._graph.copy_to(utils.to_dgl_context(device))
  File "/usr/local/lib/python3.6/dist-packages/dgl/heterograph_index.py", line 234, in copy_to
    return _CAPI_DGLHeteroCopyTo(self, ctx.device_type, ctx.device_id)
  File "/usr/local/lib/python3.6/dist-packages/dgl/_ffi/_ctypes/function.py", line 190, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/usr/local/lib/python3.6/dist-packages/dgl/_ffi/base.py", line 64, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: [06:35:06] /opt/dgl/src/runtime/cuda/cuda_device_api.cc:93: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: cudaErrorInvalidDevice
Stack trace:
  [bt] (0) /usr/local/lib/python3.6/dist-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4f) [0x7f8889d8901f]
  [bt] (1) /usr/local/lib/python3.6/dist-packages/dgl/libdgl.so(dgl::runtime::CUDADeviceAPI::AllocDataSpace(DLContext, unsigned long, unsigned long, DLDataType)+0x283) [0x7f888a5ed863]
  [bt] (2) /usr/local/lib/python3.6/dist-packages/dgl/libdgl.so(dgl::runtime::NDArray::Empty(std::vector<long, std::allocator<long> >, DLDataType, DLContext)+0x351) [0x7f888a4a9361]
```

**Comment by Rhett-Ying** [comment]
pls refer to https://discuss.dgl.ai/t/cudaerrorinvaliddevice-in-dglgraph-to-to-copy-the-graph-to-gpu-1/2943/2.

**Comment by Sakura-del** [comment]
I have the same problem, have you solved it? And how did you solve it?

**Comment by LukeLIN-web** [comment]
> I have the same problem, have you solved it? And how did you solve it?

pls try with g.to('/gpu:0').
