### ISSUE TITLE
Heterogeneous Graph Classification

### ISSUE THREAD

**Issue by ysgncss** [dmlc/dgl#4094]
Some edges in a heterogeneous graph are empty. When using Han or HGT for training, an error will be reported that such edges are not included. What should I do?

D:\software\Anaconda3\envs\torch-1.10+dgl-0.8.2\lib\site-packages\dgl\core.py:79: DGLWarning: The input graph for the user-defined edge function does not contain valid edges
  dgl_warning('The input graph for the user-defined edge function ' \
Traceback (most recent call last):
  File "D:/workspace/pycharm/Cross-Word-Concept/train.py", line 309, in <module>
    main(args)
  File "D:/workspace/pycharm/Cross-Word-Concept/train.py", line 203, in main
    logits = model(g)
  File "D:\software\Anaconda3\envs\torch-1.10+dgl-0.8.2\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\workspace\pycharm\Cross-Word-Concept\HGTClassifier.py", line 54, in forward
    h = self.gcs[i](G, h)
  File "D:\software\Anaconda3\envs\torch-1.10+dgl-0.8.2\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\workspace\pycharm\Cross-Word-Concept\HGTClassifier.py", line 160, in forward
    G.apply_edges(func=self.edge_attention, etype=etype)
  File "D:\software\Anaconda3\envs\torch-1.10+dgl-0.8.2\lib\site-packages\dgl\heterograph.py", line 4461, in apply_edges
    edata = core.invoke_edge_udf(g, eid, etype, func)
  File "D:\software\Anaconda3\envs\torch-1.10+dgl-0.8.2\lib\site-packages\dgl\core.py", line 85, in invoke_edge_udf
    return func(ebatch)
  File "D:\workspace\pycharm\Cross-Word-Concept\HGTClassifier.py", line 117, in edge_attention
    etype = edges.data['id'][0]
IndexError: index 0 is out of bounds for dimension 0 with size 0

**Comment by jermainewang** [comment]
Could you provide more details (e.g., which scripts are you running? your DGL version). If you are reporting a bug, using the Bug Report issue template will make it easier for us to follow.
