### ISSUE TITLE
adjacency matrix

### ISSUE THREAD

**Issue by DuanhaoranCC** [dmlc/dgl#4121]
I need to convert a large graph into an adjacency matrix, but the following error is reported. I want to ask if there is any way to solve it.
```python
adj = dgl.khop_adj(graph, 1).numpy()
```

```linux
a = dgl.khop_adj(graph, 1).numpy()
  File "/home/kglab/.conda/envs/kg/lib/python3.8/site-packages/dgl/transforms/functional.py", line 996, in khop_adj
    return F.tensor(adj_k.todense().astype(np.float32))
  File "/home/kglab/.conda/envs/kg/lib/python3.8/site-packages/scipy/sparse/base.py", line 864, in todense
    return asmatrix(self.toarray(order=order, out=out))
  File "/home/kglab/.conda/envs/kg/lib/python3.8/site-packages/scipy/sparse/coo.py", line 321, in toarray
    B = self._process_toarray_args(order, out)
  File "/home/kglab/.conda/envs/kg/lib/python3.8/site-packages/scipy/sparse/base.py", line 1202, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
numpy.core._exceptions.MemoryError: Unable to allocate 214. GiB for an array with shape (169343, 169343) and data type int64
```

**Comment by TristonC** [comment]
Do you need adj maxtrix in dense with datatype float32? There is  adj_sparse function with different sparse format.

**Comment by DuanhaoranCC** [comment]
Hello, I modified the code, I don't need to obtain the adjacency matrix, I use the PageRank propagation algorithm to indirectly obtain the diffusion matrix on the large image, but the following error is reported, do you have any suggestions?
'''python
def process_dataset_appnp(epsilon):
    k = 20
    alpha = 0.2
    dataset = DglNodePropPredDataset(name='ogbn-arxiv', root='./')
    graph, labels = dataset[0]
    appnp = APPNPConv(k, alpha)
    id = th.eye(graph.number_of_nodes()).float()
    diff_adj = appnp(graph.add_self_loop(), id).numpy()

process_dataset_appnp(0.01)
```
```linux
Data(num_nodes=169343, edge_index=[2, 2315598], x=[169343, 128], node_year=[169343, 1], y=[169343, 1])
Traceback (most recent call last):
  File "1.py", line 209, in <module>
    process_dataset_appnp(0.01)
  File "1.py", line 199, in process_dataset_appnp
    diff_adj = appnp(x=id, edge_index=data.edge_index)
  File "/home/kglab/.conda/envs/kg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kglab/.conda/envs/kg/lib/python3.8/site-packages/torch_geometric/nn/conv/appnp.py", line 118, in forward
    x = self.propagate(edge_index, x=x, edge_weight=edge_weight,
  File "/home/kglab/.conda/envs/kg/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 309, in propagate
    coll_dict = self.__collect__(self.__user_args__, edge_index,
  File "/home/kglab/.conda/envs/kg/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 202, in __collect__
    data = self.__lift__(data, edge_index, dim)
  File "/home/kglab/.conda/envs/kg/lib/python3.8/site-packages/torch_geometric/nn/conv/message_passing.py", line 172, in __lift__
    return src.index_select(self.node_dim, index)
RuntimeError: [enforce fail at alloc_cpu.cpp:73] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 1683229455052 bytes. Error code 12 (Cannot allocate memory)
```

**Comment by mufeili** [comment]
It's probably just that your graph is too large. There might be some fast approximate PageRank or Personalized PageRank implementations that can handle your graph.

**Comment by DuanhaoranCC** [comment]
Yes, Thank you!
