### ISSUE TITLE
[Bug] Calling `IsPinned()` in a worker process results in RuntimeError: CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by nv-dlasalle** [dmlc/dgl#4134]
## 🐛 Bug

This is caused by `IsPinned()` relying on invoking the cuda context, which is not valid in forked processes, and is the reason #3997 was generating errors.

This is tricky to address because both of the following scenarios are valid:

1. The main process initializes a cuda context, but the worker processes in the dataloader never interact with the cuda context.
1. The main process does not initialize a cuda context before spawning workers, but instead the worker processes each initialize a cuda context.

## To Reproduce

1. Initialize a cuda context (e.g., call .cuda() on a model).
1. Use a dataloader with number of workers > 0.
1. Cause `IsPinned()` to be called from one of the workers.

```
dominique@dominique-X299-A:~/src/dgl/examples/pytorch/graphsage$ python3 node_classification.py
num_tasks = 1
task_type = multiclass classification
eval_metric = acc
num_classes = 47
is_hetero = False
Traceback (most recent call last):
  File "node_classification.py", line 96, in <module>
    for it, (input_nodes, output_nodes, blocks) in enumerate(train_dataloader):
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 501, in __next__
    self._next_non_threaded() if not self.use_thread else self._next_threaded()
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 496, in _next_threaded
    exception.reraise()
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/utils/exception.py", line 57, in reraise
    raise exception
RuntimeError: Caught RuntimeError in prefetcher.
Original Traceback (most recent call last):
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 355, in _prefetcher_entry
    feats = _prefetch(batch, dataloader, stream)
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 306, in _prefetch
    feats = recursive_apply(batch, _prefetch_for, dataloader)
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/utils/internal.py", line 996, in recursive_apply
    return [recursive_apply(v, fn, *args, **kwargs) for v in data]
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/utils/internal.py", line 996, in <listcomp>
    return [recursive_apply(v, fn, *args, **kwargs) for v in data]
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/utils/internal.py", line 996, in recursive_apply
    return [recursive_apply(v, fn, *args, **kwargs) for v in data]
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/utils/internal.py", line 996, in <listcomp>
    return [recursive_apply(v, fn, *args, **kwargs) for v in data]
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/utils/internal.py", line 998, in recursive_apply
    return fn(data, *args, **kwargs)
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 276, in _prefetch_for
    return _prefetch_for_subgraph(item, dataloader)
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 267, in _prefetch_for_subgraph
    NID, dataloader.device, dataloader.pin_prefetcher)
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/dataloading/dataloader.py", line 251, in _prefetch_update_feats
    column.id_ or default_id, device, pin_prefetcher)
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/frame.py", line 439, in fetch
    return super().fetch(indices, device, pin_memory=False, **kwargs)
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/storages/pytorch_tensor.py", line 40, in fetch
    pin_memory, **kwargs)
  File "/home/dominique/.local/lib/python3.6/site-packages/dgl-0.9-py3.6-linux-x86_64.egg/dgl/storages/pytorch_tensor.py", line 14, in _fetch_cpu
    result = result.to(device, **kwargs)
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

One possible solution is to call `torch.multiprocessing.set_start_method("spawn")` from inside of our dataloader, but I'm unsure of what the side effects of this may be on the worker processes.

**Comment by yaox12** [comment]
I had a discussion with @BarclayII and @jermainewang and we thought maintaining a flag `pinned_by_dgl` inside C++ `NDArray` objects could help.  But in the following example,
```python
def pin_memory_inplace(tensor):
    F.zerocopy_to_dgl_ndarray_for_write(tensor).pin_memory_()
```
the temporary Python `NDArray` object will be freed when this function ends. If we unpin the underlying C++ DLTensor by checking the `pinned_by_dgl` flag, the above function will immediately unpin the tensor after returning.

So I tried to combine the `pinned_by_dgl` flag and `from_tensor_dispatcher` flag you introduced in #3997 to prevent unpinning these temporary NDArrays and avoid calling `IsPinned()` by irrelavent tensors. But in a more complicated case,
```python
t = F.zerocopy_from_dlpack(dgl.ndarray.empty(
        [10000, 10],
        F.reverse_data_type_dict[F.float32],
        ctx=dgl.utils.to_dgl_context(torch.device('cpu'))).to_dlpack()).zero_()
dgl.utils.pin_memory_inplace(t)
```
there are two Python `NDArray` objects: the first one is `nd1` created by `dgl.ndarray.empty()` while the second one is `nd2` temporarily created inside `dgl.utils.pin_memory_inplace()`. Interesting thing is that `nd1` will carry the flag `from_tensor_dispatcher` while `nd2` will carry the flag `pinned_by_dgl`, so neither of them will be unpinned automatically.

My suggestion is when you need a tensor that will be automatically unpinned, e.g., in #3885, use `dgl.ndarray` and pin it via `nd.pin_memory_()` instead of converting it to a PyTorch tensor and pinning it via `pin_memory_inplace`. The following example should work:
```python
for j in range(10):
    nd = dgl.ndarray.empty(
        [10000, 10],
        F.reverse_data_type_dict[F.float32],
        ctx=dgl.utils.to_dgl_context(torch.device('cpu')))
    t = F.zerocopy_from_dlpack(nd.to_dlpack()).zero_()
    assert not F.is_pinned(t)
    # dgl.utils.pin_memory_inplace(t)
    nd.pin_memory_()
    assert F.is_pinned(t)
    del t
```
For PyTorch tensors, we still need to unpin them manually.

**Comment by jermainewang** [comment]
@yaox12 for the issue of temporary object, we could save the `NDArray` reference as the attribute of `DataLoader`:
```python
class DataLoader:
    def __init__(self, g, ...):
        self.pinned_ndata = {key: F.to_dgl_nd(g.ndata[key]) for key in g.ndata}  # dict[str, NDArray]
        for _, array in self.pinned_ndata.items():
            array.pin_memory_()    # inplace pin
```

Holding this reference has two effects:
* It prevents PyTorch to free/recycle the memory before the `DataLoader` object is destroyed.
* As long as DGL `NDArray` will unpin its data upon destruction, it ensures that unpin happens before PyTorch free/recycle the memory.

**Comment by BarclayII** [comment]
@jermainewang We are aware of this solution, though it's very tricky to understand, and does not work with functions unless you also return the DGL NDArray and keep it somewhere else.

**Comment by yaox12** [comment]
Since #4135 is merged, I'd close this issue.
