### ISSUE TITLE
Neighbor Sampling for Node Classification IndexSelectSingleKernel Assertion Failed. 

### ISSUE THREAD

**Issue by bwagley** [dmlc/dgl#4173]
I am working on a project that builds on DGL's neighbor sampler and have run into an issue when trying to train the model. To reproduce the issue, I have found that running the [L1_large_node_classification.py](https://docs.dgl.ai/en/latest/tutorials/large/L1_large_node_classification.html) from the docs with `device = 'cuda'` will cause the error. For testing I have otherwise left the example the same.  The NeighborSampler is created successfully, but once the training loop starts I get an error: 
```dgl/src/array/cuda/uvm/../array_index_select.cuh:23: void dgl::aten::impl::IndexSelectSingleKernel(const DType *, const IdType *, signed long, signed long, DType *) [with DType = signed long; IdType = signed long]: block: [0,0,0], thread: [735,0,0] Assertion `index[tx] >= 0 && index[tx] < arr_len` failed.```

This error occurs on various blocks and threads, with probably about 100 errors printing before the program aborts. Since the error is essentially the same and just on different threads I have only included one example. 

I am using the pytorch backend with pytorch 1.13,  dgl 0.9 (commit e06e63d5d578d0ef7af1d112d44228109de38a1b), and cuda 11.1.

**Comment by Rhett-Ying** [comment]
could you try with latest DGL nightly build? I tried with `dgl-cu102 0.9a220622` and `torch1.10.1+cu102`, it works well. BTW, you're using pytorch 1.13?

**Comment by bwagley** [comment]
With testing with the latest DGL nightly build I get a different error, `CUDA: invalid configuration argument`. 
Here is the stack trace and traceback:
```
    Traceback (most recent call last):
  File "ogb_orig.py", line 294, in <module>
    predictions = model(mfgs, inputs)
  File "/home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "ogb_orig.py", line 193, in forward
    h = self.conv1(mfgs[0], (x, h_dst))  # <---
  File "/home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/nn/pytorch/conv/sageconv.py", line 235, in forward
    graph.update_all(msg_fn, fn.mean('m', 'neigh'))
  File "/home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/heterograph.py", line 4895, in update_all
    ndata = core.message_passing(g, message_func, reduce_func, apply_node_func)
  File "/home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/core.py", line 357, in message_passing
    ndata = invoke_gspmm(g, mfunc, rfunc)
  File "/home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/core.py", line 332, in invoke_gspmm
    z = op(graph, x)
  File "/home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/ops/spmm.py", line 189, in func
    return gspmm(g, 'copy_lhs', reduce_op, x, None)
  File "/home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/ops/spmm.py", line 75, in gspmm
    ret = gspmm_internal(g._graph, op,
  File "/home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/backend/pytorch/sparse.py", line 737, in gspmm
    return GSpMM.apply(gidx, op, reduce_op, lhs_data, rhs_data)
  File "/home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 118, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/backend/pytorch/sparse.py", line 106, in forward
    out, (argX, argY) = _gspmm(gidx, op, reduce_op, X, Y)
  File "/home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/sparse.py", line 228, in _gspmm
    _CAPI_DGLKernelSpMM(gidx, op, reduce_op,
  File "/home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/_ffi/_ctypes/function.py", line 188, in __call__
    check_call(_LIB.DGLFuncCall(
  File "/home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/_ffi/base.py", line 65, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: [10:38:41] /home/bwagley/dgl/dgl/src/array/cuda/array_sort.cu:41: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: invalid configuration argument
Stack trace:
  [bt] (0) /home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x52) [0x7f9ad47e227a]
  [bt] (1) /home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/libdgl.so(std::pair<dgl::runtime::NDArray, dgl::runtime::NDArray> dgl::aten::impl::Sort<(DLDeviceType)2, long>(dgl::runtime::NDArray, int)+0x2c0) [0x7f9ad4eea870]
  [bt] (2) /home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/libdgl.so(dgl::aten::Sort(dgl::runtime::NDArray, int)+0x505) [0x7f9ad47c0454]
  [bt] (3) /home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/libdgl.so(void dgl::aten::impl::COOSort_<(DLDeviceType)2, long>(dgl::aten::COOMatrix*, bool)+0x3a4) [0x7f9ad4eeda34]
  [bt] (4) /home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/libdgl.so(dgl::aten::COOSort_(dgl::aten::COOMatrix*, bool)+0x3af) [0x7f9ad47d5fc2]
  [bt] (5) /home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/libdgl.so(dgl::aten::COOSort(dgl::aten::COOMatrix, bool)+0x201) [0x7f9ad47e5c15]
  [bt] (6) /home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/libdgl.so(dgl::aten::CSRMatrix dgl::aten::impl::COOToCSR<(DLDeviceType)2, long>(dgl::aten::COOMatrix)+0xc6) [0x7f9ad4eeb526]
  [bt] (7) /home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/libdgl.so(dgl::aten::COOToCSR(dgl::aten::COOMatrix)+0x4c3) [0x7f9ad47d4bd7]
  [bt] (8) /home/bwagley/anaconda3/envs/dgl_devel/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/libdgl.so(dgl::UnitGraph::GetInCSR(bool) const+0x1ac) [0x7f9ad4e4195a]
```

When I run the example with `device = 'cpu'` it runs normally. 

I had been using a nightly pytorch build but since I didn't need it, for simplicity I have changed my environment to use pytorch 1.12 (Changing the pytorch version has had no effect on the errors). This is still all using cuda 11.1 on Ubuntu 20.04.

**Comment by Rhett-Ying** [comment]
I tried to build latest DGL with cuda11.1 on ubuntu18.04 and it works well. My torch is `1.10.1+cu102`. What's the cuda version of your pytorch? Could you try to build DGL on your own by referring to https://docs.dgl.ai/install/index.html#install-from-source?

**Comment by Rhett-Ying** [comment]
could you also try to change torch version? torch1.12 does not provide a build for cuda 11.1.

**Comment by bwagley** [comment]
It worked with torch 1.10! Thanks for the help.
