### ISSUE TITLE
[Example][Bug] Running error on the example case: example/pytorch/eges

### ISSUE THREAD

**Issue by chang-l** [dmlc/dgl#4205]
## 🐛 Bug

DGL implementation of Enhanced Graph Embedding with Side information (EGES) is crashed. Might be due to bug(s) in the script.

## To Reproduce

`python main.py`

```
Traceback (most recent call last):
  File "main.py", line 79, in <module>
    g, sku_encoder, sku_decoder = utils.construct_graph(
  File "/workspace/examples/eges/utils.py", line 56, in construct_graph
    g = convert_to_dgl_graph(graph)
  File "/workspace/examples/eges/utils.py", line 69, in convert_to_dgl_graph
    return dgl.from_networkx(g, edge_attrs=['weight'])
  File "/opt/conda/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/convert.py", line 1345, in from_networkx
    g.edata[attr] = F.copy_to(_batcher(attr_dict[attr]), g.device)
  File "/opt/conda/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/convert.py", line 1307, in _batcher
    if F.is_tensor(lst[0]):
IndexError: list index out of range
```

## Expected behavior

The case should run through

## Environment

 - DGL Version (e.g., 1.0): 0.9
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 1.12
 - OS (e.g., Linux): ubuntu
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version (if applicable): 11.7
 - GPU models and configuration (e.g. V100): A100
 - Any other relevant information:

**Comment by chang-l** [comment]
It turns out that the code is fine and this case can run through.

Originally, my data was not downloaded in raw format, which causes the issue. I have opened a PR for updating the README file to make it more specific.
