### ISSUE TITLE
[DistDGL] Bug in DistGraphServer with disable_shared_mem=True

### ISSUE THREAD

**Issue by Kh4L** [dmlc/dgl#4206]
## 🐛 Bug

In the context of DistDGL, using `DistGraphServer` with `server_count` > 1 (more than one server per machine) means that one `DistGraphServer` is the main and the other servers are backup servers, that doesn't own the graph but access it through shared memory.

However, if shared memory is disabled with `disable_shared_mem`, the back up server yields this error:

```
Traceback (most recent call last):
  File "repro.py", line 49, in <module>
    run_server()
  File "repro.py", line 32, in run_server
    g.start()
  File "/opt/conda/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/distributed/dist_graph.py", line 380, in start
    start_server(server_id=self.server_id,
  File "/opt/conda/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/distributed/rpc_server.py", line 122, in start_server
    res = req.process_request(server_state)
  File "/opt/conda/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/distributed/graph_services.py", line 215, in process_request
    global_src, global_dst = _find_edges(local_g, partition_book, self.edge_ids)
  File "/opt/conda/lib/python3.8/site-packages/dgl-0.9-py3.8-linux-x86_64.egg/dgl/distributed/graph_services.py", line 102, in _find_edges
    local_eids = F.astype(local_eids, local_g.idtype)
AttributeError: 'NoneType' object has no attribute 'idtype'
```

This is due to `local_g` being never initialized on the back up servers.
We need to either enforce `not disable_shared_mem or server_count == 1` or handle the case.

https://github.com/dmlc/dgl/blob/0f0e7c7fad6ec1399a67881ce9a7e60d14cfe1a0/python/dgl/distributed/dist_graph.py#L331

This comment suggests that the back up server DistGraph should be initialize at some point it but is actually never initialized. 

## To Reproduce

This repro requires to have 2 machines (one can use docker containers) with their IPs written in `ip_config.txt`, and the dist graph in a directory shared across the machines (`graph_path`).

repro.py
```
import dgl
import os
from dgl.distributed import load_partition_book

os.environ['DGL_DIST_MODE'] = 'distributed'

num_part = 2
server_id = int(os.environ.get('SERVER_ID', "0"))
part_id = int(os.environ.get('PART_ID'))
mode = os.environ.get('TEST_MODE', "server")


server_count = 2
num_clients_per_machine = 2

ip_config = "ip_config.txt"
net_type = "tensorpipe"
graph_path = f"/shared_workspace/dgl_dist_tensor_test/dist_graph/random_test_graph.json"
shared_mem=False

def run_server():
    # server_count = num_servers_per_machine
    g = dgl.distributed.DistGraphServer(server_id, ip_config,
                        server_count, num_clients_per_machine*num_part,
                        graph_path,
                        disable_shared_mem=not shared_mem,
                        graph_format=['csc', 'coo'], keep_alive=False,
                        net_type=net_type)
    print(f"starting server {server_id}")
    g.start()

def run_client():
    os.environ['DGL_NUM_SERVER'] = str(server_count)
    dgl.distributed.initialize(ip_config, net_type=net_type)
    global_rank = dgl.distributed.get_rank()
    gpb, graph_name, _, _ = load_partition_book(graph_path, part_id, None)
    g = dgl.distributed.DistGraph(graph_name, gpb=gpb)
    policy = dgl.distributed.PartitionPolicy('node', g.get_partition_book())
    print(f"client {global_rank} is done, waiting...")
    dgl.distributed.client_barrier()
    print(f"client {global_rank} exiting!")

if mode == "server":
    run_server()
else:
    run_client()
```

Machine #1
```
SERVER_ID=0 PART_ID=0 TEST_MODE=server python repro.py&
SERVER_ID=1 PART_ID=0 TEST_MODE=server python repro.py&
PART_ID=0 TEST_MODE=client python repro.py&
PART_ID=0 TEST_MODE=client python repro.py&
```

Machine #2
```
SERVER_ID=2 PART_ID=1 TEST_MODE=server python repro.py&
SERVER_ID=3 PART_ID=1 TEST_MODE=server python repro.py&
PART_ID=1 TEST_MODE=client python repro.py&
PART_ID=1 TEST_MODE=client python repro.py&
```

**Comment by Rhett-Ying** [comment]
@zheng-da could you help confirm this?

**Comment by Rhett-Ying** [comment]
For now, we have below comments in code while I don't think we really support such a feature/behavior. I think we could remove `disable_shared_mem` flag.
https://github.com/dmlc/dgl/blob/0f0e7c7fad6ec1399a67881ce9a7e60d14cfe1a0/python/dgl/distributed/dist_graph.py#L413-L416
