### ISSUE TITLE
DistDGL doesn't allow running inference inside the training loop.

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#4235]
## 🐛 Bug

If we run distributed inference inside the training loop with num_sampler > 0, we will get the following error.
```
Client[6] in group[0] is exiting...
0it [00:01, ?it/s]
Traceback (most recent call last):
  File "m5gnn_lp_huggingface.py", line 26, in <module>
    main(args)
  File "m5gnn_lp_huggingface.py", line 15, in main
    trainer.fit()
  File "/m5-gnn/python/m5gnn/trainer/lp_trainer.py", line 130, in fit
    lp_model.fit(dataloader)
  File "/m5-gnn/python/m5gnn/model/rgnn_lp_base.py", line 211, in fit
    self.save_model_embed(epoch, i, g, bert_emb_cache)
  File "/m5-gnn/python/m5gnn/model/rgnn.py", line 774, in save_model_embed
    embeddings = self.compute_embeddings(g, device, bert_emb_cache, feat_field=self._feat_name)
  File "/m5-gnn/python/m5gnn/model/rgnn.py", line 573, in compute_embeddings
    embeddings = self.compute_gnn_embeddings(g, device, bert_emb_cache, target_nidx, feat_field)
  File "/m5-gnn/python/m5gnn/model/rgnn.py", line 630, in compute_gnn_embeddings
    embeddings = do_fullgraph_infer(g=g,
  File "/m5-gnn/python/m5gnn/model/utils.py", line 858, in do_fullgraph_infer
    embeddings = model.module.dist_inference(g, eval_batch_size, device, 0, node_embed, client=client, mlflow_report_frequency=mlflow_report_frequency)
  File "/m5-gnn/python/m5gnn/model/rgnn_base.py", line 86, in dist_inference
    for iter_l, (input_nodes, output_nodes, blocks) in enumerate(tqdm.tqdm(dataloader)):
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/dist_dataloader.py", line 110, in __next__
    result = self._get_data_from_result_queue()
  File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/dist_dataloader.py", line 122, in _get_data_from_result_queue
    ret = self.pool.get_result(self.name, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/dist_context.py", line 149, in get_result
    assert result_dataloader_name == dataloader_name
AssertionError
```
This is because DistDGL tries to create a process pool whenever the distributed data loader is created.

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by jermainewang** [comment]
What's behind `model.module.dist_inference`?

**Comment by Rhett-Ying** [comment]
The root cause is all dataloaders are using the same sampler pool. I will try to figure out a way to support it.

**Comment by Rhett-Ying** [comment]
@zheng-da @jermainewang  I have just figured out a way to fix this issue with a quite simple fix. Please help review it. And pls let me re-estimate the pure efforts of this work item. I'd like to change the total effort from `10` to `3`.

**Comment by jermainewang** [comment]
Could you put up a short doc about how did you achieve it? This will help us review the code.
