### ISSUE TITLE
[Example][Bug] A multi-gpu run crashed for graphsage example

### ISSUE THREAD

**Issue by chang-l** [dmlc/dgl#4244]
## 🐛 Bug

When data and graph are both on cpu (i.e., `use_uva=0`) with num_workers > 0, the script `advanced/train_sampling_unsupervised.py` failed. 

Adding `CUDA_LAUNCH_BLOCKING=1` does not help, but when `num_workers=0`, it can pass.

## To Reproduce

- Run 1:  in  graphsage/advance/
` yes | python3 train_sampling_unsupervised.py --dataset ogbn-products --num-epochs 2 --gpu 0,1,2,3,4,5,6,7 --num-workers 4 --graph-device cpu --data-device cpu`

Core-dump stack (with the fix in https://github.com/dmlc/dgl/pull/4242):
```
==== backtrace (tid:   4304) ====
 0 0x0000000000014420 __funlockfile()  ???:0
 1 0x0000000004dcfed8 c10::function_ref<void (char**, long const*, long, long)>::callback_fn<at::native::AVX2::VectorizedLoop2d<at::native::(anonymous namespace)::direct_copy_kernel(at::TensorIteratorBase&)::{lambda()#3}::operator()() const::{lambda()#2}::operator()() const::{lambda(unsigned char)#1}, at::native::(anonymous namespace)::direct_copy_kernel(at::TensorIteratorBase&)::{lambda()#3}::operator()() const::{lambda()#2}::operator()() const::{lambda(at::vec::AVX2::Vectorized<unsigned char>)#2}> >()  CopyKernel.cpp.AVX2.cpp:0
 2 0x00000000011179e8 at::TensorIteratorBase::serial_for_each()  ???:0
 3 0x0000000001117b36 at::internal::invoke_parallel<at::TensorIteratorBase::for_each(c10::function_ref<void (char**, long const*, long, long)>, long)::{lambda(long, long)#1}>()  TensorIterator.cpp:0
 4 0x0000000000097818 __kmp_GOMP_microtask_wrapper()  kmp_gsupport.cpp:0
 5 0x00000000000b43b3 __kmp_invoke_microtask()  ???:0
 6 0x0000000000042194 __kmp_invoke_task_func()  :0
 7 0x000000000004189a __kmp_launch_thread()  :0
 8 0x0000000000096072 __kmp_launch_worker()  z_Linux_util.cpp:0
 9 0x0000000000008609 start_thread()  ???:0
10 0x000000000011f133 clone()  ???:0

...
Traceback (most recent call last):
  File "/workspace/examples/graphsage/advanced/train_sampling_unsupervised.py", line 257, in <module>
    main(args)
  File "/workspace/examples/graphsage/advanced/train_sampling_unsupervised.py", line 221, in main
    mp.spawn(run, args=(n_gpus, args, devices, data), nprocs=n_gpus)
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGBUS
/opt/conda/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 88 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d 
```

- Run 2:  in  graphsage/advance/
` yes | CUDA_LAUNCH_BLOCKING=1 python3 train_sampling_unsupervised.py --dataset ogbn-products --num-epochs 2 --gpu 0,1,2,3,4,5,6,7 --num-workers 4 --graph-device cpu --data-device cpu`

Core-dump stack (with the fix in https://github.com/dmlc/dgl/pull/4242): same as above

## Expected behavior

Multi-GPU runs should pass.

## Environment

 - DGL Version (e.g., 1.0): 0.9
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.13
 - OS (e.g., Linux): ubuntu
 - How you installed DGL (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): 
 - Python version: 3.8
 - CUDA/cuDNN version (if applicable): 11.7
 - GPU models and configuration (e.g. V100): A100x8
 - Any other relevant information:

**Comment by chang-l** [comment]
Seems increase container shm-size to 32G and `ipc=host` can resolve this issue.  Close for now...
