### ISSUE TITLE
ImportError for HGTConv in DGL cuda version

### ISSUE THREAD

**Issue by saketguru** [dmlc/dgl#4547]
## Description

I am unable to load HGTConv in `dgl-cu110` and `dgl-cu102`. However, I am able to load HGTConv in `dgl-0.9.0`. How can I run HGTConv on GPU?

```bash-4.2$ pip install dgl-cu110
Collecting dgl-cu110
  Downloading dgl_cu110-0.6.1-cp39-cp39-manylinux1_x86_64.whl (39.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.9/39.9 MB 51.4 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.19.0 in /home/user/anaconda2/envs/project/lib/python3.9/site-packages (from dgl-cu110) (2.28.1)
Requirement already satisfied: numpy>=1.14.0 in /home/user/anaconda2/envs/project/lib/python3.9/site-packages (from dgl-cu110) (1.23.1)
Requirement already satisfied: networkx>=2.1 in /home/user/anaconda2/envs/project/lib/python3.9/site-packages (from dgl-cu110) (2.8.6)
Requirement already satisfied: scipy>=1.1.0 in /home/user/anaconda2/envs/project/lib/python3.9/site-packages (from dgl-cu110) (1.8.1)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/user/anaconda2/envs/project/lib/python3.9/site-packages (from requests>=2.19.0->dgl-cu110) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/user/anaconda2/envs/project/lib/python3.9/site-packages (from requests>=2.19.0->dgl-cu110) (2022.6.15)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/user/anaconda2/envs/project/lib/python3.9/site-packages (from requests>=2.19.0->dgl-cu110) (1.26.10)
Requirement already satisfied: idna<4,>=2.5 in /home/user/anaconda2/envs/project/lib/python3.9/site-packages (from requests>=2.19.0->dgl-cu110) (3.3)
Installing collected packages: dgl-cu110
Successfully installed dgl-cu110-0.6.1
bash-4.2$ python
Python 3.9.12 (main, Jun  1 2022, 11:38:51)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dgl.nn.pytorch.conv import HGTConv
Using backend: pytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'HGTConv' from 'dgl.nn.pytorch.conv' (/home/user/anaconda2/envs/project/lib/python3.9/site-packages/dgl/nn/pytorch/conv/__init__.py)```

**Comment by rudongyu** [comment]
It seems that you're installing an older version (0.6.1). HGTConv is not included in that version. Please try our latest release instead.

**Comment by saketguru** [comment]
Thanks for the response.

I installed the dgl newer version.

```>>> import dgl
>>> dgl.__version__
'0.9.0'
```

and tried importing "from dgl.nn.pytorch.conv import HGTConv". It works.

However, when I move my graph to Cuda, I get the following issue
```
------
    from torch_geometric.datasets import IMDB

    dataset = IMDB('data/IMDB2')
    data = dataset[0]
    data_dict = {
        ('movie', 'md', 'director'): (data[('movie', 'to', 'director')]['edge_index'][0],
                                      data[('movie', 'to', 'director')]['edge_index'][1]),
        ('movie', 'ma', 'actor'): (data[('movie', 'to', 'actor')]['edge_index'][0],
                                   data[('movie', 'to', 'actor')]['edge_index'][1]),

    }
    g = dgl.heterograph(data_dict, device="cuda")
------
Traceback (most recent call last):
  File "/home/user/tools/NARS/train_dgl_hgt.py", line 93, in <module>
    main(args)
  File "/home/user/tools/NARS/train_dgl_hgt.py", line 53, in main
    data = load_data(device, args)
  File "/home/user/tools/NARS/data.py", line 114, in load_data
    return load_imdb(device, args)
  File "/home/user/tools/NARS/data.py", line 350, in load_imdb
    g = dgl.heterograph(data_dict, device="cuda")
  File "/home/user/anaconda2/envs/project/lib/python3.9/site-packages/dgl/convert.py", line 383, in heterograph
    return retg.to(device)
  File "/home/user/anaconda2/envs/project/lib/python3.9/site-packages/dgl/heterograph.py", line 5448, in to
    ret._graph = self._graph.copy_to(utils.to_dgl_context(device))
  File "/home/user/anaconda2/envs/project/lib/python3.9/site-packages/dgl/heterograph_index.py", line 236, in copy_to
    return _CAPI_DGLHeteroCopyTo(self, ctx.device_type, ctx.device_id)
  File "dgl/_ffi/_cython/./function.pxi", line 293, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 225, in dgl._ffi._cy3.core.FuncCall
  File "dgl/_ffi/_cython/./function.pxi", line 215, in dgl._ffi._cy3.core.FuncCall3
dgl._ffi.base.DGLError: [16:22:44] /opt/dgl/src/runtime/c_runtime_api.cc:88: Check failed: allow_missing: Device API gpu is not enabled. Please install the cuda version of dgl.
Stack trace:
```

The code works if I use "g = dgl.heterograph(data_dict)".

Now if I try to install "dgl-cu110", my dgl version is downgraded from 0.9.0 to 0.6.1 which then prevents me from loading "from dgl.nn.pytorch.conv import HGTConv".


Can you please help me in resolving this issue?

**Comment by rudongyu** [comment]
Could you provide more details of your environment(Backend Library & Version, CUDA Version, etc.) and the command you're using to install dgl?

**Comment by saketguru** [comment]
Yes. 
```
Backend = Pytorch.
torch.__version__
'1.12.0+cu102' 
```

DGL installation
```
pip install -U dgl
```
For DGL cuda 
```
pip install dgl-cu102
```
I have also tried the version ```dgl-cu110```

**Comment by rudongyu** [comment]
Please follow the instruction [here](https://www.dgl.ai/pages/start.html).
See if this command can help `pip install dgl-cu102 dglgo -f https://data.dgl.ai/wheels/repo.html`

**Comment by saketguru** [comment]
Thanks for the comment.
However, that command didn't work.

I reinstalled dgl using conda ```conda install -c dglteam dgl-cuda10.2```
and updated the gcc to 11.2.0.
This worked.
