### ISSUE TITLE
Have a proper way of changing DGL_DIST_MAX_TRY_TIMES in the launch script.

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#4580]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

The launch script doesn't understand DGL_DIST_MAX_TRY_TIMES. When running distributed training on a large graph, we need to change DGL_DIST_MAX_TRY_TIMES. We need a user-friendly way to change the environment variable and document it.

**Comment by Rhett-Ying** [comment]
I tried on master DGL and this env takes effect.
```
python3 ~/workspace/dgl/tools/launch.py \
    --workspace ~/workspace/dgl/examples/pytorch/graphsage/dist/ \
    --num_trainers 1 \
    --num_samplers 0 \
    --num_servers 1 \
    --part_config data/ogb-product.json \
    --ip_config ~/workspace/ip_config.txt \
    --graph_format csc,coo \
    "DGL_DIST_MAX_TRY_TIMES=0 DGL_LIBRARY_PATH=/home/ubuntu/workspace/dgl/build PYTHONPATH=/home/ubuntu/workspace/dgl/python:$PYTHONPATH python3 train_dist.py --graph_name ogb-product --ip_config /home/ubuntu/workspace/ip_config.txt --num_epochs 3 --batch_size 1000"
```

```
Traceback (most recent call last):                                                                                          
  File "train_dist.py", line 339, in <module>                                                                               
    main(args)                                                                                                              
  File "train_dist.py", line 260, in main
    dgl.distributed.initialize(args.ip_config, net_type=args.net_type)
  File "/home/ubuntu/workspace/dgl/python/dgl/distributed/dist_context.py", line 252, in initialize
    connect_to_server(ip_config, num_servers, max_queue_size, net_type, group_id=group_id)
  File "/home/ubuntu/workspace/dgl/python/dgl/distributed/rpc_client.py", line 183, in connect_to_server
    raise rpc.DistConnectError(max_try_times)
dgl.distributed.rpc.DistConnectError: Failed to build conncetion with peer after 0 retries. Please check network availabilit
y or increase max try times via 'DGL_DIST_MAX_TRY_TIMES'.
```

**Comment by peizhou001** [comment]
It worked on my side either, and used branch is master.


```

python  /home/ubuntu/workspace/dgl/tools/launch.py \
    --workspace /home/ubuntu/workspace/dgl/examples/pytorch/graphsage/dist/ \
    --num_trainers 1 \
    --num_samplers 0 \
    --num_servers 1 \
    --part_config data/ogb-product.json \
    --ip_config /home/ubuntu/workspace/ip_config.txt \
    --graph_format csc,coo \
    "DGL_DIST_MAX_TRY_TIMES=10 /opt/conda/envs/pytorch/bin/python /home/ubuntu/workspace/dgl/examples/pytorch/graphsage/dist/train_dist.py --graph_name ogb-product --ip_config /home/ubuntu/workspace/ip_config.txt --num_epochs 3 --batch_size 1000"
```

```
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 5676) of binary: /opt/conda/envs/pytorch/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/workspace/dgl/examples/pytorch/graphsage/dist/train_dist.py", line 477, in <module>
    main(args)
  File "/home/ubuntu/workspace/dgl/examples/pytorch/graphsage/dist/train_dist.py", line 344, in main
    dgl.distributed.initialize(args.ip_config, net_type=args.net_type)
  File "/home/ubuntu/workspace/dgl/python/dgl/distributed/dist_context.py", line 310, in initialize
    connect_to_server(
  File "/home/ubuntu/workspace/dgl/python/dgl/distributed/rpc_client.py", line 206, in connect_to_server
    raise rpc.DistConnectError(max_try_times)
dgl.distributed.rpc.DistConnectError: Failed to build conncetion with peer after 10 retries. Please check network availability or increase max try times via 'DGL_DIST_MAX_TRY_TIMES'.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1445099) of binary: /opt/conda/envs/pytorch/bin/python
```

**Comment by peizhou001** [comment]
@zheng-da  We and @Rhett-Ying  has tested in our environments already and both of us didn't encounter this error. I use conda and rui use a naked python. So have you met this error again and tell us how to reproduce it? Otherwise it maybe an accident error.
