### ISSUE TITLE
ModuleNotFoundError: No module named 'dgl.graph'

### ISSUE THREAD

**Issue by Jiashuhao518** [dmlc/dgl#4639]
```bash
(dgl) jiash@asic-u2:~/Desktop/pna/realworld_benchmark$ python main_molecules.py --weight_decay=3e-6 --L=16 --hidden_dim=70 --out_dim=70 --residual=True --edge_feat=True --edge_dim=40 --readout=sum --in_feat_dropout=0.0 --dropout=0.0 --graph_norm=True --batch_norm=True --aggregators="mean max min std" --scalers="identity amplification attenuation" --towers=5 --pretrans_layers=1 --posttrans_layers=1 --divide_input_first=True --divide_input_last=True --dataset ZINC --gpu_id 0 --config "configs/molecules_graph_regression_pna_ZINC.json" --lr_schedule_patience=20
cuda available with GPU: Tesla V100-PCIE-32GB
[I] Loading dataset ZINC...
Traceback (most recent call last):
  File "/home/jiash/Desktop/pna/realworld_benchmark/main_molecules.py", line 394, in <module>
    main()
  File "/home/jiash/Desktop/pna/realworld_benchmark/main_molecules.py", line 267, in main
    dataset = MoleculeDataset(DATASET_NAME)
  File "/home/jiash/Desktop/pna/realworld_benchmark/data/molecules.py", line 142, in __init__
    f = pickle.load(f)
ModuleNotFoundError: No module named 'dgl.graph'
```

I have installed dgl-cuda10.2, why this report no module named 'dgl.graph'.
This error points to a pickle sentence.
```python
class MoleculeDataset(torch.utils.data.Dataset):

    def __init__(self, name):
        """
            Loading SBM datasets
        """
        start = time.time()
        print("[I] Loading dataset %s..." % (name))
        self.name = name
        data_dir = 'data/'
        with open(data_dir + name + '.pkl', "rb") as f:
            f = pickle.load(f)
            self.train = f[0]
            self.val = f[1]
            self.test = f[2]
            self.num_atom_type = f[3]
            self.num_bond_type = f[4]
        print('train, test, val sizes :', len(self.train), len(self.test), len(self.val))
        print("[I] Finished loading.")
        print("[I] Data load time: {:.4f}s".format(time.time() - start))
```

**Comment by mufeili** [comment]
Sorry for the late reply. Perhaps you need to check if you need to use a different version of DGL. Alternatively, it will be easier for us to dive deeper by providing a minimal script for reproducing the issue.

**Comment by rudongyu** [comment]
Hi @Jiashuhao518, I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
