### ISSUE TITLE
Example code in TreeLSTM fail

### ISSUE THREAD

**Issue by reveriel** [dmlc/dgl#533]
## 📚 Documentation

https://docs.dgl.ai/en/latest/tutorials/models/2_small_graph/3_tree-lstm.html

The code provided is [3_tree-lstm.py](https://docs.dgl.ai/en/latest/_downloads/3_tree-lstm.py)

Running `python 3_tree-lstm.py` results this:
```
  % python 3_tree-lstm.py
Preprocessing...
Traceback (most recent call last):
  File "3_tree-lstm.py", line 56, in <module>
    trainset = SST(mode='tiny')  # the "tiny" set has only 5 trees
  File "/usr/local/miniconda3/lib/python3.6/site-packages/dgl/data/tree.py", line 62, in __init__
    self._load()
  File "/usr/local/miniconda3/lib/python3.6/site-packages/dgl/data/tree.py", line 100, in _load
    self.trees.append(self._build_tree(sent))
  File "/usr/local/miniconda3/lib/python3.6/site-packages/dgl/data/tree.py", line 120, in _build_tree
    ret.from_networkx(g, node_attrs=['x', 'y', 'mask'])
  File "/usr/local/miniconda3/lib/python3.6/site-packages/dgl/graph.py", line 1212, in from_networkx
    self._graph.from_networkx(nx_graph)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/dgl/graph_index.py", line 755, in from_networkx
    for e in nx_graph.edges:
TypeError: 'method' object is not iterable
```

My Environment:

dgl 0.2,
networkx 1.11
pytorch 1.0.1

**Comment by jermainewang** [comment]
It seems that your networkx is too old. They changed the `edges` member from a method to a view object later. In networkx 2.2, the following codes work fine:
```python
>>> import networkx as nx
>>> g = nx.path_graph(3)
>>> g.edges
EdgeView([(0, 1), (1, 2)])
>>> for e in g.edges:
...     print(e)
... 
(0, 1)
(1, 2)
```

We do have a minimal requirement of networkx 2.1 as our dependency. May I know how you install dgl? (pip or conda)?

**Comment by reveriel** [comment]
Thanks.
I used conda, which points to an outdated mirrors.
