### ISSUE TITLE
whether dgl.block conflicts with multiprocess Queue

### ISSUE THREAD

**Issue by YijianLiu** [dmlc/dgl#5461]
Hello, when I try to do something by myself:
Use multiprocess and shared queue to store dgl.block, it occur errors sometime when I use 'queue.get()' to get blocks
Error 1: FileNotFoundError: [Errno 2] No such file or directory
Error 2: [Errno 104] Connection reset by peer
But everything OK, when I don't put dgl.block to shared queue, I think whether dgl.block has conflict with multiprocess Queue whether it will release python GIL.

**Comment by YijianLiu** [comment]
More Description: using to multiprocessing, two subprocess, and two queue
one queue puts block, and the other queue tries to get block, and it occurs error: 
  _File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory_

**Comment by YijianLiu** [comment]
More Description: using to multiprocessing, two subprocess, and two queue
one queue puts block, and when the other queue tries to get block, and it occurs error:
_Process Process-2:
Traceback (most recent call last):
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lyj/project/dist_gnn/examples/test_queue_process/dataloader.py", line 41, in _lookup_ids
    blocks = sampler_q.get(timeout=2)
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused_

But it goes True, when I not use dgl.blocks, so I think whether it conflicts with python multiprocessing, 
my dgl version: 0.9 python 3.6 torch version: 1.10.2

**Comment by YijianLiu** [comment]
More Description:
I use two sub-processes, and two queue to communicate,
the one queue put blocks and the other one tries to get blocks, but it occur errors:
_Traceback (most recent call last):
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lyj/project/dist_gnn/examples/test_queue_process/dataloader.py", line 41, in _lookup_ids
    blocks = sampler_q.get(timeout=2)
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/root/anaconda3/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/root/anaconda3/envs/py36/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused_
When I try to put and get other things, it will be right, I think whether dgl.blocks conflict with python multiprocessing when using more than 1 sub-process
