### ISSUE TITLE
OSError: libcusparse.so.11: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lvrcek** [dmlc/dgl#5560]
## 🐛 Bug

I am unable to install any version of DGL on my machine which has CUDA 12.0 installed.
I checked `/usr/local/cuda/lib64` and there indeed is no `libcusparse.so.11`, but there is `libcusparse.so.12`. Since CUDA is backwards compatible, is it possible to use `libcusparse.so.12` for DGL versions that support CUDA 11.7 and older?

## To Reproduce

1. Install Pytorch, e.g.  version 1.12.0 for CUDA 11.3
2. Install DGL for CUDA 11.3
3. Import dgl inside Python

```
>>> import dgl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vrcekl/miniconda3/envs/gnn-assembly/lib/python3.8/site-packages/dgl/__init__.py", line 18, in <module>
    from .backend import load_backend, backend_name
  File "/home/vrcekl/miniconda3/envs/gnn-assembly/lib/python3.8/site-packages/dgl/backend/__init__.py", line 122, in <module>
    load_backend(get_preferred_backend())
  File "/home/vrcekl/miniconda3/envs/gnn-assembly/lib/python3.8/site-packages/dgl/backend/__init__.py", line 51, in load_backend
    from .._ffi.base import load_tensor_adapter  # imports DGL C library
  File "/home/vrcekl/miniconda3/envs/gnn-assembly/lib/python3.8/site-packages/dgl/_ffi/base.py", line 50, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
  File "/home/vrcekl/miniconda3/envs/gnn-assembly/lib/python3.8/site-packages/dgl/_ffi/base.py", line 39, in _load_lib
    lib = ctypes.CDLL(lib_path[0])
  File "/home/vrcekl/miniconda3/envs/gnn-assembly/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.11: cannot open shared object file: No such file or directory
```

## Expected behavior

Be able to use DGL for CUDA versions 11.7 and earlier when I have CUDA12 installed, if possible.

## Environment

 - DGL Version (e.g., 1.0): Latest
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): Pytorch 1.12.0
 - OS (e.g., Linux): Ubuntu 22.04.2 LTS
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8.16
 - CUDA/cuDNN version (if applicable): 12.0
 - GPU models and configuration (e.g. V100): H100
 - Any other relevant information:

**Comment by lvrcek** [comment]
[Issue 2258](https://github.com/dmlc/dgl/issues/2258) described a similar problem and I found a solution there. 

With conda I can install cudatoolkit, and which "replaces" the existing CUDA libraries with the older ones.

```
conda install pytorch==1.12.0 torchvision==0.13.0 torchaudio==0.12.0 cudatoolkit=11.3 -c pytorch
conda install -c dglteam/label/cu113 dgl
```

The question for installing with pip remains, though. Is it possible to install with pip when using CUDA 12 so that the installation doesn't break due to older version of `libcusparse.so`?

**Comment by mufeili** [comment]
Any thoughts? @BarclayII
