### ISSUE TITLE
benchmark tests crashed after PR 5366(commit: 62b5f50)

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#5592]
## 🐛 Bug

`//benchmarks/benchmarks/model_speed/bench_rgcn_hetero_ns.py` works well on commit `27b008b` which is just before `62b5f50` but crahsed on `62b5f50`.
```
               load ogbn-mag
               finish loading ogbn-mag
               start training...
               4 DL workers are assigned to cpus [0, 1, 2, 3], main process will use cpus [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
               Traceback (most recent call last):
                 File "/home/ubuntu/.local/lib/python3.8/site-packages/asv/benchmark.py", line 1293, in main_run_server
                   main_run(run_args)
                 File "/home/ubuntu/.local/lib/python3.8/site-packages/asv/benchmark.py", line 1167, in main_run
                   result = benchmark.do_run()
                 File "/home/ubuntu/.local/lib/python3.8/site-packages/asv/benchmark.py", line 573, in do_run
                   return self.run(*self._current_params)
                 File "/home/ubuntu/.local/lib/python3.8/site-packages/asv/benchmark.py", line 859, in run
                   return self.func(*param)
                 File "/home/ubuntu/workspace/dgl_1/benchmarks/benchmarks/model_speed/bench_rgcn_hetero_ns.py", line 365, in track_time
                   for step, (input_nodes, seeds, blocks) in enumerate(loader):
                 File "/home/ubuntu/workspace/dgl_1/python/dgl/dataloading/dataloader.py", line 619, in __next__
                   self._next_non_threaded()
                 File "/home/ubuntu/workspace/dgl_1/python/dgl/dataloading/dataloader.py", line 592, in _next_non_threaded
                   batch = next(self.dataloader_it)
                 File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
                   data = self._next_data()
                 File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1316, in _next_data
                   idx, data = self._get_data()
                 File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1282, in _get_data
                   success, data = self._try_get_data()
                 File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1120, in _try_get_data
                   data = self._data_queue.get(timeout=timeout)
                 File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
                   return _ForkingPickler.loads(res)
                 File "/home/ubuntu/workspace/dgl_1/python/dgl/heterograph_index.py", line 1570, in _forking_rebuild
                   graph_index = _CAPI_DGLHeteroForkingUnpickle(states)
                 File "dgl/_ffi/_cython/./function.pxi", line 295, in dgl._ffi._cy3.core.FunctionBase.__call__
                 File "dgl/_ffi/_cython/./function.pxi", line 227, in dgl._ffi._cy3.core.FuncCall
                 File "dgl/_ffi/_cython/./function.pxi", line 217, in dgl._ffi._cy3.core.FuncCall3
               dgl._ffi.base.DGLError: [05:00:29] /home/ubuntu/workspace/dgl_1/src/runtime/c_runtime_api.cc:82: Check failed: allow_missing: Device API cuda is not enabled. Please install the cuda version of dgl.
               Stack trace:
                 [bt] (0) /home/ubuntu/workspace/dgl_1/build/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x80) [0x7f3a56c3c230]
                 [bt] (1) /home/ubuntu/workspace/dgl_1/build/libdgl.so(dgl::runtime::DeviceAPIManager::GetAPI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)+0x2ab) [0x7f3a5700fc5b]
                 [bt] (2) /home/ubuntu/workspace/dgl_1/build/libdgl.so(dgl::runtime::DeviceAPI::Get(DGLDeviceType, bool)+0x20b) [0x7f3a5700c0eb]
                 [bt] (3) /home/ubuntu/workspace/dgl_1/build/libdgl.so(dgl::runtime::NDArray::PinContainer(dgl::runtime::NDArray::Container*)+0x13c) [0x7f3a570290ac]
                 [bt] (4) /home/ubuntu/workspace/dgl_1/build/libdgl.so(dgl::UnitGraph::PinMemory_()+0xaf) [0x7f3a5718916f]
                 [bt] (5) /home/ubuntu/workspace/dgl_1/build/libdgl.so(dgl::HeteroGraph::PinMemory_()+0x2e) [0x7f3a5707454e]
                 [bt] (6) /home/ubuntu/workspace/dgl_1/build/libdgl.so(dgl::HeteroForkingUnpickle(dgl::HeteroPickleStates const&)+0x7b5) [0x7f3a570c2225]
                 [bt] (7) /home/ubuntu/workspace/dgl_1/build/libdgl.so(+0x611fbc) [0x7f3a570c2fbc]
                 [bt] (8) /home/ubuntu/workspace/dgl_1/build/libdgl.so(DGLFuncCall+0x60) [0x7f3a5700ef70]
               asv: benchmark failed (exit status 1)
```
## To Reproduce

1. checkout master to `62b5f50`
2. build DGL
3. `cd benchmarks`
4. `DGL_HOME=/home/ubuntu/workspace/dgl_1 DGL_LIBRARY_PATH=$DGL_HOME/build PYTHONPATH=tools:tests:$DGL_HOME/python:$PYTHONPATH asv run -n -e --python=same --verbose --bench model_speed.bench_rgcn_hetero`

## Environment

 - DGL Version (e.g., 1.0):
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by chang-l** [comment]
@Rhett-Ying Okay. I will open a PR for the fix.

**Comment by frozenbugs** [comment]
For the record: related PR https://github.com/dmlc/dgl/pull/5366
