### ISSUE TITLE
Exist error when set dataloader's use_uva=True

### ISSUE THREAD

**Issue by lzc17** [dmlc/dgl#5606]
Traceback (most recent call last):
  File "uva_sampler.py", line 243, in <module>
    run(args, device, data)
  File "uva_sampler.py", line 166, in run
    input_nodes, seeds, blocks = next(it)
  File "/home/liuzhencheng/anaconda3/envs/dgl0.8.0/lib/python3.6/site-packages/dgl/dataloading/dataloader.py", line 512, in __next__
    self._next_non_threaded() if not self.use_thread else self._next_threaded()
  File "/home/liuzhencheng/anaconda3/envs/dgl0.8.0/lib/python3.6/site-packages/dgl/dataloading/dataloader.py", line 485, in _next_non_threaded
    batch = next(self.dataloader_it)
  File "/home/liuzhencheng/anaconda3/envs/dgl0.8.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/liuzhencheng/anaconda3/envs/dgl0.8.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/liuzhencheng/anaconda3/envs/dgl0.8.0/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 35, in fetch
    return self.collate_fn(data)
  File "/home/liuzhencheng/anaconda3/envs/dgl0.8.0/lib/python3.6/site-packages/dgl/dataloading/dataloader.py", line 529, in __call__
    batch = self.sample_func(self.g, items)
  File "/home/liuzhencheng/anaconda3/envs/dgl0.8.0/lib/python3.6/site-packages/dgl/dataloading/base.py", line 252, in sample
    result = self.sample_blocks(g, seed_nodes, exclude_eids=exclude_eids)
  File "/home/liuzhencheng/anaconda3/envs/dgl0.8.0/lib/python3.6/site-packages/dgl/dataloading/neighbor_sampler.py", line 113, in sample_blocks
    exclude_edges=exclude_eids)
  File "/home/liuzhencheng/anaconda3/envs/dgl0.8.0/lib/python3.6/site-packages/dgl/utils/internal.py", line 909, in _fn
    return func(*args, **kwargs)
  File "/home/liuzhencheng/anaconda3/envs/dgl0.8.0/lib/python3.6/site-packages/dgl/sampling/neighbor.py", line 297, in sample_neighbors
    copy_ndata=copy_ndata, copy_edata=copy_edata)
  File "/home/liuzhencheng/anaconda3/envs/dgl0.8.0/lib/python3.6/site-packages/dgl/sampling/neighbor.py", line 365, in _sample_neighbors
    edge_dir, prob_arrays, excluded_edges_all_t, replace)
  File "dgl/_ffi/_cython/./function.pxi", line 287, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 232, in dgl._ffi._cy3.core.FuncCall
  File "dgl/_ffi/_cython/./base.pxi", line 155, in dgl._ffi._cy3.core.CALL
dgl._ffi.base.DGLError: [22:47:22] /opt/dgl/src/runtime/cuda/cuda_device_api.cc:246: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: CUDA: an illegal memory access was encountered

**Comment by lzc17** [comment]
**    sampler = dgl.dataloading.MultiLayerNeighborSampler(
        [int(fanout) for fanout in args.fan_out.split(',')])

    dataloader = dgl.dataloading.DataLoader(
        train_g, # cpu
        train_nid.to(device), # cpu
        sampler,
        device=device,
        use_uva=True,
        batch_size=args.batch_size,
        shuffle=True,
        drop_last=False,
        num_workers=0)**

**Comment by lzc17** [comment]
`    sampler = dgl.dataloading.MultiLayerNeighborSampler(
        [int(fanout) for fanout in args.fan_out.split(',')])

    dataloader = dgl.dataloading.DataLoader(
        train_g, # cpu
        train_nid.to(device), # cpu
        sampler,
        device=device,
        use_uva=True,
        batch_size=args.batch_size,
        shuffle=True,
        drop_last=False,
        num_workers=0)`

**Comment by czkkkkkk** [comment]
Hi @lzc17 , you may need to pin the graph to unpagable CPU memory to support UVA. (https://docs.dgl.ai/en/latest/generated/dgl.DGLGraph.pin_memory_.html)

**Comment by lzc17** [comment]
Add this code ’train_g.pin_memory_()’ ，but the error still exists.
