### ISSUE TITLE
[Benchmark] `No module named benchmarks found` is thrown when run multigpu tests

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#5628]
## 🐛 Bug

`spawn` is used for multigpu benchmark tests, it works well on local run with `asv run -n -e --python=same`. But when run on benchmark CI which runs with `asv run -e -v`, it crashed with below error.

I(Rui) guess `import benchmarks` is triggered somewhere in ASV. I have tried to create a dedicated conda env and specify `PYTHONPATH` in yaml file, but not work. `echo $PYTHONPATH` always returns null.

```
[100.00%] ···· For parameters: 'reddit'
               Traceback (most recent call last):
                 File "<string>", line 1, in <module>
                 File "/asv/dgl/benchmarks/env/06715dc6ea55f2b02b6ebc21bca7e34a/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
                   exitcode = _main(fd, parent_sentinel)
                 File "/asv/dgl/benchmarks/env/06715dc6ea55f2b02b6ebc21bca7e34a/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
                   self = reduction.pickle.load(from_parent)
               ModuleNotFoundError: No module named 'benchmarks'
               Traceback (most recent call last):
                 File "<string>", line 1, in <module>
                 File "/asv/dgl/benchmarks/env/06715dc6ea55f2b02b6ebc21bca7e34a/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
                   exitcode = _main(fd, parent_sentinel)
                 File "/asv/dgl/benchmarks/env/06715dc6ea55f2b02b6ebc21bca7e34a/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
                   self = reduction.pickle.load(from_parent)
               ModuleNotFoundError: No module named 'benchmarks'
```

```
name: dgl-dev-gpu
...
varaibles:
  PYTHONPATH: /asv/dgl/benchmarks
```
## To Reproduce

see above

## Environment

 - DGL Version (e.g., 1.0): 1.1.x
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.13.1
 - OS (e.g., Linux): Ubuntu
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version: 3.10
 - CUDA/cuDNN version (if applicable): 11.6
 - GPU models and configuration (e.g. V100): g4dn.12xlarge
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
for reference: https://github.com/dmlc/dgl/pull/5620

**Comment by Rhett-Ying** [comment]
how about trying with https://pytorch.org/docs/stable/multiprocessing.html#spawning-subprocesses

**Comment by Rhett-Ying** [comment]
This issue happens with original DGL benchmark. As we are deprecating it and working with new DGL benchmark framework now, let's close this ticket.
