### ISSUE TITLE
[DistDGL] fail to split an empty test set in node_split or edge_split.

### ISSUE THREAD

**Issue by zheng-da** [dmlc/dgl#5631]
## 🐛 Bug

If the test mask is empty, DistDGL node_split or edge_split will result in the error below.
```
Traceback (most recent call last):
  File "/home/ubuntu/workspace/graph-storm/python/graphstorm/run/gsgnn_lp/gsgnn_lp.py", line 152, in <
module>
    main(args)
  File "/home/ubuntu/workspace/graph-storm/python/graphstorm/run/gsgnn_lp/gsgnn_lp.py", line 46, in ma
in
    train_data = GSgnnEdgeTrainData(config.graph_name, 
  File "/home/ubuntu/workspace/graph-storm/python/graphstorm/dataloading/dataset.py", line 259, in __i
nit__
    node_feat_field, edge_feat_field)
  File "/home/ubuntu/workspace/graph-storm/python/graphstorm/dataloading/dataset.py", line 168, in __i
nit__
    node_feat_field, edge_feat_field)
  File "/home/ubuntu/workspace/graph-storm/python/graphstorm/dataloading/dataset.py", line 98, in __in
it__
    sys_tracker.check('construct training data')
  File "/home/ubuntu/workspace/graph-storm/python/graphstorm/dataloading/dataset.py", line 310, in prepare_data
    g.edges[canonical_etype].data['test_mask'],
  File "/home/ubuntu/.local/lib/python3.8/site-packages/dgl/distributed/dist_graph.py", line 1571, in edge_split
    return _split_random_within_part(partition_book, rank, part_eid)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/dgl/distributed/dist_graph.py", line 1383, in _split_random_within_part
    offset = _even_offset(len(part_eles), num_client_per_part)
TypeError: object of type 'NoneType' has no len()
Client[13] in group[0] is exiting...
```

**Comment by jermainewang** [comment]
@Rhett-Ying  Could you help verify this?
