### ISSUE TITLE
dglsp.spmatrix dosn't support tensorflow

### ISSUE THREAD

**Issue by hmliangliang** [dmlc/dgl#5655]
g = dgl.graph(([0, 0,1,2,2], [1,4,2,4,3]), num_nodes=5)
g = dgl.to_bidirected(g)
A = dglsp.spmatrix(tf.stack(g.edges()), shape=(5, 5))

Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3397, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-73-9f3433cd7c0f>", line 1, in <cell line: 1>
    A = dglsp.spmatrix(tf.stack(g.edges()), shape=(5, 5))
  File "D:\Anaconda\lib\site-packages\dgl\sparse\sparse_matrix.py", line 524, in spmatrix
    return from_coo(indices[0], indices[1], val, shape)
  File "D:\Anaconda\lib\site-packages\dgl\sparse\sparse_matrix.py", line 605, in from_coo
    val = torch.ones(row.shape[0]).to(row.device)
RuntimeError: Invalid device string: '/job:localhost/replica:0/task:0/device:CPU:0'

**Comment by Rhett-Ying** [comment]
This is expected as `tensorflow` is not supported in dgl sparse. Only `PyTorch` is supported for now.
