### ISSUE TITLE
Many examples fail with the error: RuntimeError: Could not infer dtype of numpy.int64

### ISSUE THREAD

**Issue by yurivict** [dmlc/dgl#5727]
## 🐛 Bug

For example:
```
[yuri@yv /usr/ports/math/py-dgl/work-py39/dgl-1.1.0/examples/pytorch/gxn]$ python3.9 main.py 
WARNING:root:No valid pool_ratios is given, using default value '[0.8, 0.7]'
WARNING:root:No valid conv1d_dims is give, using default value [16, 32]
WARNING:root:No valid conv1d_kws is given, using default value '[5]'
WARNING:root:GPU is not available, using CPU for training
Trial 1/1
Downloading ./datasets/DD.zip from https://www.chrsmrrs.com/graphkerneldatasets/DD.zip...
Extracting file to ./datasets/DD_a6864905
Traceback (most recent call last):
  File "/usr/ports/math/py-dgl/work-py39/dgl-1.1.0/examples/pytorch/gxn/main.py", line 175, in <module>
    acc, train_time = main(args)
  File "/usr/ports/math/py-dgl/work-py39/dgl-1.1.0/examples/pytorch/gxn/main.py", line 98, in main
    dataset = LegacyTUDataset(args.dataset, raw_dir=args.dataset_path)
  File "/usr/local/lib/python3.9/site-packages/dgl/data/tu.py", line 99, in __init__
    super(LegacyTUDataset, self).__init__(
  File "/usr/local/lib/python3.9/site-packages/dgl/data/dgl_dataset.py", line 333, in __init__
    super(DGLBuiltinDataset, self).__init__(
  File "/usr/local/lib/python3.9/site-packages/dgl/data/dgl_dataset.py", line 112, in __init__
    self._load()
  File "/usr/local/lib/python3.9/site-packages/dgl/data/dgl_dataset.py", line 203, in _load
    self.process()
  File "/usr/local/lib/python3.9/site-packages/dgl/data/tu.py", line 144, in process
    g.add_nodes(int(DS_edge_list.max()) + 1)
  File "/usr/local/lib/python3.9/site-packages/dgl/heterograph.py", line 423, in add_nodes
    utils.toindex(num_nodes_per_type, "int64"),
  File "/usr/local/lib/python3.9/site-packages/dgl/utils/internal.py", line 304, in toindex
    return data if isinstance(data, Index) else Index(data, dtype)
  File "/usr/local/lib/python3.9/site-packages/dgl/utils/internal.py", line 37, in __init__
    self._initialize_data(data)
  File "/usr/local/lib/python3.9/site-packages/dgl/utils/internal.py", line 44, in _initialize_data
    self._dispatch(data)
  File "/usr/local/lib/python3.9/site-packages/dgl/utils/internal.py", line 110, in _dispatch
    self._user_tensor_data[F.cpu()] = F.zerocopy_from_numpy(
  File "/usr/local/lib/python3.9/site-packages/dgl/backend/pytorch/tensor.py", line 428, in zerocopy_from_numpy
    return th.as_tensor(np_array)
RuntimeError: Could not infer dtype of numpy.int64
```

## Environment

 - DGL Version (e.g., 1.0): 1.1.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 2.0.0
 - OS (e.g., Linux): FreeBSD 13.2 STABLE
 - How you installed DGL (`conda`, `pip`, source): FreeBSD port
 - Python version: 3.9
 - CUDA/cuDNN version (if applicable): n/a
 - GPU models and configuration (e.g. V100): n/a
 - Any other relevant information: n/a

**Comment by yurivict** [comment]
Building PyTorch with Numpy fixes the problem.
