### ISSUE TITLE
examples/pytorch/gin is broken: dgl._ffi.base.DGLError: Expect argument "u" to have data type int32 or int64, but got torch.float32

### ISSUE THREAD

**Issue by yurivict** [dmlc/dgl#5749]
## 🐛 Bug

This example breaks.

## To Reproduce

```
[yuri@yv /usr/ports/math/py-dgl/work-py39/dgl-1.1.0/examples/pytorch/gin]$ python3.9 train.py --dataset MUTAG
Training with DGL built-in GINConv module with a fixed epsilon = 0
Traceback (most recent call last):
  File "/usr/ports/math/py-dgl/work-py39/dgl-1.1.0/examples/pytorch/gin/train.py", line 147, in <module>
    dataset = GINDataset(
  File "/usr/local/lib/python3.9/site-packages/dgl/data/gindt.py", line 132, in __init__
    super(GINDataset, self).__init__(
  File "/usr/local/lib/python3.9/site-packages/dgl/data/dgl_dataset.py", line 333, in __init__
    super(DGLBuiltinDataset, self).__init__(
  File "/usr/local/lib/python3.9/site-packages/dgl/data/dgl_dataset.py", line 112, in __init__
    self._load()
  File "/usr/local/lib/python3.9/site-packages/dgl/data/dgl_dataset.py", line 203, in _load
    self.process()
  File "/usr/local/lib/python3.9/site-packages/dgl/data/gindt.py", line 240, in process
    g.add_edges(j, nrow[2:])
  File "/usr/local/lib/python3.9/site-packages/dgl/heterograph.py", line 541, in add_edges
    u = utils.prepare_tensor(self, u, "u")
  File "/usr/local/lib/python3.9/site-packages/dgl/utils/checks.py", line 56, in prepare_tensor
    raise DGLError(
dgl._ffi.base.DGLError: Expect argument "u" to have data type int32 or int64, but got torch.float32.
```

## Environment

 - DGL Version (e.g., 1.0):1.1.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch-2.0.0
 - OS (e.g., Linux): FreeBSD 13.2
 - How you installed DGL (`conda`, `pip`, source): package
 - Build command you used (if compiling from source): n/a
 - Python version: 3.9
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100): n/a
 - Any other relevant information: numpy-1.23.1

**Comment by mufeili** [comment]
I cannot reproduce the issue on Ubuntu. Maybe this is due to FreeBSD.

**Comment by yurivict** [comment]
This might be due to sensitivity to some dependency version.

**Comment by frozenbugs** [comment]
Hi @yurivict , we don't have much experience on FreeBSD, do you happen to know the root source?

**Comment by yurivict** [comment]
No, I am very new to DGL.

**Comment by yurivict** [comment]
not stale

**Comment by yurivict** [comment]
not stale

**Comment by yurivict** [comment]
not stale

**Comment by rudongyu** [comment]
Hi, @yurivict. Sorry, we are unable to replicate the issue you've reported and consequently cannot proceed with a resolution. Any assistance or insights from the community would be highly appreciated. Furthermore, potential confirmation of whether this issue pertains to FreeBSD would be immensely helpful. Thanks for your understanding.
