### ISSUE TITLE
import dgl  from .backend import load_backend, backend_name RuntimeError: Cannot find the files.

### ISSUE THREAD

**Issue by limaoSure** [dmlc/dgl#5898]
## ❓ Questions and Help
According to the dependency requirements, I downloaded version 0.7.2 of dgl and stored it in my virtual environment. Then, I started the program according to the command and received the following error prompt:
`Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import dgl
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\site-packages\dgl\__init__.py", line 13, in <module>
    from .backend import load_backend, backend_name
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\site-packages\dgl\backend\__init__.py", line 107, in <module>
    load_backend(get_preferred_backend())
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\site-packages\dgl\backend\__init__.py", line 41, in load_backend
    from .._ffi.base import load_tensor_adapter # imports DGL C library
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\site-packages\dgl\_ffi\base.py", line 44, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\site-packages\dgl\_ffi\base.py", line 33, in _load_lib
    lib_path = libinfo.find_lib_path()
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\site-packages\dgl\_ffi\libinfo.py", line 83, in find_lib_path
    raise RuntimeError(message)
RuntimeError: Cannot find the files.
List of candidates:
D:\ProgramData\Anaconda3\envs\GNN\lib\site-packages\dgl\libdgl.dll
D:\ProgramData\Anaconda3\envs\GNN\lib\build\libdgl.dll
D:\ProgramData\Anaconda3\envs\GNN\lib\build\Release\libdgl.dll
D:\ProgramData\Anaconda3\envs\GNN\lib\lib\libdgl.dll
D:\ProgramData\Anaconda3\envs\GNN\libdgl.dll
D:\ProgramData\Anaconda3\envs\GNN\lib\site-packages\dgl\dgl.dll
D:\ProgramData\Anaconda3\envs\GNN\lib\build\dgl.dll
D:\ProgramData\Anaconda3\envs\GNN\lib\build\Release\dgl.dll
D:\ProgramData\Anaconda3\envs\GNN\lib\lib\dgl.dll
D:\ProgramData\Anaconda3\envs\GNN\dgl.dll`
How should I solve this problem?

**Comment by mufeili** [comment]
How did you install DGL 0.7.2?

**Comment by limaoSure** [comment]
> How did you install DGL 0.7.2?

I downloaded "dgl-0.7-2-py38_0. tar. bz2", unzipped it, and copied the dgl and dgl-0.7-2-py3.8.egg info folders inside into the site packages folder in the virtual environment.

**Comment by limaoSure** [comment]
I changed the version of dgl and downloaded dgl0.6.1, but the following errors occurred during operation:
`Exception in thread Thread-6:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\pool.py", line 576, in _handle_results
    task = get()
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\connection.py", line 318, in _recv_bytes
    return self._get_more_data(ov, maxsize)
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\connection.py", line 340, in _get_more_data
    ov, err = _winapi.ReadFile(self._handle, left, overlapped=True)
MemoryError
Process SpawnPoolWorker-7:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\pool.py", line 131, in worker
    put((job, i, result))
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\queues.py", line 362, in put
    obj = _ForkingPickler.dumps(obj)
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
MemoryError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)`

**Comment by mufeili** [comment]
Is this a duplicate of #5900 ?

**Comment by limaoSure** [comment]
> 

I later installed the dgl0.7.2 version, and the error returned was the same as before, so it was released in #5900

**Comment by mufeili** [comment]
Sorry, I did not get your point. Do we still need to keep this issue open? Or maybe we can close the issue and make 5900 the centralized place for discussion?

**Comment by limaoSure** [comment]
> 

OK.

**Comment by limaoSure** [comment]
> 

Now, I'm trying to reinstall my environment.

**Comment by guoshulan** [comment]
Have you solved your problem
