### ISSUE TITLE
P-GNN running error: MemoryError from multiprocessing floders

### ISSUE THREAD

**Issue by limaoSure** [dmlc/dgl#5900]
## ❓ Questions and Help
When I installed the dependencies according to the prompts and ran the connection prediction, the following error occurred:
`Process SpawnPoolWorker-6:
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\pool.py", line 131, in worker
    put((job, i, result))
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\queues.py", line 362, in put
    obj = _ForkingPickler.dumps(obj)
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\pool.py", line 133, in worker
    wrapped = MaybeEncodingError(e, result[1])
  File "D:\ProgramData\Anaconda3\envs\GNN\lib\multiprocessing\pool.py", line 86, in __init__
    self.value = repr(value)
MemoryError`

**Comment by mufeili** [comment]
@RecLusIve-F Could you take a look?

**Comment by limaoSure** [comment]
This is the error after reinstall my environment:
`D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
Using backend: pytorch
Learning Type: Transductive Task: link
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
Using backend: pytorch
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
D:\ProgramData\Anaconda3\envs\PGNNtest\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
Using backend: pytorch
Using backend: pytorch
Using backend: pytorch
 58%|██████████████████████████████████████████████████████████████████████▊                                                   | 290/500 [00:36<00:25,  8.27it/s]multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\PGNNtest\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\研一学习资料\VScode\GNN复现\utils.py", line 279, in get_graphs
    g, anchor_eid, edge_weight = get_a_graph(dists_max, dists_argmax)
  File "D:\研一学习资料\VScode\GNN复现\utils.py", line 266, in get_a_graph
    eid_dict = {(u, v): i for i, (u, v) in enumerate(list(zip(dst, src)))}
  File "D:\研一学习资料\VScode\GNN复现\utils.py", line 266, in <dictcomp>
    eid_dict = {(u, v): i for i, (u, v) in enumerate(list(zip(dst, src)))}
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 211, in <module>
    main(args)
  File "main.py", line 119, in main
    ) = preselect_anchor(data, args)
  File "D:\研一学习资料\VScode\GNN复现\utils.py", line 323, in preselect_anchor
    output = [p.get() for p in results]
  File "D:\研一学习资料\VScode\GNN复现\utils.py", line 323, in <listcomp>
    output = [p.get() for p in results]
  File "D:\ProgramData\Anaconda3\envs\PGNNtest\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
MemoryError`
It looks the same as the previous error.

**Comment by mufeili** [comment]
Could you also provide the installation instruction you used?

**Comment by limaoSure** [comment]
> Could you also provide the installation instruction you used?

This is my installation list:
`(PGNNtest) D:\下载>pip list
Package            Version
------------------ --------
certifi            2023.5.7
charset-normalizer 3.1.0
dgl                0.7.2
idna               3.4
joblib             1.2.0
mkl-fft            1.3.6
mkl-random         1.2.2
mkl-service        2.4.0
networkx           2.6.3
numpy              1.21.2
Pillow             9.4.0
pip                23.1.2
requests           2.31.0
scikit-learn       1.0.2
scipy              1.10.1
setuptools         67.8.0
threadpoolctl      3.1.0
torch              1.10.1
torchaudio         0.10.1
torchvision        0.11.2
typing_extensions  4.6.3
urllib3            2.0.3
wheel              0.38.4`

**Comment by limaoSure** [comment]
> 

After I fixed this, a new error appeared:
![b90f48982169729d90a718a1c1c8357](https://github.com/dmlc/dgl/assets/75509857/62bc0ff7-4375-47c5-a881-301b2d252521)

**Comment by RecLusIve-F** [comment]
> @RecLusIve-F Could you take a look?

Sure, I will take a look.

**Comment by mufeili** [comment]
> > Could you also provide the installation instruction you used?
> 
> This is my installation list: `(PGNNtest) D:\下载>pip list Package Version
> 
> certifi 2023.5.7 charset-normalizer 3.1.0 dgl 0.7.2 idna 3.4 joblib 1.2.0 mkl-fft 1.3.6 mkl-random 1.2.2 mkl-service 2.4.0 networkx 2.6.3 numpy 1.21.2 Pillow 9.4.0 pip 23.1.2 requests 2.31.0 scikit-learn 1.0.2 scipy 1.10.1 setuptools 67.8.0 threadpoolctl 3.1.0 torch 1.10.1 torchaudio 0.10.1 torchvision 0.11.2 typing_extensions 4.6.3 urllib3 2.0.3 wheel 0.38.4`

What were the exact commands you used for installation? It's also possible that you did not use the correct installation instructions.

**Comment by mufeili** [comment]
> > @RecLusIve-F Could you take a look?
> 
> Sure, I will take a look.

Thanks a lot!

**Comment by limaoSure** [comment]
> > > Could you also provide the installation instruction you used?
> > 
> > 
> > This is my installation list: `(PGNNtest) D:\下载>pip list Package Version
> > certifi 2023.5.7 charset-normalizer 3.1.0 dgl 0.7.2 idna 3.4 joblib 1.2.0 mkl-fft 1.3.6 mkl-random 1.2.2 mkl-service 2.4.0 networkx 2.6.3 numpy 1.21.2 Pillow 9.4.0 pip 23.1.2 requests 2.31.0 scikit-learn 1.0.2 scipy 1.10.1 setuptools 67.8.0 threadpoolctl 3.1.0 torch 1.10.1 torchaudio 0.10.1 torchvision 0.11.2 typing_extensions 4.6.3 urllib3 2.0.3 wheel 0.38.4`
> 
> What were the exact commands you used for installation? It's also possible that you did not use the correct installation instructions.
I download a wheelfor dgl and torch to install.
![image](https://github.com/dmlc/dgl/assets/75509857/52dcb9d2-806b-4746-88ea-96d7ebee3a24)
About pytorch,I used a official direction:`conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 -c pytorch`

**Comment by limaoSure** [comment]
> 

In addition,I can import multiprocessing in other file.
![image](https://github.com/dmlc/dgl/assets/75509857/b73d6959-57d2-4d54-adcf-2827e9e54ccf)

**Comment by mufeili** [comment]
> > > > Could you also provide the installation instruction you used?
> > > 
> > > 
> > > This is my installation list: `(PGNNtest) D:\下载>pip list Package Version certifi 2023.5.7 charset-normalizer 3.1.0 dgl 0.7.2 idna 3.4 joblib 1.2.0 mkl-fft 1.3.6 mkl-random 1.2.2 mkl-service 2.4.0 networkx 2.6.3 numpy 1.21.2 Pillow 9.4.0 pip 23.1.2 requests 2.31.0 scikit-learn 1.0.2 scipy 1.10.1 setuptools 67.8.0 threadpoolctl 3.1.0 torch 1.10.1 torchaudio 0.10.1 torchvision 0.11.2 typing_extensions 4.6.3 urllib3 2.0.3 wheel 0.38.4`
> > 
> > 
> > What were the exact commands you used for installation? It's also possible that you did not use the correct installation instructions.
> > I download a wheelfor dgl and torch to install.
> > ![image](https://user-images.githubusercontent.com/75509857/249054161-52dcb9d2-806b-4746-88ea-96d7ebee3a24.png)
> > About pytorch,I used a official direction:`conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 -c pytorch`

@BarclayII Do you have any clues?

**Comment by RecLusIve-F** [comment]
> > 
> 
> After I fixed this, a new error appeared: ![b90f48982169729d90a718a1c1c8357](https://user-images.githubusercontent.com/75509857/248732760-62bc0ff7-4375-47c5-a881-301b2d252521.png) It looks as the same as before.

Did this error occur before the first epoch or after training for several epochs? 
In my env, the memory usage for running one epoch is approximately between 12-20 GB. I am not sure if this memory usage is normal, and I need to further investigate to confirm.

**Comment by limaoSure** [comment]
> 

It occur before the first epoch. I probably understand my problem, because my virtual memory is only 40000MB.So should I increase my virtual memory capacity?
![image](https://github.com/dmlc/dgl/assets/75509857/90e0cbee-6ef0-4ec9-81e6-6d76aacd77a8)

**Comment by RecLusIve-F** [comment]
> > 
> 
> It occur before the first epoch. But my virtual memory is about 50000MB. ![image](https://user-images.githubusercontent.com/75509857/249074819-90e0cbee-6ef0-4ec9-81e6-6d76aacd77a8.png)

I think it may be related to physical memory, can I ask you about your physical memory size?
You can try to modify [num_workers](https://github.com/dmlc/dgl/blob/master/examples/pytorch/P-GNN/utils.py#L303) to reduce memory usage, but the calculation time consumption will increase.

**Comment by limaoSure** [comment]
> > > 
> > 
> > 
> > It occur before the first epoch. But my virtual memory is about 50000MB. ![image](https://user-images.githubusercontent.com/75509857/249074819-90e0cbee-6ef0-4ec9-81e6-6d76aacd77a8.png)
> 
> I think it may be related to physical memory, can I ask you about your physical memory size? You can try to modify [num_workers](https://github.com/dmlc/dgl/blob/master/examples/pytorch/P-GNN/utils.py#L303) to reduce memory usage, but the calculation time consumption will increase.

![image](https://github.com/dmlc/dgl/assets/75509857/95e7ecce-a5fb-4b5f-85ff-59a94ec4db91)
The above are my computer parameters.The num_workers in the code is 4, but spawnpoolworker-4 will appear when I run.

**Comment by RecLusIve-F** [comment]
> > > > 
> > > 
> > > 
> > > It occur before the first epoch. But my virtual memory is about 50000MB. ![image](https://user-images.githubusercontent.com/75509857/249074819-90e0cbee-6ef0-4ec9-81e6-6d76aacd77a8.png)
> > 
> > 
> > I think it may be related to physical memory, can I ask you about your physical memory size? You can try to modify [num_workers](https://github.com/dmlc/dgl/blob/master/examples/pytorch/P-GNN/utils.py#L303) to reduce memory usage, but the calculation time consumption will increase.
> 
> ![image](https://user-images.githubusercontent.com/75509857/249095267-95e7ecce-a5fb-4b5f-85ff-59a94ec4db91.png) The above are my computer parameters. The num_workers in the code is 4, but spawnpoolworker-5 will appear when I run.

I am asking about your physical memory size and not the storage size. Let me correct my mistake, reducing the num_workers do not reduce memory usage because the number of anchors is fixed.

**Comment by RecLusIve-F** [comment]
@limaoSure Given that you haven't provided me with the size of your physical memory, I assume you have a standard 16GB of memory. As mentioned above, sampling all the anchor for each epoch in one experiment would roughly consume 12-20GB of memory. Here are two solutions I can suggest:

1. You can modify the anchor sampling function to sample data for only N epochs at a time. You can call it every N epoch to reduce memory consumption.
2. You can rewrite the anchor sampling function as a Pytorch dataset and utilize a data loader for prefetching.

**Comment by RecLusIve-F** [comment]
@mufeili Should I submit a pr based on the solution I mentioned to resolve this issue?

**Comment by mufeili** [comment]
> @mufeili Should I submit a pr based on the solution I mentioned to resolve this issue?

@RecLusIve-F Let's wait for @limaoSure 's response first.

**Comment by RecLusIve-F** [comment]
> @limaoSure Given that you haven't provided me with the size of your physical memory, I assume you have a standard 16GB of memory. As mentioned above, sampling all the anchor for each epoch in one experiment would roughly consume 12-20GB of memory. Here are two solutions I can suggest:
> 
> 1. You can modify the anchor sampling function to sample anchor for only N epochs at a time. You can call it every N epoch to reduce memory consumption.
> 2. You can rewrite the anchor sampling function as a Pytorch dataset and utilize a data loader for prefetching.

@limaoSure Here is a sample code for solution 2:
```python
class PGNNDataset(Dataset):
    def __init__(self, data, args):
        self.data = data
        self.anchor_set_ids = [get_anchors(self.data["num_nodes"]) for _ in range(args.epoch_num)]

    def __len__(self):
        return len(self.anchor_set_ids)

    def __getitem__(self, idx):
        anchor_set = self.anchor_set_ids[idx]
        dists_max, dists_argmax = get_dist_max(anchor_set, self.data["dists"])
        g, anchor_eid, edge_weight = get_a_graph(dists_max, dists_argmax)

        return g, anchor_eid, dists_max, edge_weight

data = get_dataset(args)
dataset = PGNNDataset(data, args)
dataloader = DataLoader(dataset, batch_size=1, shuffle=False, num_workers=4, prefetch_factor=4,
                        collate_fn=lambda x: x[0])

for epoch, (g, anchor_eid, dist_max, edge_weight) in enumerate(dataloader):
    if epoch == 200:
        for param_group in optimizer.param_groups:
            param_group["lr"] /= 10

    g = dgl.graph(g)
    g.ndata["feat"] = torch.FloatTensor(data["feature"])
    g.edata["sp_dist"] = torch.FloatTensor(edge_weight)
    g_data = {
        "graph": g.to(device),
        "anchor_eid": anchor_eid,
        "dists_max": dist_max,
    }

    train_model(data, model, loss_func, optimizer, device, g_data)
```

**Comment by frozenbugs** [comment]
Hi, I am closing this issue assuming you are happy about our response. Feel free to follow up and reopen the issue if you have more questions with regard to our response.
