### ISSUE TITLE
ogb download dataset TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by LukeLIN-web** [dmlc/dgl#5928]
https://github.com/dmlc/dgl/blob/40dcc7152d930a8761b84d9ed2041a32fa06972c/examples/pytorch/graphsage/node_classification.py#L181

    dataset = AsNodePredDataset(DglNodePropPredDataset("ogbn-products"))
  File "/opt/conda/lib/python3.7/site-packages/ogb/nodeproppred/dataset_dgl.py", line 69, in __init__
    self.pre_process()
  File "/opt/conda/lib/python3.7/site-packages/ogb/nodeproppred/dataset_dgl.py", line 98, in pre_process
    if decide_download(url):
  File "/opt/conda/lib/python3.7/site-packages/ogb/utils/url.py", line 13, in decide_download
    size = int(d.info()["Content-Length"])/GBFACTOR
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by UTKRISHTPATESARIA** [comment]
I have been getting the exact same error too:

```
Traceback (most recent call last):
  File "/storage/utk/dgl/examples/pytorch/graphsage/node_classification.py", line 181, in <module>
    dataset = AsNodePredDataset(DglNodePropPredDataset("ogbn-papers100M", "./dataset/ogbn_papers100M/"))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/utk/miniconda3/envs/dgl/lib/python3.11/site-packages/ogb/nodeproppred/dataset_dgl.py", line 69, in __init__
    self.pre_process()
  File "/storage/utk/miniconda3/envs/dgl/lib/python3.11/site-packages/ogb/nodeproppred/dataset_dgl.py", line 98, in pre_process
    if decide_download(url):
       ^^^^^^^^^^^^^^^^^^^^
  File "/storage/utk/miniconda3/envs/dgl/lib/python3.11/site-packages/ogb/utils/url.py", line 13, in decide_download
    size = int(d.info()["Content-Length"])/GBFACTOR
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

**Comment by LukeLIN-web** [comment]
> I have been getting the exact same error too:
> 
> ```
> Traceback (most recent call last):
>   File "/storage/utk/dgl/examples/pytorch/graphsage/node_classification.py", line 181, in <module>
>     dataset = AsNodePredDataset(DglNodePropPredDataset("ogbn-papers100M", "./dataset/ogbn_papers100M/"))
>                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/storage/utk/miniconda3/envs/dgl/lib/python3.11/site-packages/ogb/nodeproppred/dataset_dgl.py", line 69, in __init__
>     self.pre_process()
>   File "/storage/utk/miniconda3/envs/dgl/lib/python3.11/site-packages/ogb/nodeproppred/dataset_dgl.py", line 98, in pre_process
>     if decide_download(url):
>        ^^^^^^^^^^^^^^^^^^^^
>   File "/storage/utk/miniconda3/envs/dgl/lib/python3.11/site-packages/ogb/utils/url.py", line 13, in decide_download
>     size = int(d.info()["Content-Length"])/GBFACTOR
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
> ```

Maybe because of https://github.com/snap-stanford/ogb/issues/452#issuecomment-1608233455
