### ISSUE TITLE
GAT example can't work on GPU mode.

### ISSUE THREAD

**Issue by yangysc** [dmlc/dgl#635]
## 🐛 Bug

The GAT example can't work on GPU mode, but can work using cpu.
The error indicates that something is wrong with the file 'nn/pytorch/softmax.py'

## To Reproduce

1. clone and install current dgl project,
1. run the gat experiment
`python3 train.py --dataset=cora --gpu=0
`

## Expected behavior
Namespace(alpha=0.2, attn_drop=0.6, dataset='cora', epochs=200, fastmode=False, gpu=0, in_drop=0.6, lr=0.005, num_heads=8, num_hidden=8, num_layers=1, num_out_heads=1, residual=False, syn_gnp_n=1000, syn_gnp_p=0.0, syn_nclasses=10, syn_nfeats=500, syn_seed=42, syn_test_ratio=0.5, syn_train_ratio=0.1, syn_type='gnp', syn_val_ratio=0.2, weight_decay=0.0005)
----Data statistics------'
      #Edges 10556
      #Classes 7
      #Train samples 140
      #Val samples 300
      #Test samples 1000
GAT(
  (gat_layers): ModuleList(
    (0): GraphAttention(
      (fc): Linear(in_features=1433, out_features=64, bias=False)
      (feat_drop): Dropout(p=0.6)
      (attn_drop): Dropout(p=0.6)
      (leaky_relu): LeakyReLU(negative_slope=0.2)
    )
    (1): GraphAttention(
      (fc): Linear(in_features=64, out_features=7, bias=False)
      (feat_drop): Dropout(p=0.6)
      (attn_drop): Dropout(p=0.6)
      (leaky_relu): LeakyReLU(negative_slope=0.2)
    )
  )
)
/home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/base.py:18: UserWarning: Initializer is not set. Use zero initializer instead. To suppress this warning, use `set_initializer` to explicitly specify which initializer to use.
  warnings.warn(msg)
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    main(args)
  File "train.py", line 102, in main
    logits = model(features)
  File "/home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/noone/Documents/Test_new_action_coding/dgl-master/dgl-master/examples/pytorch/gat/gat.py", line 121, in forward
    h = self.gat_layers[l](h).flatten(1)
  File "/home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/noone/Documents/Test_new_action_coding/dgl-master/dgl-master/examples/pytorch/gat/gat.py", line 62, in forward
    self.edge_softmax()
  File "/home/noone/Documents/Test_new_action_coding/dgl-master/dgl-master/examples/pytorch/gat/gat.py", line 82, in edge_softmax
    attention = self.softmax(self.g, self.g.edata.pop('a'))
  File "/home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/nn/pytorch/softmax.py", line 103, in edge_softmax
    return EdgeSoftmax.apply(graph, logits)
  File "/home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/nn/pytorch/softmax.py", line 42, in forward
    g.update_all(fn.copy_e(score_name, 'm'), fn.max('m', tmp_name))
  File "/home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/graph.py", line 2674, in update_all
    Runtime.run(prog)
  File "/home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/runtime/runtime.py", line 11, in run
    exe.run()
  File "/home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/runtime/ir/executor.py", line 1191, in run
    graph = self.graph.data(ctx)
  File "/home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/utils.py", line 451, in wrapper
    dic[key] = func(self, *args)
  File "/home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/graph_index.py", line 622, in get_immutable_gidx
    return self.to_immutable().asbits(self.bits_needed()).copy_to(ctx)
  File "/home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/graph_index.py", line 835, in copy_to
    handle = _CAPI_DGLImmutableGraphCopyTo(self._handle, ctx.device_type, ctx.device_id)
  File "/home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/_ffi/_ctypes/function.py", line 175, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  **File "/home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/_ffi/base.py", line 62, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: [18:15:59] /home/noone/Documents/Test_new_action_coding/dgl-master (1)/dgl-master/src/runtime/c_runtime_api.cc:87: Check failed: allow_missing: Device API gpu is not enabled.**
Stack trace:
  [bt] (0) /home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/libdgl.so(dgl::runtime::DeviceAPIManager::GetAPI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)+0x7e3) [0x7f977f9e6193]
  [bt] (1) /home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/libdgl.so(dgl::runtime::DeviceAPIManager::GetAPI(int, bool)+0x15f) [0x7f977f9e698f]
  [bt] (2) /home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/libdgl.so(dgl::runtime::NDArray::Empty(std::vector<long, std::allocator<long> >, DLDataType, DLContext)+0x288) [0x7f977fa0caa8]
  [bt] (3) /home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/libdgl.so(dgl::runtime::NDArray::CopyTo(DLContext const&) const+0xd9) [0x7f977fa478d9]
  [bt] (4) /home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/libdgl.so(dgl::CSR::CopyTo(DLContext const&) const+0xa0) [0x7f977fa40f60]
  [bt] (5) /home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/libdgl.so(dgl::ImmutableGraph::CopyTo(DLContext const&) const+0xe6) [0x7f977fa44206]
  [bt] (6) /home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/libdgl.so(+0x8adcfa) [0x7f977fa31cfa]
  [bt] (7) /home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/libdgl.so(+0x8adde4) [0x7f977fa31de4]
  [bt] (8) /home/noone/anaconda3/envs/tf_test/lib/python3.6/site-packages/dgl-0.2-py3.6-linux-x86_64.egg/dgl/libdgl.so(DGLFuncCall+0x62) [0x7f977f9e2ce2]

## Environment

 - DGL Version (e.g., 0.2):
 - Backend Library & Version (e.g., PyTorch 1.1.0):
 - OS (e.g., Linux 18.04):
 - How you installed DGL (source):
 - Build command you used (if compiling from source):
`
mkdir build
cd build
cmake ..
make -j4
`
 - Python version:
 - CUDA/cuDNN version (if applicable): CUDA 10.2
 - GPU models and configuration (e.g. V100): GTX 1080Ti
 - Any other relevant information:

**Comment by yangysc** [comment]
It turns that I do not the the cuda in the CMakefile.txt when building the project..

**Comment by bigheiniu** [comment]
So we should rebuild the project by change the makefile???

**Comment by jermainewang** [comment]
Please read the get started page for how to install GPU enabled dgl. https://www.dgl.ai/pages/start.html

**Comment by yzh119** [comment]
@bigheiniu if you want to build dgl from source, please follow our instruction https://docs.dgl.ai/install/index.html#install-from-source, you don't have to change makefile.
If you just need to install dgl with gpu support, please select correct cuda versions in our start page: https://www.dgl.ai/pages/start.html.
