### ISSUE TITLE
dataloader causes RuntimeError: CUDA error: unspecified launch failure

### ISSUE THREAD

**Issue by wzm2256** [dmlc/dgl#6473]
## 🐛 Bug

This bug appears several times and is claimed to be fixed several times. https://github.com/dmlc/dgl/issues/4134 https://github.com/dmlc/dgl/issues/4340 but it still exists. Dataloader is a fundamental class so this bug is rather urgent.

## To Reproduce
```
import dgl
from torch import nn
import torch
from dgl.data import DGLDataset

class Trivial(nn.Module):
    def __init__(self):
        super().__init__()
        self.my_param = nn.Parameter(torch.randn((3, 3)))

    def forward(self, feature_dict, g=None):
        pass


class GraphDataset(DGLDataset):
	def __init__(self):
		super().__init__(name="MugGraph")

	def __getitem__(self, i):
		return dgl.knn_graph(torch.randn((100, 3)), 2), torch.randn((3, 3))

	def __len__(self):
		return 20

def main():
	# Prepare data
	train_dataset = GraphDataset()

	train_loader = dgl.dataloading.GraphDataLoader(train_dataset, batch_size=2, shuffle=False, drop_last=False, num_workers=2)

	model_all = Trivial()
	model_all.to('cuda') # if you remove this line, then everything is OK, otherwise not.
 

	for i, (g1, t) in enumerate(train_loader):
		gt = t.to('cuda')

if __name__ == '__main__':
	main()
```

```
Traceback (most recent call last):
  File "/home/wzm/MyCode/BiEq/debug.py", line 51, in <module>
    main()
  File "/home/wzm/MyCode/BiEq/debug.py", line 42, in main
    r_gt = t.to('cuda')
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

## Environment
I tried this in several environment, several backend pytorch version, but it always exists.

 - DGL Version (e.g., 1.0):   1.1.0.cu117 
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):  pytorch 2.0.0 
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source): conda 
 - Build command you used (if compiling from source):
 - Python version: 3.10
 - CUDA/cuDNN version (if applicable):  117 
 - GPU models and configuration (e.g. V100): T4, 1060s, Titan, A40
 - Any other relevant information:

## Additional context
Any work around is appreciated! I have been stucked here for several days!

**Comment by wzm2256** [comment]
The problem exists as long as a graph is created in a dataset class. Even the graph is not returned, and even for a torch dataset and torch dataloader. That is rediculous. Is there a way to load dgl graphs at all?

```
import dgl
from torch import nn
import torch
from torch.utils.data import DataLoader

class Trivial(nn.Module):
	def __init__(self):
		super().__init__()
		self.my_param = nn.Parameter(torch.randn((3, 3)))

	def forward(self, feature_dict, g=None):
		pass


class GraphDataset(torch.utils.data.Dataset):
	def __init__(self):
		super().__init__()

	def __getitem__(self, i):
		g = dgl.graph((torch.tensor([2, 3, 4]), torch.tensor([1, 2, 3])))
		return torch.randn((3, 3)), torch.randn((3, 3))

	def __len__(self):
		return 20

def main():
	train_dataset = GraphDataset()
	train_loader = DataLoader(train_dataset, batch_size=2, shuffle=True, num_workers=1, drop_last=True)

	model_all = Trivial()
	model_all.to('cuda')  # if you remove this line, then everything is OK, otherwise not.

	for i, (g1, t) in enumerate(train_loader):
		gt = t.to('cuda')


if __name__ == '__main__':
	main()
```

```
Traceback (most recent call last):
  File "/home/wzm/MyCode/BiEq/dgl_debug.py", line 40, in <module>
    main()
  File "/home/wzm/MyCode/BiEq/dgl_debug.py", line 36, in main
    gt = t.to('cuda')
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by wzm2256** [comment]
Sorry, this is the same bug as here https://github.com/dmlc/dgl/issues/6375. Sadly it looks that it won't be solved in a short time.

**Comment by wzm2256** [comment]
I now close this issue. A workaround is to use dgl-1.0.2+cu118 as pointed out in https://github.com/dmlc/dgl/issues/6375 .
