### ISSUE TITLE
[Example] Many examples are failed with later version of numpy

### ISSUE THREAD

**Issue by chang-l** [dmlc/dgl#6539]
## 🐛 Bug

With a later version of numpy (e.g., 1.24.4), many examples are failed and need to be updated. They are:
https://github.com/dmlc/dgl/tree/master/examples/pytorch/ogb/cluster-gat
https://github.com/dmlc/dgl/tree/master/examples/pytorch/ogb/cluster-sage
https://github.com/dmlc/dgl/tree/master/examples/pytorch/bgnn
https://github.com/dmlc/dgl/tree/master/examples/pytorch/gas
https://github.com/dmlc/dgl/tree/master/examples/pytorch/grace

## To Reproduce
```
pip install numpy==1.24.4
# run those examples:
bash test.sh
```

For `cluster-gat` and `cluster-sage`, the error is:
```
  File ".../dgl/examples/pytorch/ogb/cluster-gat/sampler.py", line 36, in __init__
    np.save(fn, self.par_li)
  File "<__array_function__ internals>", line 200, in save
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 521, in save
    arr = np.asanyarray(arr)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (15000,) + inhomogeneous part.
```
For other failures, the errors are like:
```
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
```

## Environment

 - DGL Version (e.g., 1.0): DGL 1.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 2.1
 - OS (e.g., Linux): ubuntu 
 - Numpy version:  1.24.4
 - How you installed DGL (`conda`, `pip`, source): source

**Comment by yxy235** [comment]
@chang-l May I ask you about what is the problem with running this [grace example](https://github.com/dmlc/dgl/tree/master/examples/pytorch/grace)? I didn't catch error when running it.

**Comment by chang-l** [comment]
Hi @yxy235 , for GRACE example, here is the stack trace:
```=== Final ===
Traceback (most recent call last):
  File "/workspace/examples/grace/main.py", line 134, in <module>
    label_classification(
  File "/opt/dgl/dgl-source/examples/pytorch/grace/eval.py", line 20, in wrapper
    results = [f(*args, **kwargs) for _ in range(n_times)]
  File "/opt/dgl/dgl-source/examples/pytorch/grace/eval.py", line 20, in <listcomp>
    results = [f(*args, **kwargs) for _ in range(n_times)]
  File "/opt/dgl/dgl-source/examples/pytorch/grace/eval.py", line 64, in label_classification
    Y = onehot_encoder.transform(Y).toarray().astype(np.bool)
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?

```
