### ISSUE TITLE
[GraphBolt] `RuntimeError: CUDA error: initialization error` in `sample_neighbors()` when num_workers > 0

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#6921]
## To Reproduce

1. build CUDA version upon DGL 2.0.x branch or install latest nightly build DGL.
2. run `DGL_HOME=/home/ubuntu/workspace/dgl_0 DGL_LIBRARY_PATH=$DGL_HOME/build PYTHONPATH=tools:tools/distpartitioning:tests:$DGL_HOME/python:tests/python/pytorch/graphbolt:$PYTHONPATH python3 examples/sampling/graphbolt/node_classification.py --num-workers 5 --device cpu`

```
Training in cpu mode.
Loading data...
The dataset is already preprocessed.
Training...
Traceback (most recent call last):
  File "/home/ubuntu/workspace/dgl_0/examples/sampling/graphbolt/node_classification.py", line 410, in <module>
    main(args)
  File "/home/ubuntu/workspace/dgl_0/examples/sampling/graphbolt/node_classification.py", line 392, in main
    train(args, graph, features, train_set, valid_set, num_classes, model)
  File "/home/ubuntu/workspace/dgl_0/examples/sampling/graphbolt/node_classification.py", line 292, in train
    for step, data in enumerate(dataloader):
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 41, in fetch
    data = next(self.dataset_iter)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 154, in __next__
    return self._get_next()
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 142, in _get_next
    result = next(self.iterator)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 226, in wrap_next
    result = next_func(*args, **kwargs)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/datapipe.py", line 381, in __next__
    return next(self._datapipe_iter)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 183, in wrap_generator
    response = gen.send(None)
  File "/home/ubuntu/workspace/dgl_0/python/dgl/graphbolt/base.py", line 162, in __iter__
    for data in self.datapipe:
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 183, in wrap_generator
    response = gen.send(None)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torchdata/datapipes/iter/util/prefetcher.py", line 103, in __iter__
    raise data
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torchdata/datapipes/iter/util/prefetcher.py", line 73, in thread_worker
    item = next(itr)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 183, in wrap_generator
    response = gen.send(None)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/iter/callable.py", line 122, in __iter__
    for data in self.datapipe:
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 183, in wrap_generator
    response = gen.send(None)
  File "/home/ubuntu/workspace/dgl_0/python/dgl/graphbolt/dataloader.py", line 64, in __iter__
    yield from self.dataloader
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 41, in fetch
    data = next(self.dataset_iter)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 154, in __next__
    return self._get_next()
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 142, in _get_next
    result = next(self.iterator)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 226, in wrap_next
    result = next_func(*args, **kwargs)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/datapipe.py", line 381, in __next__
    return next(self._datapipe_iter)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/_hook_iterator.py", line 183, in wrap_generator
    response = gen.send(None)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/iter/callable.py", line 123, in __iter__
    yield self._apply_fn(data)
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/iter/callable.py", line 88, in _apply_fn
    return self.fn(data)
  File "/home/ubuntu/workspace/dgl_0/python/dgl/graphbolt/minibatch_transformer.py", line 38, in _transformer
    minibatch = self.transformer(minibatch)
  File "/home/ubuntu/workspace/dgl_0/python/dgl/graphbolt/subgraph_sampler.py", line 57, in _sample
    ) = self.sample_subgraphs(seeds)
  File "/home/ubuntu/workspace/dgl_0/python/dgl/graphbolt/impl/neighbor_sampler.py", line 138, in sample_subgraphs
    subgraph = self.sampler(
  File "/home/ubuntu/workspace/dgl_0/python/dgl/graphbolt/impl/fused_csc_sampling_graph.py", line 557, in sample_neighbors
    C_sampled_subgraph = self._sample_neighbors(
  File "/home/ubuntu/workspace/dgl_0/python/dgl/graphbolt/impl/fused_csc_sampling_graph.py", line 657, in _sample_neighbors
    return self._c_csc_graph.sample_neighbors(
RuntimeError: CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

This exception is thrown by __iter__ of NeighborSampler(datapipe=ShardingFilterIterDataPipe, deduplicate=True, fanouts=[tensor([10]), tensor([10]), tensor([10])], graph=FusedCSCSamplingGraph(csc_indptr=tensor([        0,       174,       263,  ..., 123718233, 123718242,
                                         123718280]),
                      indices=tensor([152857,  32104,  23158,  ...,  18965, 162836,  53324]),
                      num_nodes=2449029, num_edges=123718280, edge_attributes={}), prob_name=None, replace=False)
```

## Environment

 - DGL Version (e.g., 1.0): 2.0.0, nightly
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 2.1
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable): 12.1
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
cpu only DGL works well with `num_workers>0, --device cpu`.

**Comment by mfbalin** [comment]
Probably related: https://pytorch.org/docs/master/notes/multiprocessing.html#cuda-in-multiprocessing
I don't know if there is a way to stop CUDA from being initialized when not using it. I will do some research on it.

**Comment by mfbalin** [comment]
Also related:
https://github.com/dmlc/dgl/blob/master/tests/python/pytorch/graphbolt/test_dataloader.py#L13

**Comment by mfbalin** [comment]
I identified the issue. When we are dispatching to the GPU, we check two things, whether the tensors are pinned or whether they are on CUDA. I verified that changing this function:
https://github.com/dmlc/dgl/blob/4323986b25ce5c6d0ced0a6db5550402740aeb99/graphbolt/src/utils.h#L18-L20
To
```python
return tensor.device().type() == c10::DeviceType::CUDA;
```
resolves the issue.

**Comment by mfbalin** [comment]
However, we need to figure out how to do the dispatch when it is one of the dataloader workers. Maybe we can mark each of the launched processes by a global variable which can be checked inside this function so that we don't check if tensors are pinned if they are dataloader workers.

**Comment by mfbalin** [comment]
If `is_dataloader_worker` indicates whether the process is a dataloader process, then the is_pinned check can be avoided as follows:
```python
 inline bool is_accessible_from_gpu(torch::Tensor tensor) { 
   return (!is_dataloader_worker && tensor.is_pinned()) || tensor.device().type() == c10::DeviceType::CUDA; 
 } 
 ```

**Comment by mfbalin** [comment]
That is if we don't want to add `mp.set_start_method("spawn")` to main for all examples or into the dataloader for when cuda is available in the system.

**Comment by mfbalin** [comment]
Found a better solution, opening a PR.
