### ISSUE TITLE
OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by yonatansverdlov** [dmlc/dgl#7046]
I did the following steps: 

1. conda create --name dgl -c conda-forge python=3.11
2. conda install -c dglteam/label/cu121 dgl
3. conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
4. conda activate dgl
5. 5. import dgl
And have OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found.
I run on a10 gpu.

**Comment by BarclayII** [comment]
What is your OS?

**Comment by yonatansverdlov** [comment]
linux

‫בתאריך יום ד׳, 31 בינו׳ 2024 ב-10:07 מאת ‪Quan (Andy) Gan‬‏ <‪
***@***.***‬‏>:‬

**Comment by BarclayII** [comment]
Sorry, I meant what is your Linux distro and version number?  (Ubuntu 20.04, CentOS 7, etc.)

**Comment by Rhett-Ying** [comment]
@yonatansverdlov pls note that ubuntu20.04/CentOS8/RHEL8 or above are required since DGL 2.0

**Comment by Rhett-Ying** [comment]
could you run below commands on your system and share the outputs?
1. `ldd --version`
2. `which ldd`
3. `uname -a`

And could you try to install via pip: `pip install  dgl -f https://data.dgl.ai/wheels/cu121/repo.html`?

**Comment by yonatansverdlov** [comment]
ldd (Ubuntu GLIBC 2.31-0ubuntu9.14) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

/usr/bin/ldd

Linux newton 5.4.0-169-generic #187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023
x86_64 x86_64 x86_64 GNU/Linux

After installing using pip I still have: OSError: /lib64/libm.so.6: version
`GLIBC_2.27' not found


‫בתאריך יום ו׳, 2 בפבר׳ 2024 ב-3:05 מאת ‪Rhett Ying‬‏ <‪
***@***.***‬‏>:‬

**Comment by Rhett-Ying** [comment]
On my ubuntu 20.04, `libm` is found below which links with GLIBC 2.31, not 2.27. could you confirm your lib? and have you ever built math lib on your own?
```
ls -lh /lib/x86_64-linux-gnu/libm.so.6
```
```
lrwxrwxrwx 1 root root 12 Nov 22 13:32 /lib/x86_64-linux-gnu/libm.so.6 -> libm-2.31.so
```

**Comment by yonatansverdlov** [comment]
Not sure, could you please detail what to check/try in more detailed manner?

בתאריך יום א׳, 4 בפבר׳ 2024 ב-4:31 מאת Rhett Ying ***@***.***

**Comment by yonatansverdlov** [comment]
By the way, the pip install dgl -f
https://data.dgl.ai/wheels/cu121/repo.html installation fails also on the
colab.

‫בתאריך יום א׳, 4 בפבר׳ 2024 ב-15:05 מאת יונתן סברדלוב <‪
***@***.***‬‏>:‬

**Comment by yonatansverdlov** [comment]
By the way, the pip install dgl -f https://data.dgl.ai/wheels/cu121/repo.html installation fails also on the colab.
After installtion when I write import dgl.sparse, it returns ImportError: Cannot load DGL C++ sparse library

**Comment by Rhett-Ying** [comment]
1. first locate your `libm.so` and check if it links to 2.27 instead of 2.31: `ls -lh /lib/x86_64-linux-gnu/libm.so.6`
2. As for the collab issue, could you confirm which torch version you're using for now?

**Comment by yonatansverdlov** [comment]
1. After ls -lh /lib/x86_64-linux-gnu/libm.so.6 the ldd version is 2.31
2. 2.1.0+cu121

‫בתאריך יום ב׳, 5 בפבר׳ 2024 ב-11:07 מאת ‪Rhett Ying‬‏ <‪
***@***.***‬‏>:‬

**Comment by Rhett-Ying** [comment]
> By the way, the pip installs dgl -f https://data.dgl.ai/wheels/cu121/repo.html installation also fails on the collab. After installation, when I write import dgl.sparse, it returns ImportError: Cannot load DGL C++ sparse library

I tried with collab(T4 GPU) and it works well. `!pip install dgl -f https://data.dgl.ai/wheels/cu121/repo.html`

**Comment by RemyLau** [comment]
I'm having the same issue after upgrading to `dgl 2.0.0`, downgrading to `dgl 1.1.3` fixes the issue

**Comment by parva93** [comment]
I am having similar issues. I by mistake deleted older version (based on cuda) and now it is hard to use the newer version as on our university cluster the version of GLibc is 2.17. And workaround for this issue? Or how to download the cuda based older versions of dgl?

**Comment by Rhett-Ying** [comment]
@parva93 `2.17` is too old. what's your OS and version? could you try build from source on your own? please refer to https://docs.dgl.ai/install/index.html#install-from-source.

**Comment by HouyuZhang1007** [comment]
```
(iefm_0531) [zhanhouy@ip-10-0-69-26]~/workspace/MFiveLib/mfive/apps/iefm% python
Python 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21) 
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dgl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhanhouy/.conda/envs/iefm_0531/lib/python3.9/site-packages/dgl/__init__.py", line 14, in <module>
    from .backend import backend_name, load_backend  # usort: skip
  File "/home/zhanhouy/.conda/envs/iefm_0531/lib/python3.9/site-packages/dgl/backend/__init__.py", line 122, in <module>
    load_backend(get_preferred_backend())
  File "/home/zhanhouy/.conda/envs/iefm_0531/lib/python3.9/site-packages/dgl/backend/__init__.py", line 51, in load_backend
    from .._ffi.base import load_tensor_adapter  # imports DGL C library
  File "/home/zhanhouy/.conda/envs/iefm_0531/lib/python3.9/site-packages/dgl/_ffi/base.py", line 50, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
  File "/home/zhanhouy/.conda/envs/iefm_0531/lib/python3.9/site-packages/dgl/_ffi/base.py", line 39, in _load_lib
    lib = ctypes.CDLL(lib_path[0])
  File "/home/zhanhouy/.conda/envs/iefm_0531/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/zhanhouy/.conda/envs/iefm_0531/lib/python3.9/site-packages/dgl/libdgl.so)
```
I met the same issue. Any way to resolve it?

**Comment by HouyuZhang1007** [comment]
```
(iefm_0531) [zhanhouy@ip-10-0-69-26]~/workspace/MFiveLib/mfive/apps/iefm% ldd --version
ldd (GNU libc) 2.26
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
Above is the GLIBC version of my OS.

**Comment by Rhett-Ying** [comment]
@HouyuZhang1007 which OS version are you working on? GLIBC 2.26 is not supported in latest DGL versions.

**Comment by HouyuZhang1007** [comment]
Please see my OS version below:
```
(iefm_0531) [zhanhouy@ip-10-0-69-26]~/workspace/MFiveLib/mfive/apps/iefm% cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
```
What is the latest DGL version that supports GLIBC 2.26?

**Comment by Rhett-Ying** [comment]
For anyone who hits the `OSError: /lib64/libm.so.6: version 'GLIBC_2.27' not found`, please try with below DGL packages. please update the path according to the torch version you're using. It's pre-release version of `DGL 2.3.1`.

```
pip install dgl -f https://data.dgl.ai/wheels-internal/torch-2.3/cu121/repo.html
```

**Comment by Rhett-Ying** [comment]
I've downgraded the base image from ubi8 to ubi7 for the nightly build. So the minimum required GLIBC version is 2.17 now. Please feel free to try with the latest nightly build packages: `pip install --pre dgl -f https://data.dgl.ai/wheels-test/torch-2.3/repo.html`

**Comment by Tobias-Lin** [comment]
HI~ @Rhett-Ying, thank you for your update.
My GLibc is 2.17. I tried installing the latest nightly build packagge using the command you provided:
`pip install --pre dgl -f https://data.dgl.ai/wheels-test/torch-2.3/repo.html`

However, I'm still encountering the same issue with GLIBC version requrements:
`OSError: /lib64/libm.so.6: version ;GLIBC_2.27' not found`

so i check the dependencies of `libdgl.so`
`ldd /.....lib/python_3.9/site-packages/dgl/libdgl.so`

and still get
`/lib64/libm.so.6: version 'GLIBC_2.27' not found(required by .....)`

My system is Linux RHEL7.7, python3.9.10, torch2.3.1.
Could you take a look for me? Thanks a lot!

**Comment by wxbs** [comment]
Thanks for your nice work! It seems that I don't have the file "x86_64-linux-gnu/libm.so.6". Please help! Your early reply will be highly appreciated!
