### ISSUE TITLE
Issue with DGL import using conda

### ISSUE THREAD

**Issue by DominikaJedynak** [dmlc/dgl#7058]
## 🐛 Bug

After importing DGL library using conda (following the instruction from: https://www.dgl.ai/pages/start.html), some error occurs when trying to import dgl library in python file.

## To Reproduce

1. _conda create --name dgl_conda  python=3.10_
2. _conda activate dgl_conda_
3. _conda install -c dglteam dgl_
4. from python: _import dgl_

## Error message
```
>>> import dgl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dominika/miniconda3/envs/dgl_conda/lib/python3.10/site-packages/dgl/__init__.py", line 14, in <module>
    from .backend import backend_name, load_backend  # usort: skip
  File "/home/dominika/miniconda3/envs/dgl_conda/lib/python3.10/site-packages/dgl/backend/__init__.py", line 122, in <module>
    load_backend(get_preferred_backend())
  File "/home/dominika/miniconda3/envs/dgl_conda/lib/python3.10/site-packages/dgl/backend/__init__.py", line 51, in load_backend
    from .._ffi.base import load_tensor_adapter  # imports DGL C library
  File "/home/dominika/miniconda3/envs/dgl_conda/lib/python3.10/site-packages/dgl/_ffi/base.py", line 50, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
  File "/home/dominika/miniconda3/envs/dgl_conda/lib/python3.10/site-packages/dgl/_ffi/base.py", line 39, in _load_lib
    lib = ctypes.CDLL(lib_path[0])
  File "/home/dominika/miniconda3/envs/dgl_conda/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/dominika/miniconda3/envs/dgl_conda/lib/python3.10/site-packages/dgl/libdgl.so: ELF load command address/offset not properly aligned
```

## Environment

 - DGL Version (e.g., 1.0): 2.0.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 2.2.0
 - OS (e.g., Linux): Ubuntu 20.04 LTS
 - How you installed DGL (`conda`, `pip`, source): conda
 - Python version: 3.10

**Comment by Rhett-Ying** [comment]
1. could you try to install with pip instead of conda?
2. what is the GLIBC version on your machine? `ldd --vesiion`

**Comment by Rhett-Ying** [comment]
I have updated the conda packages. could you try again? @DominikaJedynak

**Comment by DominikaJedynak** [comment]
Thanks, it works for me now.
