### ISSUE TITLE
Error running `bench_graphbolt_uva_index_select_csc.py`

### ISSUE THREAD

**Issue by yxy235** [dmlc/dgl#7301]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

When running this benchmark with these attributes `track_throughput(20000000, 256, "cpu", torch.int32, Regularity.IRREGULAR, 1000)` on `g5.8xlarge`, I have had this problem.

**Environment**
Python: 3.10
Pytorch: 2.0.0
cuda: 11.7

**Error**
```
Traceback (most recent call last):
  File "/home/ubuntu/DGL_scripts/regression/benchmarks/api/bench_graphbolt_uva_index_select_csc.py", line 178, in <module>
    track_throughput(20000000, 256, "cpu", torch.int32, Regularity.IRREGULAR, 1000)
  File "/home/ubuntu/DGL_scripts/regression/benchmarks/api/bench_graphbolt_uva_index_select_csc.py", line 172, in track_throughput
    _, throughput = test_random(num_nodes, degree, device, idtype, regular, indices_size)
  File "/home/ubuntu/DGL_scripts/regression/benchmarks/api/bench_graphbolt_uva_index_select_csc.py", line 148, in test_random
    runtime, throughput = test_index_select_csc(**params_dict)
  File "/home/ubuntu/DGL_scripts/regression/benchmarks/api/bench_graphbolt_uva_index_select_csc.py", line 99, in test_index_select_csc
    torch.ops.graphbolt.index_select_csc(indptr, indices, index, None)
  File "/home/ubuntu/miniconda3/envs/dgl-dev-gpu-117/lib/python3.10/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by mfbalin** [comment]
Please see https://github.com/dglai/DGL_scripts/issues/195

**Comment by mfbalin** [comment]
I don't have access to the benchmark repository, could you do the fix for me? I already found the potential solution there.

**Comment by Rhett-Ying** [comment]
https://github.com/dglai/DGL_scripts/pull/197
