### ISSUE TITLE
[torchdata] 

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#7380]
## To Reproduce
This issue happens on `torch 2.3.0`. A [fix](https://github.com/pytorch/pytorch/pull/122616) is merged into torch, but not integrated into `2.3.0` as mentioned in https://github.com/pytorch/data/issues/1244.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/dgl/__init__.py", line 16, in <module>
    from . import (
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/dgl/dataloading/__init__.py", line 13, in <module>
    from .dataloader import *
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/dgl/dataloading/dataloader.py", line 27, in <module>
    from ..distributed import DistGraph
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/dgl/distributed/__init__.py", line 5, in <module>
    from .dist_graph import DistGraph, DistGraphServer, edge_split, node_split
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/dgl/distributed/dist_graph.py", line 11, in <module>
    from .. import backend as F, graphbolt as gb, heterograph_index
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/dgl/graphbolt/__init__.py", line 39, in <module>
    from .base import *
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/dgl/graphbolt/base.py", line 9, in <module>
    from torchdata.datapipes.iter import IterDataPipe
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torchdata/__init__.py", line 9, in <module>
    from . import datapipes
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torchdata/datapipes/__init__.py", line 9, in <module>
    from . import iter, map, utils
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torchdata/datapipes/iter/__init__.py", line 79, in <module>
    from torchdata.datapipes.iter.util.cacheholder import (
  File "/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torchdata/datapipes/iter/util/cacheholder.py", line 24, in <module>
    from torch.utils.data.datapipes.utils.common import _check_unpickable_fn, DILL_AVAILABLE
ImportError: cannot import name 'DILL_AVAILABLE' from 'torch.utils.data.datapipes.utils.common' (/opt/conda/envs/dgl-dev-gpu-dgl-0/lib/python3.10/site-packages/torch/utils/data/datapipes/utils/common.py)
```

## Environment

 - DGL Version (e.g., 1.0): master
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 2.3.0
 - OS (e.g., Linux): Linux
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by mfbalin** [comment]
#7362 related.

**Comment by Rhett-Ying** [comment]
> #7362 related.

yes. we may hit other similar issues in the future due to the project status of `torchdata`.  :(
