### ISSUE TITLE
[GraphBolt][MultiGPU] Error occurs when running multiGPU example with `num-workers` > 0

### ISSUE THREAD

**Issue by Skeleton003** [dmlc/dgl#7381]
## 🔨Work Item

**IMPORTANT:**
* This template is only for dev team to track project progress. For feature request or bug report, please use the corresponding issue templates.
* DO NOT create a new work item if the purpose is to fix an existing issue or feature request. We will directly use the issue in the project tracker.

Project tracker: https://github.com/orgs/dmlc/projects/2

## Description

When running `python examples/multigpu/graphbolt/node_classification.py --num-workers=2` (2 could be any number greater than 0), this error is raised within every distributed replica:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/dgl/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/ubuntu/miniconda3/envs/dgl/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/ubuntu/miniconda3/envs/dgl/lib/python3.9/site-packages/torch/utils/data/datapipes/datapipe.py", line 359, in __setstate__
    self._datapipe = dill.loads(value)
  File "/home/ubuntu/miniconda3/envs/dgl/lib/python3.9/site-packages/dill/_dill.py", line 303, in loads
    return load(file, ignore, **kwds)
  File "/home/ubuntu/miniconda3/envs/dgl/lib/python3.9/site-packages/dill/_dill.py", line 289, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "/home/ubuntu/miniconda3/envs/dgl/lib/python3.9/site-packages/dill/_dill.py", line 444, in load
    obj = StockUnpickler.load(self)
AttributeError: 'PyCapsule' object has no attribute 'cudaHostUnregister'
```

**Comment by frozenbugs** [comment]
By default it is using CUDA sampling, not sure how num_workers parameter work with it. @mfbalin might know?

**Comment by Skeleton003** [comment]
@mfbalin Hello Fatih, could you please give me a hand on this issue? I've been investigating it for a while but got no clue at all. The error message indicates it's related to cuda, and your expertise in cuda may help a lot in resolving this issue.

**Comment by mfbalin** [comment]
num workers argument is always passed into MultiProcessingWrapper in dataloader.py before FeatureFetcher. But if sampling is performed on the GPU, then multiple workers will perform GPU sampling. Right now, there is no way for multiple processes to initialize the CUDA context, it always gives a runtime error.

**Comment by mfbalin** [comment]
I would expect no error if we use CPU sampling but GPU feature fetching.

**Comment by Skeleton003** [comment]
> I would expect no error if we use CPU sampling but GPU feature fetching for example.

You're right. After I set `--mode=cpu-cuda`, the error doesn't occur.

Result:
num-gpu=4, num-workers=0
```
$ python /home/ubuntu/dgl/examples/multigpu/graphbolt/node_classification.py --gpu 0,1,2,3 --num-workers 0 --mode cpu-cuda
Training with 4 gpus.
The dataset is already preprocessed.
Training...
48it [00:07,  6.02it/s]
Validating...
10it [00:01,  6.73it/s]
Epoch 00000 | Average Loss 2.3673 | Accuracy 0.7817 | Time 9.5063
48it [00:06,  7.22it/s]
Validating...
10it [00:01,  7.38it/s]
Epoch 00001 | Average Loss 0.9844 | Accuracy 0.8414 | Time 8.0284
48it [00:06,  7.09it/s]
Validating...
10it [00:01,  7.40it/s]
Epoch 00002 | Average Loss 0.7432 | Accuracy 0.8579 | Time 8.1474
48it [00:07,  6.79it/s]
Validating...
10it [00:01,  7.33it/s]
Epoch 00003 | Average Loss 0.6331 | Accuracy 0.8691 | Time 8.4613
48it [00:06,  7.31it/s]
Validating...
10it [00:01,  6.92it/s]
Epoch 00004 | Average Loss 0.5717 | Accuracy 0.8759 | Time 8.0768
48it [00:06,  7.14it/s]
Validating...
10it [00:01,  7.38it/s]
Epoch 00005 | Average Loss 0.5314 | Accuracy 0.8810 | Time 8.2336
48it [00:06,  6.89it/s]
Validating...
10it [00:01,  7.04it/s]
Epoch 00006 | Average Loss 0.4993 | Accuracy 0.8837 | Time 8.4067
48it [00:06,  7.19it/s]
Validating...
10it [00:01,  9.87it/s]
Epoch 00007 | Average Loss 0.4773 | Accuracy 0.8863 | Time 8.1699
48it [00:06,  7.52it/s]
Validating...
10it [00:01,  6.93it/s]
Epoch 00008 | Average Loss 0.4582 | Accuracy 0.8896 | Time 7.8546
48it [00:06,  7.52it/s]
Validating...
10it [00:01,  6.81it/s]
Epoch 00009 | Average Loss 0.4425 | Accuracy 0.8900 | Time 7.8795
Testing...
541it [00:50, 10.68it/s]
Test Accuracy 0.7352
```

num-gpu=4, numworkers=2
```
$ python /home/ubuntu/dgl/examples/multigpu/graphbolt/node_classification.py --gpu 0,1,2,3 --num-workers 2 --mode cpu-cuda
Training with 4 gpus.
The dataset is already preprocessed.
Training...
48it [00:25,  1.86it/s]
Validating...
10it [00:13,  1.38s/it]
Epoch 00000 | Average Loss 2.3917 | Accuracy 0.7787 | Time 40.1520
48it [00:14,  3.26it/s]
Validating...
10it [00:03,  3.01it/s]
Epoch 00001 | Average Loss 0.9744 | Accuracy 0.8389 | Time 18.2313
48it [00:15,  3.12it/s]
Validating...
10it [00:03,  3.06it/s]
Epoch 00002 | Average Loss 0.7396 | Accuracy 0.8581 | Time 18.6571
48it [00:14,  3.21it/s]
Validating...
10it [00:03,  3.06it/s]
Epoch 00003 | Average Loss 0.6351 | Accuracy 0.8689 | Time 18.2657
48it [00:15,  3.13it/s]
Validating...
10it [00:03,  2.95it/s]
Epoch 00004 | Average Loss 0.5724 | Accuracy 0.8758 | Time 18.7767
48it [00:15,  3.15it/s]
Validating...
10it [00:03,  2.94it/s]
Epoch 00005 | Average Loss 0.5288 | Accuracy 0.8792 | Time 18.6821
48it [00:15,  3.16it/s]
Validating...
10it [00:03,  3.02it/s]
Epoch 00006 | Average Loss 0.4968 | Accuracy 0.8831 | Time 18.5221
48it [00:14,  3.27it/s]
Validating...
10it [00:03,  3.04it/s]
Epoch 00007 | Average Loss 0.4751 | Accuracy 0.8873 | Time 18.0010
48it [00:15,  3.13it/s]
Validating...
10it [00:03,  3.06it/s]
Epoch 00008 | Average Loss 0.4564 | Accuracy 0.8891 | Time 18.9161
48it [00:15,  3.19it/s]
Validating...
10it [00:03,  3.10it/s]
Epoch 00009 | Average Loss 0.4421 | Accuracy 0.8915 | Time 18.5745
Testing...
541it [02:17,  3.95it/s]
Test Accuracy 0.7370
```

**Comment by Skeleton003** [comment]
It turns out that, for mode `pinned-cuda` and `cuda-cuda`, setting `num-workers` > 0 will lead to error. And for mode `cpu-cuda`, setting `num-workers` > 0 will lead to increased time consuming. It's always better to set `num-workers` = 0. Therefore, should we disable this argument and hardcode it as 0? @frozenbugs @mfbalin

**Comment by mfbalin** [comment]
It is up to you. I think @peizhou001 has better knowledge about when the num_workers argument is useful.

**Comment by mfbalin** [comment]
If you check the pyg advanced example, it is possible to use CPU for sampling and pinned for feature fetching and GPU for training. We might want to add these additional options to the multiGPU example as well.

**Comment by frozenbugs** [comment]
I think we can leave it as it is for now.
