### ISSUE TITLE
Failed to import graphbolt due to `libgraphbolt_pytorch_2.3.0.post300.so`

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#7438]
## 🐛 Bug

Somehow `post300` is appended for the target so name which results in failure to find it as the expected name is `libgraphbolt_pytorch_2.3.0.so`.
See more details in https://discuss.dgl.ai/t/filenotfounderror-cannot-find-dgl-c-graphbolt-library-in-dgl-2-2-1-and-pytorch-2-3-0/4419
## To Reproduce

1. conda install DGL package for torch 2.3.0.

## Environment

 - DGL Version (e.g., 1.0): DGL 2.2.1
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 2.3.0
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by alexbarghi-nv** [comment]
I'm also seeing this bug - any update?

**Comment by Rhett-Ying** [comment]
This issue is not handled yet.

**Comment by alexbarghi-nv** [comment]
I think I've partly figured out the source of this bug - I tried installing again with PyTorch from the `pytorch` channel instead of `conda-forge` and that resolved the issue.  There's probably a different version string or something similar in the `conda-forge` distribution which is causing this.

**Comment by Davidxswang** [comment]
I am also see this bug, installed dlg from pip, 2.2.1+cu121, for torch 2.2.2+cu121. Also tried for torch 2.3.x, not working.

**Comment by Rhett-Ying** [comment]
> I am also see this bug, installed dlg from pip, 2.2.1+cu121, for torch 2.2.2+cu121. Also tried for torch 2.3.x, not working.

Did you install torch with pip or conda from `conda-forge`?

**Comment by Rhett-Ying** [comment]
Seems it's a common issue, we could add a reg check when loading graphbolt.

**Comment by Davidxswang** [comment]
> > I am also see this bug, installed dlg from pip, 2.2.1+cu121, for torch 2.2.2+cu121. Also tried for torch 2.3.x, not working.
> 
> Did you install torch with pip or conda from `conda-forge`?

I installed torch with pip

**Comment by Rhett-Ying** [comment]
@Davidxswang  could you share your pip install command? and what is the version if check with `pip list|grep torch` and `torch.__version__` in your case?

**Comment by Davidxswang** [comment]
> @Davidxswang could you share your pip install command? and what is the version if check with `pip list|grep torch` and `torch.__version__` in your case?



`pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu121

```
pytorch-lightning            2.2.1
torch                        2.2.2+cu121
torch_geometric              2.5.2
torchaudio                   2.2.2+cu121
torchdata                    0.7.1
torchmetrics                 1.3.2
torchvision                  0.17.2+cu121
```


```
In [2]: torch.__version__
Out[2]: '2.2.2+cu121' 
```

**Comment by Silhouettes-of-U** [comment]
I got a similar error while without `post300` appended:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.8/site-packages/dgl/__init__.py", line 16, in <module>
    from . import (
  File "/root/miniconda3/lib/python3.8/site-packages/dgl/dataloading/__init__.py", line 13, in <module>
    from .dataloader import *
  File "/root/miniconda3/lib/python3.8/site-packages/dgl/dataloading/dataloader.py", line 27, in <module>
    from ..distributed import DistGraph
  File "/root/miniconda3/lib/python3.8/site-packages/dgl/distributed/__init__.py", line 5, in <module>
    from .dist_graph import DistGraph, DistGraphServer, edge_split, node_split
  File "/root/miniconda3/lib/python3.8/site-packages/dgl/distributed/dist_graph.py", line 11, in <module>
    from .. import backend as F, graphbolt as gb, heterograph_index
  File "/root/miniconda3/lib/python3.8/site-packages/dgl/graphbolt/__init__.py", line 36, in <module>
    load_graphbolt()
  File "/root/miniconda3/lib/python3.8/site-packages/dgl/graphbolt/__init__.py", line 26, in load_graphbolt
    raise FileNotFoundError(
FileNotFoundError: Cannot find DGL C++ graphbolt library at /root/miniconda3/lib/python3.8/site-packages/dgl/graphbolt/libgraphbolt_pytorch_2.3.1.so`

**Comment by rfrs** [comment]
`  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.8/site-packages/dgl/__init__.py", line 16, in <module>
    from . import (
  File "/root/miniconda3/lib/python3.8/site-packages/dgl/dataloading/__init__.py", line 13, in <module>
    from .dataloader import *
  File "/root/miniconda3/lib/python3.8/site-packages/dgl/dataloading/dataloader.py", line 27, in <module>
    from ..distributed import DistGraph
  File "/root/miniconda3/lib/python3.8/site-packages/dgl/distributed/__init__.py", line 5, in <module>
    from .dist_graph import DistGraph, DistGraphServer, edge_split, node_split
  File "/root/miniconda3/lib/python3.8/site-packages/dgl/distributed/dist_graph.py", line 11, in <module>
    from .. import backend as F, graphbolt as gb, heterograph_index
  File "/root/miniconda3/lib/python3.8/site-packages/dgl/graphbolt/__init__.py", line 36, in <module>
    load_graphbolt()
  File "/root/miniconda3/lib/python3.8/site-packages/dgl/graphbolt/__init__.py", line 26, in load_graphbolt
    raise FileNotFoundError(
FileNotFoundError: Cannot find DGL C++ graphbolt library at /root/miniconda3/lib/python3.8/site-packages/dgl/graphbolt/libgraphbolt_pytorch_2.3.1.so````

We are also facing the same issue with version 2.3.1. 
Any progresses? Thank you

**Comment by Rhett-Ying** [comment]
> I got a similar error while without `post300` appended:
> 
> ```
>   File "<stdin>", line 1, in <module>
>   File "/root/miniconda3/lib/python3.8/site-packages/dgl/__init__.py", line 16, in <module>
>     from . import (
>   File "/root/miniconda3/lib/python3.8/site-packages/dgl/dataloading/__init__.py", line 13, in <module>
>     from .dataloader import *
>   File "/root/miniconda3/lib/python3.8/site-packages/dgl/dataloading/dataloader.py", line 27, in <module>
>     from ..distributed import DistGraph
>   File "/root/miniconda3/lib/python3.8/site-packages/dgl/distributed/__init__.py", line 5, in <module>
>     from .dist_graph import DistGraph, DistGraphServer, edge_split, node_split
>   File "/root/miniconda3/lib/python3.8/site-packages/dgl/distributed/dist_graph.py", line 11, in <module>
>     from .. import backend as F, graphbolt as gb, heterograph_index
>   File "/root/miniconda3/lib/python3.8/site-packages/dgl/graphbolt/__init__.py", line 36, in <module>
>     load_graphbolt()
>   File "/root/miniconda3/lib/python3.8/site-packages/dgl/graphbolt/__init__.py", line 26, in load_graphbolt
>     raise FileNotFoundError(
> FileNotFoundError: Cannot find DGL C++ graphbolt library at /root/miniconda3/lib/python3.8/site-packages/dgl/graphbolt/libgraphbolt_pytorch_2.3.1.so```
> ```

This is expected as DGL 2.2 does not support torch 2.3.1 yet. The latest supported torch version is 2.3.0

**Comment by Rhett-Ying** [comment]
@rfrs This is expected as DGL 2.2 does not support torch 2.3.1 yet. The latest supported torch version is 2.3.0

**Comment by jbm-composer** [comment]
I installed using the 2.3.x version, cuda 12.1, conda (from the DGL website), with torch 2.3.0, and I'm seeing:

```
>>> import dgl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/james/src/jbm/dgl/python/dgl/__init__.py", line 16, in <module>
    from . import (
  File "/home/james/src/jbm/dgl/python/dgl/dataloading/__init__.py", line 13, in <module>
    from .dataloader import *
  File "/home/james/src/jbm/dgl/python/dgl/dataloading/dataloader.py", line 27, in <module>
    from ..distributed import DistGraph
  File "/home/james/src/jbm/dgl/python/dgl/distributed/__init__.py", line 5, in <module>
    from .dist_graph import DistGraph, DistGraphServer, edge_split, node_split
  File "/home/james/src/jbm/dgl/python/dgl/distributed/dist_graph.py", line 12, in <module>
    from .. import backend as F, graphbolt as gb, heterograph_index
  File "/home/james/src/jbm/dgl/python/dgl/graphbolt/__init__.py", line 36, in <module>
    load_graphbolt()
  File "/home/james/src/jbm/dgl/python/dgl/graphbolt/__init__.py", line 26, in load_graphbolt
    raise FileNotFoundError(
FileNotFoundError: Cannot find DGL C++ graphbolt library at /home/james/src/jbm/dgl/python/dgl/graphbolt/libgraphbolt_pytorch_2.3.0.so
```

**Comment by Rhett-Ying** [comment]
> Are there any news on this? I'm also currently failing to set up the dgl library and always get the same DGL C++ graphbolt library error shown above..

could you list what files exist under `//dgl/graphbolt/` after you installed?

**Comment by Rhett-Ying** [comment]
Is `*.post300` a post-release version with additional bug fixes? https://discuss.pytorch.org/t/why-torch-version-returns-2-3-1-post300/206486

**Comment by LZVSDY** [comment]
install https://www.dgl.ai/pages/start.html
The versions of CUDA, PyTorch, and DGL must be compatible with each other.
