### ISSUE TITLE
AttributeError: '_OpNamespace' 'graphbolt' object has no attribute 'set_max_uva_threads'

### ISSUE THREAD

**Issue by 0913vision** [dmlc/dgl#7512]
## Code

```python3
class SAGE(nn.Module):
    def __init__(self, in_size, hidden_size):
        super().__init__()
        self.layers = nn.ModuleList()
        self.layers.append(SAGEConv(in_size, hidden_size, "mean"))
        self.layers.append(SAGEConv(hidden_size, hidden_size, "mean"))
        self.hidden_size = hidden_size
        self.predictor = nn.Sequential(
            nn.Linear(hidden_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, 1),
        )

    def forward(self, blocks, x):
        hidden_x = x
        for layer_idx, (layer, block) in enumerate(zip(self.layers, blocks)):
            hidden_x = layer(block, hidden_x)
            is_last_layer = layer_idx == len(self.layers) - 1
            if not is_last_layer:
                hidden_x = F.relu(hidden_x)
        return hidden_x

dataset = gb.BuiltinDataset("cora-seeds").load()

graph = dataset.graph
feature = dataset.feature
train_set = dataset.tasks[1].train_set
test_set = dataset.tasks[1].test_set
task_name = dataset.tasks[1].metadata["name"]
print(f"Task: {task_name}")

device = torch.device("cuda")

datapipe = gb.ItemSampler(train_set, batch_size=256, shuffle=True)
datapipe = datapipe.copy_to(device)
datapipe = datapipe.sample_uniform_negative(graph, 5)
datapipe = datapipe.sample_neighbor(graph, [5, 5])
datapipe = datapipe.transform(partial(gb.exclude_seed_edges, include_reverse_edges=True))
datapipe = datapipe.fetch_feature(feature, node_feature_keys=["feat"])
train_dataloader = gb.DataLoader(datapipe)
```

```
Traceback (most recent call last):
  File "/home/yoochan/GNN/dgl/./train.py", line 57, in <module>
    train_dataloader = gb.DataLoader(datapipe)
  File "/home/yoochan/.local/lib/python3.10/site-packages/dgl/graphbolt/dataloader.py", line 203, in __init__
    torch.ops.graphbolt.set_max_uva_threads(max_uva_threads)
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 921, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'graphbolt' object has no attribute 'set_max_uva_threads'
```

## Comment

This code is an example using graphbolt from the official documentation. I tried it with another torch (2.2.0) version and dgl, but I still get the same error. (I also tried it with colab from https://docs.dgl.ai/en/2.0.x/api/python/dgl.graphbolt.html, but dgl is not imported there at all.)

Additionally, if I directly edit the dataloader code and comment out the part where set_max_uva_threads is called, I get an error saying "RuntimeError: unique_and_compact is only available on CUDA device."

## Environment
 - DGL Version (e.g., 1.0): 2.3.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): 2.3.1+cu121
 - OS (e.g., Linux): Ubuntu 22.04
 - How you installed DGL (`conda`, `pip`, source): pip
 - Python version: 3.10.12
 - CUDA/cuDNN version (if applicable): 12.1
 - GPU models and configuration (e.g. V100): rtx2080 super

**Comment by mfbalin** [comment]
What command did you use to install dgl?
