### ISSUE TITLE
[DistGB] `dgl_partition_to_graphbolt()` crashed

### ISSUE THREAD

**Issue by Rhett-Ying** [dmlc/dgl#7815]
## To Reproduce

```
dgl.distributed.dgl_partition_to_graphbolt(
            part_config,
            store_eids=True,
            graph_formats="coo",
        )
```

```
2024-10-03 23:23:24,190 INFO Converting partitions to GraphBolt format
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/graphstorm/python/graphstorm/gpartition/convert_to_graphbolt.py", line 72, in <module>
    main()
  File "/graphstorm/python/graphstorm/gpartition/convert_to_graphbolt.py", line 62, in main
    dgl_distributed.dgl_partition_to_graphbolt(
  File "/opt/gs-venv/lib/python3.10/site-packages/dgl/distributed/partition.py", line 1991, in dgl_partition_to_graphbolt
    part_meta = _convert_partition_to_graphbolt_wrapper(
  File "/opt/gs-venv/lib/python3.10/site-packages/dgl/distributed/partition.py", line 1926, in _convert_partition_to_graphbolt_wrapper
    rel_path = convert_with_format(part_id=part_id)
  File "/opt/gs-venv/lib/python3.10/site-packages/dgl/distributed/partition.py", line 1862, in gb_convert_single_dgl_partition
    part = _load_part(part_config, part_id)
  File "/opt/gs-venv/lib/python3.10/site-packages/dgl/distributed/partition.py", line 1581, in _load_part
    graph, _, _, _, _, _, _ = load_partition(
  File "/opt/gs-venv/lib/python3.10/site-packages/dgl/distributed/partition.py", line 342, in load_partition
    part_graph_field in part_files
AssertionError: the partition does not contain graph structure: part_graph
```

## Environment

 - DGL Version (e.g., 1.0): latest nightly build
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3):
 - OS (e.g., Linux):
 - How you installed DGL (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version (if applicable):
 - GPU models and configuration (e.g. V100):
 - Any other relevant information:

**Comment by Rhett-Ying** [comment]
This issue can be reproduces by running `python -m pytest tests/distributes/test_mp_dataloader.py`
