### ISSUE TITLE
`Cannot find DGL C++ graphbolt library` for torch 2.4.1

### ISSUE THREAD

**Issue by DanielYang59** [dmlc/dgl#7822]
## 🐛 Bug

I believe this is a duplicate of `#7247` (but newer for `torch` 2.4.1).

## To Reproduce

```
>>> import dgl

Traceback (most recent call last):
  File "/Users/yang/developer/test/test_mult.py", line 1, in <module>
    import dgl
  File "/Users/yang/developer/test/venv/lib/python3.12/site-packages/dgl/__init__.py", line 16, in <module>
    from . import (
  File "/Users/yang/developer/test/venv/lib/python3.12/site-packages/dgl/dataloading/__init__.py", line 13, in <module>
    from .dataloader import *
  File "/Users/yang/developer/test/venv/lib/python3.12/site-packages/dgl/dataloading/dataloader.py", line 27, in <module>
    from ..distributed import DistGraph
  File "/Users/yang/developer/test/venv/lib/python3.12/site-packages/dgl/distributed/__init__.py", line 5, in <module>
    from .dist_graph import DistGraph, DistGraphServer, edge_split, node_split
  File "/Users/yang/developer/test/venv/lib/python3.12/site-packages/dgl/distributed/dist_graph.py", line 11, in <module>
    from .. import backend as F, graphbolt as gb, heterograph_index
  File "/Users/yang/developer/test/venv/lib/python3.12/site-packages/dgl/graphbolt/__init__.py", line 36, in <module>
    load_graphbolt()
  File "/Users/yang/developer/test/venv/lib/python3.12/site-packages/dgl/graphbolt/__init__.py", line 26, in load_graphbolt
    raise FileNotFoundError(
FileNotFoundError: Cannot find DGL C++ graphbolt library at /Users/yang/developer/test/venv/lib/python3.12/site-packages/dgl/graphbolt/libgraphbolt_pytorch_2.4.1.dylib
```

## Environment

 - DGL Version (e.g., 1.0): 2.0.0
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): pytorch 2.4.1
 - OS (e.g., Linux): MacOS 15.0.1
 - How you installed DGL (`conda`, `pip`, source): pip
 - Python version: 3.12.7

## Additional context

```
>>> ls libgraphbolt_pytorch_2.*

libgraphbolt_pytorch_2.1.0.dylib libgraphbolt_pytorch_2.2.0.dylib libgraphbolt_pytorch_2.3.0.dylib
libgraphbolt_pytorch_2.1.1.dylib libgraphbolt_pytorch_2.2.1.dylib
libgraphbolt_pytorch_2.1.2.dylib libgraphbolt_pytorch_2.2.2.dylib
```

**Comment by Alkomnenos** [comment]
Same error, have tried all combination of versions. Would appreciate a head up if someone managed to solve this ：）

**Comment by colintle** [comment]
Anyone got this working yet?

**Comment by ph-mehdi** [comment]
We still have this problem in new versions, has anyone fixed this problem?

**Comment by beviu** [comment]
As a workaround, I was able to make import `dgl` successfully by installing older versions of PyTorch and torchdata:
```console
$ pip install torch==2.2.1
$ pip install torchdata==0.7.1
```

**Comment by 523718** [comment]
In dgl website,it says:
# Since 2024.06.27, we have stopped providing packages for Windows and MacOS. The latest version of available package is 2.2.1. For newer versions, please install from source.
# If you have installed dgl-cudaXX.X package, please uninstall it first. 
may be this can give you some ideas. 

And i also met this problem,but i need to install 2.2.1version of dgl in windows 10.it seems like i should install it from source code?If anybody knows that ,please tell me how i could solve this ,thank you so much.

**Comment by Alkomnenos** [comment]
I have managed to make mine working, under the DGL package site there are several "libgraphbolt_pytorch_2.x.x.dylib" files you could find and you will know which versions of pytorch you should use. Mine issue arose from having a corrupted pytorch version registered and DGL could not properly recognize the pytorch 2.2.1 that I have installed, manually removing the corrupted pytorch files from site-packages has fixed the problem for me

**Comment by DanielYang59** [comment]
> Since 2024.06.27, we have stopped providing packages for Windows and MacOS. The latest version of available package is 2.2.1. For newer versions, please install from source.

Thanks for sharing the info. It looks like [dgl only ship binary distributions for Windows for 2.2.1](https://pypi.org/project/dgl/2.2.1/#files).

---

Also I appreciate everyone's comment, however downgrading to `torch==2.2.1` is not a solution.


It turns out [dgl does ship pre-built binary here](https://www.dgl.ai/pages/start.html), but only for certain versions of `torch` and `python`, for other version we might need to [build from source](https://docs.dgl.ai/install/index.html#install-from-source).

**Comment by Akash-bu** [comment]
Any updates? I am also facing this issue for my mac.

**Comment by Infraste03** [comment]
I managed to solve the issue by aligning the library versions.
In my case, the incompatibility came from mismatched DGL and PyTorch versions.
Here are the working setups that I successfully tested both on Windows and CentOS:
torch==2.1.2
torchvision==0.16.2
torchaudio==2.1.2
dgl==0.9.1
recbole==1.2.1
python==3.10

After reinstalling DGL from PyPI and ensuring that my PyTorch version matched the installed CUDA toolkit, everything worked correctly on both operating systems.

Hope this helps anyone facing the same issue!
