### ISSUE TITLE
Running the same code on GPU fails with error Tensor object has no attribute local_var

### ISSUE THREAD

**Issue by lichen11** [dmlc/dgl#834]
I ran the same code 
    python3 train.py --dataset cora --self-loop 
on both CPU and GPU versions of dgl. 
I am using Python 3.7. For GPU, I use cuda 9.0.
On CPU, the code works well. However in GPU, I received the following error:

Traceback (most recent call last):
  File "train.py", line 143, in <module>
    main(args)
  File "train.py", line 99, in main
    logits = model(features)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/nfs/Documents/Work/Security/GNN/Code/dgl-master/examples/pytorch/gcn/gcn.py", line 38, in forward
    h = layer(h, self.g)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/dgl/nn/pytorch/conv.py", line 131, in forward
    graph = graph.local_var()
AttributeError: 'Tensor' object has no attribute 'local_var'

Any idea how to fix this? Thank you!

**Comment by VoVAllen** [comment]
Which `train.py` are you using?

**Comment by yzh119** [comment]
@lichen11 , Hi, we changed the order of arguments of `dgl.nn.pytorch.conv.GraphConv` from `feat, graph` to `graph, feat` in DGL v0.3.1, so please check if you have updated the example code to its latest version.

**Comment by mjam57** [comment]
Hi, is the train.py code updated with this change? I have the 0.3.1 DGL version.
