### ISSUE TITLE
data.read_only? in sampler

### ISSUE THREAD

**Issue by mjam57** [dmlc/dgl#844]
Hi, 

I'm using my own data for gcn_ns_sc.py. https://github.com/dmlc/dgl/blob/master/examples/pytorch/sampling/gcn_ns_sc.py

I'm using my own edgelist for this code. I'm seeing this error:
Traceback (most recent call last):
  File "C:/Users/mjamma/PycharmProjects/grades/gcn_ns_sc_rmat.py", line 304, in <module>
    main(args)
  File "C:/Users/mjamma/PycharmProjects/grades/gcn_ns_sc_rmat.py", line 231, in main
    seed_nodes=train_nid):
  File "C:\Users\mjamma\AppData\Local\Continuum\anaconda3\envs\grades\lib\site-packages\dgl\contrib\sampling\sampler.py", line 319, in __init__
    ThreadPrefetchingWrapper)
  File "C:\Users\mjamma\AppData\Local\Continuum\anaconda3\envs\grades\lib\site-packages\dgl\contrib\sampling\sampler.py", line 153, in __init__
    raise NotImplementedError("This loader only support read-only graphs.")
NotImplementedError: This loader only support read-only graphs.

What do you suggest to overcome this?

This is with 0.3.1 dgl version.

Thanks
Madhuri

**Comment by VoVAllen** [comment]
After constructing DGLGraph `g`, you can call `g.readonly()`. It will transform g into a read-only(immutable) graph as an in-place operation.

**Comment by jermainewang** [comment]
Closed due to inactivity. Please reopen if issue still exists.
