### ISSUE TITLE
Question about graph regression with GIN, 

### ISSUE THREAD

**Issue by fatemehteimury** [dmlc/dgl#856]
## ❓ Questions and Help

Before proceeding, please note that we recommend
using our discussion forum (https://discuss.dgl.ai) for
general questions. As a result, this issue will
likely be CLOSED shortly.

**Comment by fatemehteimury** [comment]
Thanks for your reply. 
one more question  https://alchemy.tencent.com/data/dgl/valid_processed.zip and  https://alchemy.tencent.com/data/dgl/test_processed.zip don't exist so I cannot run the code. can you provide the preprocessing code as well or check this bug?

Thanks

**Comment by mufeili** [comment]
@fatemehteimury Could you please update to the latest version of DGL by installing from the source and see if the issue resolves?

**Comment by fatemehteimury** [comment]
Hi, 
I uninstalled and install the latest version of the DGL and again I get the same error. 
Besides I can't download https://alchemy.tencent.com/data/dgl/valid_processed.zipfrom web browser as well. 
Can you send me the zip file of valid_preproccessed
 Thanks,

**Comment by mufeili** [comment]
Update: datasets sent

**Comment by fatemehteimury** [comment]
Thanks Mufei, 
I installed the latest version of DGL and now I don't have the previous problem. Unfortunately, I get a new error. 

This is my error:

 python regression.py -m SCHNET -d Alchemy
99776 loaded!
3951 loaded!
Traceback (most recent call last):
  File "regression.py", line 113, in <module>
    main(args)
  File "regression.py", line 89, in main
    run_a_train_epoch(args, epoch, model, train_loader, loss_fn, score_fn, optimizer)
  File "regression.py", line 26, in run_a_train_epoch
    for batch_id, batch_data in enumerate(data_loader):
  File "/home/t_teimf/anaconda3/envs/GIN_cls/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/t_teimf/anaconda3/envs/GIN_cls/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/t_teimf/anaconda3/envs/GIN_cls/lib/python3.6/site-packages/dgl-0.4-py3.6-linux-x86_64.egg/dgl/data/chem/alchemy.py", line 246, in __getitem__
    return g.smile, g, l
AttributeError: 'DGLGraph' object has no attribute 'smile'

**Comment by mufeili** [comment]
1. Could you please go to `.dgl` directory and remove any file/folder related to Alchemy and try again? Note `.dgl` is the dir for holding datasets for DGL.
2. If this still does not work. Try setting `from_raw=True` when initializing `TencentAlchemyDataset` in `regression.py`.

**Comment by fatemehteimury** [comment]
Thanks for your help. It's working now. 
I have one more question: I preprocessed my own dataset in the same way as alchemy so I have a list of DGLGraph and a list of tensors as a graph label. 

But when I run the code it gives me this error:
Traceback (most recent call last):
  File "regression.py", line 113, in <module>
    main(args)
  File "regression.py", line 89, in main
    run_a_train_epoch(args, epoch, model, train_loader, loss_fn, score_fn, optimizer)
  File "regression.py", line 26, in run_a_train_epoch
    for batch_id, batch_data in enumerate(data_loader):
  File "/home/t_teimf/anaconda3/envs/GIN_cls/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/t_teimf/anaconda3/envs/GIN_cls/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/t_teimf/anaconda3/envs/GIN_cls/lib/python3.6/site-packages/dgl-0.4-py3.6-linux-x86_64.egg/dgl/data/chem/alchemy.py", line 246, in __getitem__
    return g.smile, g, l
AttributeError: 'DGLGraph' object has no attribute 'smile'


My question is how should I prepare smile for my own dataset? Moreover my dataset it's not a chemical dataset or is it possible to remove it for my dataset?

Thanks

**Comment by fatemehteimury** [comment]
Hi, 
Thanks for your great help. It works.

**Comment by mufeili** [comment]
Close the issue as questions have been split and moved to the discussion forum: https://discuss.dgl.ai/t/multi-gpu-gat-and-model-zoo/434.
