### ISSUE TITLE
train examples/pytorch/jtnn fail 

### ISSUE THREAD

**Issue by ZENGXH** [dmlc/dgl#934]
## 🐛 Bug

Fail to run training scripts for jtnn examples 

## To Reproduce

1. `cd examples/pytorch/jtnn`
2. `python vaetrain_dgl.py`

## Expected behavior

Error message: 
```
Downloading /h/xiaohui/.dgl/jtnn.zip from https://s3-ap-southeast-1.amazonaws.com/dgl-data-cn/dataset/jtnn.zip...
Extracting file to /h/xiaohui/.dgl/jtnn
Loading data...
Loading finished.
        Num samples: 220011
        Vocab file: /h/xiaohui/.dgl/jtnn/vocab.txt
vaetrain_dgl.py:54: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
  nn.init.xavier_normal(param)
vaetrain_dgl.py:52: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(param, 0)
Model #Params: 1221K
Traceback (most recent call last):
  File "vaetrain_dgl.py", line 142, in <module>
    train()
  File "vaetrain_dgl.py", line 80, in train
    for it, batch in enumerate(dataloader):
  File "/scratch/gobi2/xiaohui/miniconda3/envs/pyt12/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/scratch/gobi2/xiaohui/miniconda3/envs/pyt12/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 606, in _process_next_batch
    raise Exception("KeyError:" + batch.exc_msg)
Exception: KeyError:Traceback (most recent call last):
  File "/scratch/gobi2/xiaohui/miniconda3/envs/pyt12/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/scratch/gobi2/xiaohui/miniconda3/envs/pyt12/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/scratch/gobi2/xiaohui/code/dgl/examples/pytorch/jtnn/jtnn/datautils.py", line 53, in __getitem__
    wid = _set_node_id(mol_tree, self.vocab)
  File "/scratch/gobi2/xiaohui/code/dgl/examples/pytorch/jtnn/jtnn/datautils.py", line 23, in _set_node_id
    wid.append(vocab.get_index(mol_tree.nodes_dict[node]['smiles']))
  File "/scratch/gobi2/xiaohui/code/dgl/examples/pytorch/jtnn/jtnn/mol_tree.py", line 16, in get_index
    return self.vmap[smiles]
KeyError: 'C1=CN=NC=C1'

```

## Environment

 - DGL Version (e.g., 1.0): 0.3.1 
 - Backend Library & Version (e.g., PyTorch 0.4.1, MXNet/Gluon 1.3): PyTorch 1.1.0
 - OS (e.g., Linux): Linux 
 - How you installed DGL (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.4 
 - CUDA/cuDNN version (if applicable): 9.0
 - GPU models and configuration (e.g. V100): TITAN Xp 
 - Any other relevant information:

**Comment by VoVAllen** [comment]
Hi,

I guess this is due to rdkit's version. Please use rdkit 2018.09.3 as recommended [here](https://github.com/dmlc/dgl/blob/9df8cd324207d3924439c3d912229811e34687f0/examples/pytorch/model_zoo/chem/README.md#dependencies).

**Comment by VoVAllen** [comment]
Closed due to inactive. Please reopen this if you have any further questions.
